### ISSUE TITLE
AntiPrompt in generated result

### ISSUE THREAD

**Issue by xbotter** [SciSharp/LLamaSharp#10]
In the example of WebApi, AntiPrompt is used, and it always appears in the final generated result. Is this a feature or am I using the wrong method?
![image](https://github.com/SciSharp/LLamaSharp/assets/3634877/05ebd8bc-fdc5-4fc9-845b-9a67af33de90)

**Comment by Oceania2018** [comment]
Same question in the [BotSharp](builder.Services.AddLlamaSharp(builder.Configuration)) when using `LLamaSharp`.

**Comment by AsakusaRinne** [comment]
In version 0.4.0 a solution is provided, as shown in [this example](https://scisharp.github.io/LLamaSharp/0.4/Examples/ChatSessionStripRoleName/), using transforms to remove the names.

**Comment by xbotter** [comment]
Well done, thank you for your work.
