### ISSUE TITLE
Typo in the code in the main Readme.md file

### ISSUE THREAD

**Issue by MrYossu** [SciSharp/LLamaSharp#1000]
### Description

The code includes the following...

```c#
InferenceParams inferenceParams = new InferenceParams()
{
    MaxTokens = 256, // No more than 256 tokens should appear in answer. Remove it if antiprompt is enough for control.
    AntiPrompts = new List<string> { "User:" } // Stop generation once antiprompts appear.

    SamplingPipeline = new DefaultSamplingPipeline(),
};
```

This causes a compiler error as there should be a comma at the end of the line that sets `AntiPrompts` (before the `\\` obviously).

Not a major issue, but worth fixing.

**Comment by martindevans** [comment]
Definitely worth fixing! Would you like to make a PR for it?

**Comment by MrYossu** [comment]
@martindevans I don't have time to do it at the moment ([playing with repo](https://github.com/SciSharp/LLamaSharp/issues/999) is already eating up my lack of spare time!), so if any of the maintainers can do it, it would be a lot faster. If not, I'll se when I can do it.

**Comment by MrYossu** [comment]
@martindevans Thanks for doing that. Definitely faster than I would have done it!

Any chance you could look at [the other issue I opened](https://github.com/SciSharp/LLamaSharp/issues/999)? That's a real issue, and is preventing me from trying this package.

Thanks again.
