### ISSUE TITLE
model bin file?

### ISSUE THREAD

**Issue by TheDevelolper** [SciSharp/LLamaSharp#106]
Hey, I followed the instructions for llama2 and I've downloaded all the folders with various files which looks like this 

checklist.chk  
consolidated.00.pth  
consolidated.01.pth  
params.json

Looking at your unit tests it seems that you're expecting a bin file? 

How can I either get the lib to work with these files or where is the bin file? I'm suspect this might have something to do with llama2 vs llama1?

**Comment by TheDevelolper** [comment]
![image](https://github.com/SciSharp/LLamaSharp/assets/4026553/c67ec9db-92e2-4548-8a61-117e14603471)
This also seems true for the models on hugging face?

**Comment by SignalRT** [comment]
You need ggml models. TheBloke repository contains a lot of converted models:

https://huggingface.co/TheBloke

In the near future this format will change

![image](https://github.com/SciSharp/LLamaSharp/assets/16475613/95fb0678-68c8-494b-8e62-f4a0e1863c50)

**Comment by TheDevelolper** [comment]
Ah thank you. I did come across his stuff but I wasn't sure!
