### ISSUE TITLE
SEHException when trying to load pygmalion model

### ISSUE THREAD

**Issue by et118** [SciSharp/LLamaSharp#11]
I have been messing around with trying to load a [ggml pygmalion model](https://huggingface.co/notstoic/pygmalion-13b-4bit-128g) which I have converted to ggml using llama.cpp. I can run it in both in [Gpt4All](https://github.com/nomic-ai/gpt4all) using the C# wrapper and in [Oobabooga's text generation web UI](https://github.com/oobabooga/text-generation-webui).

Unfortunately every time I am trying to load the model using LLamaSharp i get this error:
`System.Runtime.InteropServices.SEHException: 'External component has thrown an exception.'`
Which originates from :
`extern IntPtr llama_init_from_file(string path_model, LLamaContextParams params_);`

Here is my code:
```C#
namespace AiTest
{
	internal class Program
	{
		static void Main(string[] args)
		{
			Console.WriteLine("Hello, World!");
			LLamaModel model = new LLamaModel(new LLamaParams(model: "pygmalion-13b-4bit-128g-gpt-j\\ggml-model-q4_1.bin", n_ctx: 512, repeat_penalty: 1.0f, n_gpu_layers: 20));
		}
	}
}
```

Gpt4All says that the model is in the `ggjt v1 (latest)` format if that helps.

**Comment by AsakusaRinne** [comment]
Hi, in the [huggingface repo](https://huggingface.co/notstoic/pygmalion-13b-4bit-128g/tree/main) there's not such a file named `ggml-model-q4_1.bin`. I guess you made the conversion and quantization yourself. Could you please provide some descriptions of

**Comment by et118** [comment]
I used the command `python convert.py models\pygmalion-13b-4bit-128g-gpt-j\4bit-128g.safetensors` with the newest version of llama.cpp to generate the file. As I said before it worked in Gpt4All and Oobabooga but not in LLamaSharp. Maybe the llama versions aren't matching? 
Here is a [link](https://drive.google.com/file/d/1kNtGWfg1ZeQGl-jGNCFkTyAcy6ncS5yZ/view?usp=sharing) to my converted model

**Comment by AsakusaRinne** [comment]
Please checkout `llama.cpp` to `7e4ea5beff567f53be92f75f9089e6f11fa5dabd` and try again. I've tried it in my local environment and it worked. It's sometimes annoying that `llama.cpp` updates too quickly with too many beak changes. We'll attach the llama.cpp code to the next release. Thank you for reporting this issue.

We'll also upload the quantized models to [our huggingface repo](https://huggingface.co/AsakusaRinne/LLamaSharpSamples/tree/v0.3.0) later.

**Comment by AsakusaRinne** [comment]
The models have been uploaded. You can also download them directly to use.

**Comment by AsakusaRinne** [comment]
I use this python code:
```py
convert.main(['--outtype', 'f32', '--', '4bit-128g.safetensors'])
```

Then as an optional choice, you can quantize it.

**Comment by et118** [comment]
Oh. I thought convert.py also quantized the model because you could pass in `--outtype q4_1`. When I converted and later quantized the model using quantize.exe it finally worked. Thanks a lot!
