### ISSUE TITLE
Is the LLamaWeights.cs file not yet in the LLama Namespace (LLamaSharp 0.4.2 preview)?

### ISSUE THREAD

**Issue by PsillyPseudonym** [SciSharp/LLamaSharp#110]
I'm using the 0.4.2 preview of LLamaSharp, trying to follow the new Save/Load states examples but LLamaWeights.cs is not in any of the LLama Namespaces.

**Comment by martindevans** [comment]
It's just in the root `LLama` namespace (see [here](https://github.com/SciSharp/LLamaSharp/blob/master/LLama/LLamaWeights.cs#L7)), but I don't think it's been released in a nuget package yet.

The examples in the docs seem to be correct for the currently released version: https://scisharp.github.io/LLamaSharp/0.4/Examples/LoadAndSaveState/

Alternatively you can pull `master` and use the new system. If you do I'd be very interested to hear any feedback you have about the new system.

**Comment by PsillyPseudonym** [comment]
Thanks for your response. I'll try pulling master later and test out the new system. With the current release (0.4.2) for some reason, when using ChatSession.SaveState or InteractiveExecutor.SaveState, there's sometimes an error writing the JSON file and I haven't been able to figure out what causes it as it sometimes works even though I haven't changed anything: 

"System.ArgumentException: '.NET number values such as positive and negative infinity cannot be written as valid JSON.' "

I guess it doesn't really matter if it's changing for a future release. InteractiveExecutor.Model.SaveState seems to be working though but that doesn't save a JSON file, only a model file. Don't know if that's important or not.

**Comment by martindevans** [comment]
> "System.ArgumentException: '.NET number values such as positive and negative infinity cannot be written as valid JSON.' "

Can you find out which field is the invalid value? That probably indicates a bug somewhere else, putting a bad value into the state.

**Comment by PsillyPseudonym** [comment]
I just loaded an older version of my program that wasn't working but now both ChatSession.SaveSession and InteractiveExecutor.SaveState are working again. I don't know what's going on. 
I wrote above that nothing's changing between it intermittently working but realised that I have been using different types of models so I tested a few and they all worked. Really bizarre! If it happens again, I'll try getting those details for you.

**Comment by PsillyPseudonym** [comment]
So I've been able to consistently replicate the bug. It appears to be a problem with AntiPrompts. 
The program generates the JSON error whenever you try to save the session when the antiprompt (in this case, "User:") is the last token of the initial setup prompt, i.e. :  "You are an AI assistant. Answer any questions given. User:"  

(This bug didn't always show up for me because I sometimes put my instructions/query directly in the initial prompt after "User:")

I can't see how it's trying to write the JSON file as that's all handled in the nuget package.

**Comment by martindevans** [comment]
I think this was fixed a while ago, so I'll close this issue. But feel free to re-open if it's still a problem
