### ISSUE TITLE
GitHub Action Compiling Dependencies

### ISSUE THREAD

**Issue by martindevans** [SciSharp/LLamaSharp#123]
Rather than hand building the dependencies for every release we could set up a system that builds them all in a GitHub action.

We could:
1. Have a file that defines the commit id
2. Have an action that pulls the main llama.cpp repo at that commit
3. Runs builds for Windows, Linux and MacOS
4. Packages the binaries into the right location and opens a PR on this repo
5. Auto run that action every week

This would mean that updating to a new version of llama.cpp would be much easier and done more frequently. The PR would be auto opened and CI would run to check if it works, if it doesn't then it's obvious someone needs to modify the PR to fix things.

**Comment by martindevans** [comment]
WIP: https://github.com/martindevans/LLamaSharp/tree/cron_job

**Comment by AsakusaRinne** [comment]
I'm late to see this good idea. Is there any help needed for the binary release? BTW, I remember that github action only has intel MAC instead of M1/M2 MAC. Is there already a fix for it?

**Comment by martindevans** [comment]
> I'm late to see this good idea. Is there any help needed for the binary release?

I've done most of the work for the compiling of binaries in the new GitHub action (currently only manually triggered). This pulls in the master branch from llama.cpp and builds for:
 - Windows
 - Windows+CUBLAS
 - Linux
 - MacOS (ARM64)
 - MacOS (x86_64)

I have _not_ yet done a metal build for MacOS. I have no idea how that works, so any help there would be really good.

> BTW, I remember that github action only has intel MAC instead of M1/M2 MAC. Is there already a fix for it?

Unfortunately not, Mac runners are still all x86_64. I've set up the new action to cross compile, so it can create the ARM64 binaries, it just can't run them. That does mean we still have no way to test ARM64 though :(

**Comment by martindevans** [comment]
I just noticed the GitHub action doesn't include cuda .so files either, so that needs doing as well.

**Comment by martindevans** [comment]
I've managed to work out the Linux cuda build, turns out it was basically the same as the Windows one. Fortunately we don't need a GPU for compiling CUDA, although it might be a good idea to run some CI on a GPU server in the future.

Someone [gave me some tips](https://github.com/SciSharp/LLamaSharp/pull/122#issuecomment-1697338329) on how to build for metal, so I will investigate adding that to the GitHub action. But that probably won't be until next weekend.

**Comment by SignalRT** [comment]
@martindevans , I post that on the issue related to the flags used to compile on MacOS with and without Metal https://github.com/SciSharp/LLamaSharp/issues/38#issuecomment-1681052923

**Comment by SignalRT** [comment]
In my Fork I have a different workflow and a Self-Hosted action to pass the MacOS test in my computer.

**Comment by SignalRT** [comment]
@martindevans Once that we are able to generate all the binaries from Actions. Do we agree that this binaries should be committed to master/LLama/runtime in a daily frequency (that's an example)?. In that way we are sure that we are aligned with llama.cpp and that the binaries are generated without modifications.

**Comment by martindevans** [comment]
Yeah that's basically the idea. I was thinking that rather than committing directly to master it would open up a PR with the new binaries occasionally (e.g. weekly). The CI would then run on that PR and tell us if anything has broken (since llama.cpp has such an unstable interface I would expect some human intervention required most times).

**Comment by martindevans** [comment]
I just noticed that one of the recent updates (https://github.com/ggerganov/llama.cpp/releases/tag/b1250) has enabled building the shared libs for all Windows builds. Maybe the GitHub action for building binaries should be updated to just download those directly?

That would save a _lot_ of time in the build process (compiling Windows+CUDA takes about 20 minutes).
