### ISSUE TITLE
gguf implementation from llama.cpp broke lib?

### ISSUE THREAD

**Issue by conneroisu** [SciSharp/LLamaSharp#129]
I can no longer at runtime create an Interactive Executor within both a console only and WPF Project.

Thinking that this might have something to do with the upgrade to the new binary llm format  gguf within the llama.cpp project.

**Comment by martindevans** [comment]
LLamaSharp doesn't support GGUF models yet, you still need to use GGML models. Support for that is under development in #122, so you could also pull that branch and use it directly if you like (testing is always appreciated!)

**Comment by martindevans** [comment]
GGUF support released last week 🥳
