### ISSUE TITLE
error loading model: unknown (magic, version) combination: 46554747, 00000002; is this really a GGML file?

### ISSUE THREAD

**Issue by jack20951948** [SciSharp/LLamaSharp#148]
I tried to fine-tuned llama2-7b model with this instruction => https://blog.ovhcloud.com/fine-tuning-llama-2-models-using-a-single-gpu-qlora-and-ai-notebooks/
Then i ran `python3 llama.cpp/convert.py ./results/llama2/final_merged_checkpoint/ --outtype f16 --outfile ./results/llama2/final_merged_checkpoint/ggml-model-f16.bin` to make it into a .bin model file. It went well with llama.cpp but showed error with LLamaSharp:
![image](https://github.com/SciSharp/LLamaSharp/assets/56648560/ab0c9907-5bff-4075-b02a-c855c5d9bfc1)

**Comment by martindevans** [comment]
It looks like that magic number indicates a GGUF v2 file (https://github.com/ggerganov/llama.cpp/blob/d59bd97065cd7ded6c4ecab54b1d5e0b1b11e318/ggml.h#L226). Support for GGUF is merged into master, but is not yet released to nuget. You'll need to pull master (or wait for those packages to be released).

**Comment by jack20951948** [comment]
@martindevans Thanks for your reply!
Is there any other step i need to do after pull master? Because this pic was capture with the latest main branch yesterday.

**Comment by martindevans** [comment]
Just a heads up that the GGUF support has now been released to nuget, so you could switch back and upgrade to 0.5.1 to get the same fixes :)
