### ISSUE TITLE
使用Run a LLamaModel with instruct mode，在回答完第一个问题之后，出现了自动回答的bug

### ISSUE THREAD

**Issue by KKD4Soei** [SciSharp/LLamaSharp#15]
![image](https://github.com/SciSharp/LLamaSharp/assets/58964439/d066f3e8-0054-4b0b-b6b0-681eec8d87bc)

**Comment by AsakusaRinne** [comment]
这个问题目前正在修复中，修复后会在这里告知您。

**Comment by KKD4Soei** [comment]
好 感谢！

**Comment by AsakusaRinne** [comment]
您好，现在这个问题应该已经解决了，然后同时，这个问题的出现也可能是因为anti-prompt没有设置正确，现在最新版本有详细文档了，可以参考这里：https://scisharp.github.io/LLamaSharp/0.4/Tricks/

**Comment by KKD4Soei** [comment]
非常感谢

**Comment by AsakusaRinne** [comment]
请问这个问题现在已经确认解决了吗？新版本0.5.1发布了，欢迎尝试。如果确认问题已经解决我会关掉这个issue。

**Comment by martindevans** [comment]
It looks like this was resolved a while ago, so I'll close this issue. If it's still a problem please do comment and re-open the issue!
