### ISSUE TITLE
LoadState error

### ISSUE THREAD

**Issue by mphacker** [SciSharp/LLamaSharp#151]
Version 0.5.1 with Cuda12 backend.

When calling LoadState on the InteractiveExecutor instance I am getting the following error:

System.Text.Json.JsonReaderException: 't' is invalid after a single JSON value. Expected end of data. LineNumber: 0 | BytePositionInLine: 237.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)

To repo, create an InteractiveExecutor, use SaveState to save to a file and then LoadState.

**Comment by martindevans** [comment]
Could you share a copy of the JSON file?

**Comment by mphacker** [comment]
Here is an image of it in VS code.  Is the SaveState supposed to just write out well formed JSON?  It looks like it is writing out a bunch of odd data after the JSON.
![image](https://github.com/SciSharp/LLamaSharp/assets/16866813/16beeffe-c431-44fd-b8b5-ff28d6db1ada)

If you need the full file I can try to paste it here.

**Comment by saddam213** [comment]
We need to change `FileMode.OpenOrCreate` to ` FileMode.Create` so it overwrites the entite file

**Comment by martindevans** [comment]
This isn't part of llamasharp I'm very familiar with, but it does look like it's just meant to be valid JSON. Here's the relevant code:

```csharp
InteractiveExecutorState state = (InteractiveExecutorState)GetStateData();
using(FileStream fs = new FileStream(filename, FileMode.OpenOrCreate, FileAccess.Write))
{
    JsonSerializer.Serialize(fs, state);
}
```

I think it's because it's using `OpenOrCreate`, so there's still junk in the file if the new content is _smaller_ than the old content.

Try deleting the file before saving.

**Comment by mphacker** [comment]
Deleting the file before saving works well.

**Comment by martindevans** [comment]
I just pushed up a PR that _should) fix this, could you confirm if using the `master` branch fixes it?
