### ISSUE TITLE
Design Discussion: Async Support?

### ISSUE THREAD

**Issue by martindevans** [SciSharp/LLamaSharp#166]
Currently LLamaSharp is in a bit of an awkward position with `async` support.

 - `ILLamaExecutor` specifies two infer methods, one async and one non-async.
 - All implementations of `InferAsync` currently just call `Infer`, which is useless!
 - Inference itself is not _really_ async (although we could make it act like it).
 - There are some things LLamaSharp does which _could_ be async (e.g. saving/loading session files), but they're not because they're implemented in the non-async `Infer` method. Making these async would require duplicating a huge amount of inference code.

So we're in the position that we pretend to have async, but don't actually have async, and the small amount of work we have which _could_ be async isn't!

### Option 1: Remove Async

Right now the library is not really async, the small amount of IO work that is in the library isn't async and all inference computations block. So we could just remove async support altogether and lose nothing.

### Option 2: Remove Non-Async

The other option is to remove _non_ async support. That way the inference code would all be in an async context - any IO work would be easy to make properly async and the expensive computations (i.e. `Eval()`) could be done in a `Task.Run` call and awaited to not block the calling thread.

---

Personally I prefer option 2. But I realise that requiring async may not be preferred by everyone! Thoughts?

**Comment by mingyangzhu** [comment]
Support  Option 2: Remove Non-Async

**Comment by saddam213** [comment]
`IAsyncEnumearabe` as extenseins for syncronous Enumerable `ToBlockingEnumerable ` if I remember correctly

So if the default infer was Async then we can easily give users an sync version with a simple `Infer().ToBlockingEnumerable()`

So if we reversed implemetation like you suggest we can support both

**Comment by drasticactions** [comment]
I agree, it's easy enough to make the async version non-async if you want to, and having one implmentation that does the things it says makes sense to me.

**Comment by SignalRT** [comment]
Support Option 2: Remove Non-Async

**Comment by martindevans** [comment]
Is it safe to convert async into non async with something like ToBlockingEnumerable? See this answer by Eric Lippert for example: https://stackoverflow.com/questions/45034554/how-to-correctly-block-on-async-code

**Comment by saddam213** [comment]
> Is it safe to convert async into non async with something like ToBlockingEnumerable? See this answer by Eric Lippert for example: https://stackoverflow.com/questions/45034554/how-to-correctly-block-on-async-code

If your worried about the .NET implemetation of `ToBlockingEnumerable` just do the Async stuff, any end user can use the extesion method themselfs in thier own app

No need for LLamaSharp to explicitly provide it

**Comment by martindevans** [comment]
I've opened PR #173 with the minimal changes to make things async-only, so we can see what this would look like.

There's no sync version for now, but if we do want that it can easily be added an an extension method to `ILLamaExecutor`.
