### ISSUE TITLE
[Feature Request] Support InternLM Deploy

### ISSUE THREAD

**Issue by vansinhu** [SciSharp/LLamaSharp#168]
Dear LLamaSharp developer,

Greetings! I am vansinhu, a community developer and volunteer at InternLM. [InternLM](https://github.com/InternLM/InternLM) is a large language model similar to llama2, and we look forward to InternLM being supported in LLamaSharp. If there are any challenges or inquiries regarding support for InternLM, please feel free to join our Discord discussion at https://discord.gg/gF9ezcmtM3. 

Best regards,
vansinhu

**Comment by martindevans** [comment]
Is InternLM supported by llama.cpp? If it is then we probably already support it!

**Comment by geffzhang** [comment]
https://github.com/InternLM/InternLM/issues/258

**Comment by martindevans** [comment]
Some related upstream issues:
 - https://github.com/ggerganov/llama.cpp/issues/3133
 - https://github.com/ggerganov/llama.cpp/issues/3551

**Comment by martindevans** [comment]
https://github.com/ggerganov/llama.cpp/pull/4283

**Comment by martindevans** [comment]
https://github.com/ggerganov/llama.cpp/pull/5184 has been merged (4 days ago), therefore #479 should include InternLM support for LLamaSharp.

**Comment by martindevans** [comment]
0.10.0 has just been released which should include InternLM support at long last!
