### ISSUE TITLE
SEHE exception

### ISSUE THREAD

**Issue by suchoss** [SciSharp/LLamaSharp#17]
Hello, 

I have downloaded your `Llama.Examples` project, downloaded `ggml-model-f32-q4_0.bin` from https://huggingface.co/AsakusaRinne/LLamaSharpSamples/tree/v0.3.0/LLaMa/7B 

And when I publish code for `win-x64` runtime, then I am not able to run it on Windows. I am getting following errror:
```
Fatal error. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
Repeat 2 times:
--------------------------------
   at LLama.Native.NativeApi.llama_init_backend()
--------------------------------
   at LLama.Native.NativeApi..cctor()
   at LLama.Native.NativeApi.llama_context_default_params()
   at LLama.Utils.llama_init_from_gpt_params(LLama.LLamaParams ByRef)
   at LLama.LLamaModel..ctor(LLama.LLamaParams, System.String, Boolean, System.String)
   at LLama.Examples.ChatSession..ctor(System.String, System.String, System.String[])
   at Program.<Main>$(System.String[])
```

**Comment by AsakusaRinne** [comment]
Hi, which version of `LLamaSharp.Backend` did you install?

**Comment by suchoss** [comment]
Hi I have installed 
```
<PackageReference Include="LLamaSharp" Version="0.3.0" />
<PackageReference Include="LLamaSharp.Backend.Cpu" Version="0.3.0" />
```

**Comment by AsakusaRinne** [comment]
Unfortunately I couldn't reproduce this error. Is there any other information? For example your cpu and system info, your runtime version, etc..

**Comment by suchoss** [comment]
I tried to run/debug it on Macbook M1 and figured it won't work, so I released it for `win-x64` and run it on following system:
<img width="681" alt="image" src="https://github.com/SciSharp/LLamaSharp/assets/39336141/ec0c038e-9fe9-49c5-8aa7-26f708979712">

Dotnet runtime is `7.0.302` and project's target framework is `<TargetFramework>net7.0</TargetFramework>`

**Comment by AsakusaRinne** [comment]
Mac has not been supported now because I don't have a MacBook and it seems this is the reason for the error. Could you please try building from source with llama.cpp? If time is not limited for you, you can also wait for the new release of `LLamaSharp.Backend`. Someone in discord promised to compile it in Mac and make a PR.

**Comment by suchoss** [comment]
I will try llama.cpp. But the main thing that bothers me is, that it doesn`t work even on Win-server.

**Comment by AsakusaRinne** [comment]
Does it throw the same exception when running on windows server?

**Comment by suchoss** [comment]
This exception reported above is from Windows server. 

Exception which I am getting from MacOS is different and I didn't reported because I thought it is not supported. I saw no reason to bother you with M1 issues 😄

**Comment by AsakusaRinne** [comment]
I see. How many memories are there in your windows server? I am guessing if it's the memory problem because LLM requires a lot of memories.

**Comment by suchoss** [comment]
21,6 GB total - 18,6 GB free

What is memory requirement?

**Comment by AsakusaRinne** [comment]
The memory is enough for 7B and 13B models. Unfortunately I don't have windows server, either. What I can do is using cloud server, but I have only 2-4 GB memories, which is too few to run LLM. I think compiling llama.cpp in debug mode and run it directly will give you more information about this error.

**Comment by suchoss** [comment]
Thanks for Your help.

**Comment by AsakusaRinne** [comment]
Thanks to the community effort, `LLamaSharp.Backend.Cpu` 0.3.1 has included MAC support. I hope it is of some help to you. :)
