### ISSUE TITLE
Dll not found exception on test

### ISSUE THREAD

**Issue by KangHyeonSeok** [SciSharp/LLamaSharp#2]
I'm not sure if I can register an issue or if I have a guide on how to register an issue, but I'd like to try this project, so excuse me.

I downloaded 0.2.1 and ran the test and got the error.
The error couldn't find the dll 'libllama'. I tried on Windows 11 and Mac Big Sur.

Is there a way to solve the above problem? Or is there anything I did wrong or should I missed?

![image](https://github.com/SciSharp/LLamaSharp/assets/31717201/607620c5-516a-49ea-95d9-d9b7cbc6ead9)

**Comment by AsakusaRinne** [comment]
Hi, are you using LLama with only CPU? Please install `LLamaSharp.Cpu v0.2.1` for using cpu only.

**Comment by KangHyeonSeok** [comment]
I installed the module you mentioned. It works! I really appreciate your help.

![image](https://github.com/SciSharp/LLamaSharp/assets/31717201/5f00775b-4f7e-46cf-9b4c-56e61a55fa41)

**Comment by AsakusaRinne** [comment]
Oh, God, The question you asked in the screenshot is exactly the same with what I asked it at the first time! 🤣

**Comment by KangHyeonSeok** [comment]
Because the question was included in the test code! Sounds like a good question to start a conversation with AI. I think I will use it often, too.

**Comment by AsakusaRinne** [comment]
😁😁
