### ISSUE TITLE
Adapts to SK Kernel Memory

### ISSUE THREAD

**Issue by geffzhang** [SciSharp/LLamaSharp#200]
https://github.com/microsoft/kernel-memory

**Comment by AsakusaRinne** [comment]
@xbotter Hey, would you like to help with it? :) Seems that it could provide ability of vector storage and search. There's already a simple [example](https://github.com/microsoft/kernel-memory/tree/0db634b9868806b91a705bddcf875e6107f0e441/examples/009-dotnet-custom-LLM) for using with LLamaSharp.

**Comment by xbotter** [comment]
> @xbotter Hey, would you like to help with it? :) Seems that it could provide ability of vector storage and search. There's already a simple [example](https://github.com/microsoft/kernel-memory/tree/0db634b9868806b91a705bddcf875e6107f0e441/examples/009-dotnet-custom-LLM) for using with LLamaSharp.

Of course, I have been considering doing this recently.
