### ISSUE TITLE
Flakey CI

### ISSUE THREAD

**Issue by martindevans** [SciSharp/LLamaSharp#220]
CI is quite unreliable, often failing with errors like this:

>  Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
/home/runner/work/LLamaSharp/LLamaSharp/LLama.Unittest/bin/Release/net6.0/LLama.Unittest.dll
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.5.0.1+5ebf84cd75 (64-bit .NET 6.0.24)
[xUnit.net 00:00:00.22]   Discovering: LLama.Unittest
[xUnit.net 00:00:00.37]   Discovered:  LLama.Unittest
[xUnit.net 00:00:00.38]   Starting:    LLama.Unittest
  Passed LLama.Unittest.IEnumerableExtensionsTests.TakeLastEmpty [11 ms]
  Passed LLama.Unittest.IEnumerableExtensionsTests.TakeLastAll [2 ms]
  Passed LLama.Unittest.IEnumerableExtensionsTests.TakeLast [< 1 ms]
  Passed LLama.Unittest.EncodingExtensionsTests.GetCharsChineseString [9 ms]
  Passed LLama.Unittest.EncodingExtensionsTests.GetCharCountChineseString [< 1 ms]
  Passed LLama.Unittest.EncodingExtensionsTests.GetCharCountString [< 1 ms]
  Passed LLama.Unittest.EncodingExtensionsTests.GetCharsString [< 1 ms]
  Passed LLama.Unittest.EncodingExtensionsTests.GetCharCountEmptyString [< 1 ms]
  Passed LLama.Unittest.EncodingExtensionsTests.GetCharsEmptyString [< 1 ms]
[xUnit.net 00:00:00.84]     LLama.Unittest.BeamTests.BasicBeam [SKIP]
[xUnit.net 00:00:00.85]       Very very slow in CI
The active test run was aborted. Reason: Test host process crashed
> 
> Test Run Aborted.
> Total tests: Unknown
>      Passed: 9
>  Total time: 6.2505 Seconds
>   LLamaSharp.SemanticKernel -> /home/runner/work/LLamaSharp/LLamaSharp/LLama.SemanticKernel/bin/Release/net6.0> /LLamaSharp.SemanticKernel.dll
> Error: Process completed with exit code 1.

Rerunning the it will often succeed in another run.

**Comment by martindevans** [comment]
I've tried to debug this, but no luck so far. There are detailed logs uploaded as artifacts from each CI run now, but they don't seem to contain anything relevant.

**Comment by AsakusaRinne** [comment]
Yes I met the same problem before, which seems to only happen in linux ci. I found [a similar discussion](https://github.com/xunit/xunit/discussions/2348) in `xunit` repo. It mentioned everything goes well with netcore 3.1 but crash in linux container with net5. I wonder if downgrading the sdk version of unittest to 3.1 or upgrading it to net7 will solve it (if lucky maybe it's solved in higher version).

**Comment by martindevans** [comment]
Based on that I've updated the CI to use dotnet 7.0 only in this PR: https://github.com/SciSharp/LLamaSharp/pull/222

**Comment by martindevans** [comment]
Maybe this is due to #225 - if it's much slower than before something could be timing out? Or it could be consuming a little more memory too.
