### ISSUE TITLE
v0.6.0 has hardcoded default seed of 1686349486

### ISSUE THREAD

**Issue by lexxsoft** [SciSharp/LLamaSharp#221]
I have noticed that my responses are not random anymore with latest package version.

The behavior has been changed, instead of `int` `-1` which previously meant random, now it is `uint` with hard-coded `1686349486` as can be seen at https://github.com/SciSharp/LLamaSharp/blob/b72b2535495ae7fd7b8e64aea1cb572df77750e2/LLama/Common/ModelParams.cs#L31

**Comment by AsakusaRinne** [comment]
Thank you for reporting us it. Maybe it's from a previous PR because of debugging in local environment. @martindevans Could you please take a look of this? Maybe we should add a patch version to fix it.

**Comment by martindevans** [comment]
I'll open up a PR to fix that right away!
