### ISSUE TITLE
osx-arm64 platform

### ISSUE THREAD

**Issue by tonual** [SciSharp/LLamaSharp#224]
First thing first thank you for the project and effort enabling llama model inference with .NET!

I use Mac M2 and was trying various combinations from the compatibility table (llamasharp-backend-model) with the basic console example.
Not sure if this is the arm64 issue alone but I'am always getting same error about missing assembly (no matter which version I use)

> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'LLamaSharp, Version=0.5.0.0, >Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

>File name: 'LLamaSharp, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null'
>   at Program.<Main>$(String[] args)
>   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>   at Program.<Main>$(String[] args)
>   at Program.<Main>(String[] args)

**.csproj**

```
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>osx-arm64</Platforms>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LLamaSharp" Version="0.5.1" />
    <PackageReference Include="LLamaSharp.Backend.Cpu" Version="0.5.1" />
  </ItemGroup>

```

**Comment by SignalRT** [comment]
It works without problems on Mac M2. Can you try to execute the test or examples in the Master or LLamaSharp?

**Comment by philippjbauer** [comment]
@tonual Try the following csrpoj file contents:

```csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LLamaSharp" Version="0.7.0" />
    <PackageReference Include="LLamaSharp.Backend.MacMetal" Version="0.7.0" />
  </ItemGroup>

  <Target Name="CopyNativeLibs" AfterTargets="Build" Condition="$([MSBuild]::IsOsPlatform('OSX'))">
    <Copy SourceFiles="$(TargetDir)/runtimes/osx-x64/native/ggml-metal.metal" DestinationFolder="$(TargetDir)" />
    <Copy SourceFiles="$(TargetDir)/runtimes/osx-x64/native/libllama.dylib" DestinationFolder="$(TargetDir)" />
  </Target>
</Project>
```

I still have the issue that the native libraries are not found because they don't live in their respective `runtimes/osx-arm64/native` directory and missing entry in the `YourProjectName.deps.json` file in the build target folder:

```json
[...]
"LLamaSharp.Backend.MacMetal/0.7.0": {
    "runtimeTargets": {
        "runtimes/osx-x64/native/ggml-metal.metal": {
            "rid": "osx-x64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
        },
        "runtimes/osx-x64/native/libllama.dylib": {
            "rid": "osx-x64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
        },
        // Missing information:
        "runtimes/osx-arm64/native/ggml-metal.metal": {
            "rid": "osx-arm64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
        },
        "runtimes/osx-arm64/native/libllama.dylib": {
            "rid": "osx-arm64",
            "assetType": "native",
            "fileVersion": "0.0.0.0"
        }
    }
}
[...]
```

@SignalRT this is something that needs to be adjusted in the build pipeline as far as I can tell. While the library is a universal one, .NET seems to not pick up on the files correctly for some reason.

**Comment by SignalRT** [comment]
@philippjbauer The master is working fine in my test. The nugget packages are clearly wrong, they not contains the native binaries. I'm reviewing it.

**Comment by martindevans** [comment]
Did something go wrong with the 0.7.0 release?

**Comment by SignalRT** [comment]
@martindevans  I'm not using the nuget packages, so I miss this..., reviewing the packages, this is the content of the CPU package:

![image](https://github.com/SciSharp/LLamaSharp/assets/16475613/5d34c084-aa42-41a3-8fa1-cb796f6a35ce)

But LlamaSharpBacked.props do not seems to copy the files (except on Windows) to the output directory:


```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <!--
  NuGet packages.config doesn't support native assemblies automatically,
  so copy the native assemblies to the output directory.
  -->
  <ItemGroup Condition="Exists('packages.config') OR
                        Exists('$(MSBuildProjectName).packages.config') OR
                        Exists('packages.$(MSBuildProjectName).config')">
    <Content Include="$(MSBuildThisFileDirectory)\..\..\runtimes\win-x64\native\*.dll"
             Condition="'$(PlatformTarget)' == 'x64'">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
      <Link>%(Filename)%(Extension)</Link>
    </Content>
    <Content Include="$(MSBuildThisFileDirectory)\..\..\runtimes\win-x86\native\*.dll"
             Condition="'$(PlatformTarget)' == 'x86'">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
      <Link>%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>

</Project>
```

It contains also the copy of x86 when there is no x86 binaries in the nuget package.

If I understand this right we should change LlamaSharpBacked.props to add all the options to copy files in the different platforms.

**Comment by philippjbauer** [comment]
I'm not sure if this a way for you to go at all since I'm admittedly unfamiliar with your build pipeline and all. After struggling with packaging native libraries for our project I was successful with using a nuspec file like this to package our project correctly for nuget:

https://github.com/tryphotino/photino.Native/blob/master/Photino.Native/Photino.Native.nuspec

**Comment by AsakusaRinne** [comment]
I'm very sorry for this mistake. It's a file copied from another project of mine and I only tested with windows... (linux device is not available to me recently). I'm not sure if that's the key to this issue but only coping win-x64 files is absolutely not correct. I've made a PR #238 

@philippjbauer @tonual Could you please help to test [this backend package](https://public-1306037490.cos.ap-beijing.myqcloud.com/LLamaSharp.Backend.Cpu.0.7.1.nupkg?q-sign-algorithm=sha1&q-ak=AKIDQxAyfxZucgt499CovHJVRBU-neUU3ZjvpeejNd2oEIQyBUrYg_pIUJZQ9PVsLr94&q-sign-time=1699025523;1699029123&q-key-time=1699025523;1699029123&q-header-list=host&q-url-param-list=&q-signature=a9d6ebbae232943e8dc05d65ca08583d12e48f86&x-cos-security-token=Dsi5V10soCY6Ipscd1VTmZP16nRs0P2a006ace9ec616b48cf5a6e52c0ee5b86exptAWq8WO8jDzwmkqhiNRim2W7l5M2uUiZ8YrjwxHj8sdAL9-kOq6dL1bB04_BqiRcaz6AimjPZPs7aWistEbF1r9U3Z-fHNwzAzz0HV_9d1h6NE9HTXrBDB9yH8nq8gpo7V6GD1irh6wkhWRPDmIFuWY0i8VjWrB5KHCEyDrsshhU4TBpjHzk0tIXTuP3Oo)? It will help us to see if that could resolve this problem. Many thanks!

**Comment by philippjbauer** [comment]
@AsakusaRinne Sure I can try that!

For my understanding, are the libraries in the backend packages for MacMetal and CPU equivalent? I expected the CPU package would only include the llama.cpp libraries compiled without metal (explicitly disabled in recent versions of llama.cpp).

There was a bit of delay between my edits to my previous message and your response. The nuspec equivalent for my last edit in the MacMetal backend would be:

```
  <files>
    <file src="LLamaSharpBackend.props" target="build/netstandard2.0/LLamaSharp.Backend.MacMetal.props" />
    <file src="runtimes/ggml-metal.metal" target="runtimes\osx-x64\native\ggml-metal.metal" />
    <file src="runtimes/libllama.dylib" target="runtimes\osx-x64\native\libllama.dylib" />

Add these entries (since it's the universal package):
    <file src="runtimes/ggml-metal.metal" target="runtimes\osx-arm64\native\ggml-metal.metal" />
    <file src="runtimes/libllama.dylib" target="runtimes\osx-arm64\native\libllama.dylib" />

    <file src="icon512.png" target="icon512.png" />
  </files>
```

**Comment by AsakusaRinne** [comment]
@philippjbauer Thank you very much for your suggestions! I've made the changes you mentioned in #238. Now the link for backend package is [here](https://public-1306037490.cos.ap-beijing.myqcloud.com/LLamaSharp.Backend.Cpu.0.7.1.nupkg?q-sign-algorithm=sha1&q-ak=AKIDLiCJu72dtncsvVO7KlPryvq4htRI0wrLZMz1njHOSr4WTYuSmhm47va3Y8pEsPW3&q-sign-time=1699025850;1699029450&q-key-time=1699025850;1699029450&q-header-list=host&q-url-param-list=&q-signature=d4e97fa5762fc338414f4bbc18f925d6f6e8ac57&x-cos-security-token=Dsi5V10soCY6Ipscd1VTmZP16nRs0P2aff7f416184442119cde15f1333b99116xptAWq8WO8jDzwmkqhiNRhJr8AaaS-RH7O2RPLpQ_odR8JtfZb2LCFjCKPdByNRaBW6nqwSz-daM50q-QMy34i3SS5oYCBMLZA7u6RMD2VYh3lQOLs2AG4agBLXzEhrnKRJjgTQGGZr6QgyFQR0AqhPv2OsaBU3dVhNQeUoC_6cKO_Th6qEgE1vcu4kZ_o-8).

**Comment by philippjbauer** [comment]
@AsakusaRinne this works for me! :)

**Comment by AsakusaRinne** [comment]
@philippjbauer Thank you for your help! We'll include this fix in the next patch release (in 2 days I think). :)

**Comment by philippjbauer** [comment]
Perfect! I was hoping this issue gets fixed before my presentation at this year's Dev Intersection. Now I don't have to explain a workaround ;)

**Comment by philippjbauer** [comment]
@AsakusaRinne Can you advise me on my earlier question?

>For my understanding, are the libraries in the backend packages for MacMetal and CPU equivalent? I expected the CPU package would only include the llama.cpp libraries compiled without metal (explicitly disabled in recent versions of llama.cpp).

I want to get this right :)

**Comment by AsakusaRinne** [comment]
@philippjbauer Yes, for MAC there're no difference between these two packages now ([reference](https://github.com/SciSharp/LLamaSharp/pull/204#discussion_r1367882207)). We keep the `MacMetal` backend now because there may be some users still using it. Only in some early versions, the DLL in these two package are not the same.

**Comment by tonual** [comment]
> @tonual Try the following csrpoj file contents:
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk">
>   <PropertyGroup>
>     <OutputType>Exe</OutputType>
>     <TargetFramework>net7.0</TargetFramework>
>     <ImplicitUsings>enable</ImplicitUsings>
>     <Nullable>enable</Nullable>
>   </PropertyGroup>
> 
>   <ItemGroup>
>     <PackageReference Include="LLamaSharp" Version="0.7.0" />
>     <PackageReference Include="LLamaSharp.Backend.MacMetal" Version="0.7.0" />
>   </ItemGroup>
> 
>   <Target Name="CopyNativeLibs" AfterTargets="Build" Condition="$([MSBuild]::IsOsPlatform('OSX'))">
>     <Copy SourceFiles="$(TargetDir)/runtimes/osx-x64/native/ggml-metal.metal" DestinationFolder="$(TargetDir)" />
>     <Copy SourceFiles="$(TargetDir)/runtimes/osx-x64/native/libllama.dylib" DestinationFolder="$(TargetDir)" />
>   </Target>
> </Project>
> ```
> 
> I still have the issue that the native libraries are not found because they don't live in their respective `runtimes/osx-arm64/native` directory and missing entry in the `YourProjectName.deps.json` file in the build target folder:
> 
> ```json
> [...]
> "LLamaSharp.Backend.MacMetal/0.7.0": {
>     "runtimeTargets": {
>         "runtimes/osx-x64/native/ggml-metal.metal": {
>             "rid": "osx-x64",
>             "assetType": "native",
>             "fileVersion": "0.0.0.0"
>         },
>         "runtimes/osx-x64/native/libllama.dylib": {
>             "rid": "osx-x64",
>             "assetType": "native",
>             "fileVersion": "0.0.0.0"
>         },
>         // Missing information:
>         "runtimes/osx-arm64/native/ggml-metal.metal": {
>             "rid": "osx-arm64",
>             "assetType": "native",
>             "fileVersion": "0.0.0.0"
>         },
>         "runtimes/osx-arm64/native/libllama.dylib": {
>             "rid": "osx-arm64",
>             "assetType": "native",
>             "fileVersion": "0.0.0.0"
>         }
>     }
> }
> [...]
> ```
> 
> @SignalRT this is something that needs to be adjusted in the build pipeline as far as I can tell. While the library is a universal one, .NET seems to not pick up on the files correctly for some reason.

Thank you a lot, it works for me.

**Comment by tonual** [comment]
@AsakusaRinne thank you for the upcoming fix and I will test the new release ASAP, however I can't test the backend from the link you've provided because Access is Denied. For now I am using workaround from @philippjbauer.
