### ISSUE TITLE
System.Runtime.InteropServices.SEHException when calling LLama.Native.NativeApi.NativeApi()

### ISSUE THREAD

**Issue by hswlab** [SciSharp/LLamaSharp#228]
I'm trying to get the LLama.WEB project running in Visual studio, but without success. I did the following steps.
1. Checked out the latest master branch of LLamaSharp
2. Modified the model path in appsettings.json where the file is located. 
"ModelPath": "D:\\AiModels\\llama-2-7b-chat.Q4_0.gguf",
3. Installed the nuget package LLamaSharp.Backend.Cpu (v0.7.0) in the LLamaSharp project.
4. Started LLama.Web in Debugger mode.

I'm getting an error when the method llama_backend_init(false); is called in LLama.Native.NativeApi.NativeApi()
![image](https://github.com/SciSharp/LLamaSharp/assets/12501993/af1a0366-ed57-445f-a248-8b0de5e86bee)

The llama_empty_call(); call was successfull but I noticed, that during TryLoadLibrary(); the NativeLibrary.TryLoad(path, out var handle) call always failed. Is probably something wrong with the path configuration for the .dll files?

![image](https://github.com/SciSharp/LLamaSharp/assets/12501993/f3dcefcf-dd6b-47fd-b664-3ad99a9211b0)

**Comment by SignalRT** [comment]
Theoretically you should not need to install nuget packages running from master. Could you try to see if this works for you?

**Comment by AsakusaRinne** [comment]
Could you please provide some extra information, including CUDA version of your PC, Avx support of your cpu and the sorbet runtime version? 

Besides, could you find a libllama.dll in the output folder of the project?

**Comment by hswlab** [comment]
@SignalRT after removing the LLamaSharp.Backend.Cpu from the dependencies in LLamaSharp project the DllNotFoundException is called in llama_empty_call();
![image](https://github.com/SciSharp/LLamaSharp/assets/12501993/c0d2a3a7-445c-447a-b6e6-b64cec1e76f9)

@AsakusaRinne 
**CUDA:**
Graphics Card: GeForce GT 525M, NVIDIA-kompatibel / Adapter-RAM (2.147.483.648) Bytes
GPU Details: https://www.techpowerup.com/gpu-specs/geforce-gt-525m.c1490
The command "nvcc" can't be recognized on my PC. Probably it is "2.1", but I'm not sure.
This GPU is really old, so I think it is better using the CPU :)

**Avx support of my cpu**
Prozessor: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz, 2201 MHz, 4 Kern(e), 8 logische(r) Prozessor(en)
CPU Details: https://www.ubergizmo.com/products/lang/en_us/devices/intel-i7-2670qm

**sorbet runtime version**
I don't know exactly what a sorbet runtime version is. Probably I do not have something like that :)

By the way I was already successfull testing v0.6.0, but it was really slow. 
During the test with 0.6.0 I detached the LLamaSharp Projet from the Web Project and installed
LLamaSharp and LLamaSharp.Backend.Cpu from nuget package manager.

**Comment by hswlab** [comment]
@martindevans I see, thanks for your help :)

**Comment by AsakusaRinne** [comment]
> By the way I was already successfull testing v0.6.0, but it was really slow.

@hswlab The performance issue was solved in v0.7.0, please refer to #225

**Comment by hswlab** [comment]
Thank you very much. The 0.7.0 version is much faster than the previous version. I downloaded deps.zip and used the avx binary simply in that TryLoadLibryry() Method. Its not elegant, but it is doing its job for now :)

![image](https://github.com/SciSharp/LLamaSharp/assets/12501993/277709a0-0cfe-4677-ab82-7ccd95ee5bd9)

**Comment by martindevans** [comment]
Rather than modifying `TryLoadLibrary` it would probably be better to simply replace the `libllama.dll` in the project with your avx only `libllama.dll`.

Alternatively if you place your binary in a folder named `avx` it should be loaded by the existing logic before it falls back to the default (which is currently AVX2).

**Comment by hswlab** [comment]
@martindevans oh, you are right, there is already a call for avx/libllama.dll, much better solution, thank you :)
