### ISSUE TITLE
"load_index_from_storage" equivelant method in LLamaSharp?

### ISSUE THREAD

**Issue by sengiv** [SciSharp/LLamaSharp#229]
Trying to convert below Python code using llama_index to C# version using LLamaSharp.
Any help would be greatly appreciated, thanks 🙏

```python
      from llama_index import (
          StorageContext,
          load_index_from_storage
      )
      
    # Rebuild storage context 
    storage_context = StorageContext.from_defaults(persist_dir="data/storage/vedastro/")

    # Load index (heavy computation)
    index = load_index_from_storage(storage_context, index_id="vedastro_index")

    # Initialize query engine and retriever
    retriever = index.as_retriever()
    
    response_synthesizer = llama_index.response_synthesizers.get_response_synthesizer(
                                          response_mode="refine",
                                          text_qa_template=text_qa_template,
                                          refine_template=refine_template,
                                          service_context=llm_context_query__service_context,
                                          use_async=False,
                                          streaming=False,
                                          )

    query_engine = llama_index.query_engine.retriever_query_engine.RetrieverQueryEngine(
        retriever=retriever,
        response_synthesizer=response_synthesizer,
    )
    
   response = query_engine.query("How was your day sweetheart?")


```

**Comment by AsakusaRinne** [comment]
Hi, could you please provide some more contexts about the python code? I'd like to ask about what is supposed to do by this code.

**Comment by sengiv** [comment]
Quite simple, once you have the retriever, you can run queries on it.
There is already an embeddings vector index in file, we need to load it.
I've updated the code for a more complete example

**Comment by martindevans** [comment]
It looks like `load_index_from_storage` is part of [llama index](https://www.llamaindex.ai/), not part of llama.cpp? I don't know much about this area, but I think something like Semantic Kernel (which we have an integration with) provides things like that.

**Comment by sengiv** [comment]
Thanks for your reply 🙏
Do you have any sample code using Semantic Kernel that loads a vector index or something similar?

**Comment by martindevans** [comment]
I think that's what [this](https://github.com/SciSharp/LLamaSharp/blob/master/LLama.Examples/NewVersion/SemanticKernelMemory.cs) demonstrates?

**Comment by sengiv** [comment]
@martindevans Thank for the quick reply.
so in this case `modelPath` will be path to the vector index right? 
I saw this code before posting this issue, but was not sure since it said `modelPath` and not vector path, will test the code and see how..
```python
Console.Write("Please input your model path: ");
            var modelPath = Console.ReadLine();

            var seed = 1337u;
            // Load weights into memory
            var parameters = new ModelParams(modelPath)
            {
                Seed = seed,
                EmbeddingMode = true
            };

            using var model = LLamaWeights.LoadFromFile(parameters);
            var embedding = new LLamaEmbedder(model, parameters);
```

**Comment by martindevans** [comment]
ModelPath would be the path to the LLM (i.e. a gguf file) which is used to generate embedding vectors.

**Comment by martindevans** [comment]
I'll close this one since it seems like your question has been answered, but please feel free to re-open if you've still got questions :)
