### ISSUE TITLE
Made a simple example for Unity demonstrating the use of this library.

### ISSUE THREAD

**Issue by Xsanf** [SciSharp/LLamaSharp#23]
I created a thread just in case.
This is just a simple example, a very simple chat. But it will allow those who are interested to use this library in Unity.

I put a working Unity example at https://github.com/Xsanf/LLaMa_Unity.
Just install Unity 2021 or higher and create an empty 3D project.
Assets > Import package > Custom package "LLaMa_Unity.unitypackage". After installing it.
In Project Panel > Scene. Load SampleScene. Set the unsafe flag, and run the example.

**Comment by Xsanf** [comment]
It's hard to figure out what's not working for you. I made an example. There it was necessary that the example would work not only in the editor, put the weights in the Assets\StreamingAssets directory.
Need to use Unity 2021 and later. Earlier versions will not work.
Use LLaMa_Unity.unitypackage from my repository. Please note that there is a libllama-cuda12 backend, more than in the example from the original repository. What is in the original, under Unity only works with the CPU.
The example works fine for me and compiles under Windows 10 and NVIDIA 3080.
If necessary, I can archive the project itself if you have a setup problem. I'm just not sure if it's a landlord because there are file size limits. Well, or put not archived, but the model itself cannot be put into it.

**Comment by Xsanf** [comment]
I have added the project to https://github.com/Xsanf/LLaMa_Unity/
He must work. I took it from the archive and ran it. If something doesn't work, it could be a DLL mismatch with your version of CUDA.

**Comment by BruceKristelijn** [comment]
Hi there, thanks for responding. I just now managed to get it working by replacing the libllama.dll you provided in the llamasharp [CPU nupkg](https://www.nuget.org/packages/LLamaSharp.Backend.Cpu).

**Comment by Xsanf** [comment]
If your GPU is not working, try different versions of the backend, it works fine for me with the GPU. As I understand it, if your GPU does not work, then you can try to compile the original backend for your CUDA. Here it is better to ask a question to the author of this repository, since he compiled the original https://github.com/ggerganov/llama.cpp into a DLL. But as I understand it, everything that supports lamacpp should be supported.

**Comment by Sanokei** [comment]
I tried this, but it unfortunately crashes unity (2021.3.27f1) without explanation. I experienced this same sort of crash when trying to using LLamaSharp through a NuGet Package Getter for Unity. I am not sure why the issue persists.

A user in the SciSharp discord found a work around by running LLama seperately on a webserver and then using unity websockets to connect to it. 

It feels like cheating in a way, and I continue to find a way to run it natively.
(I have also tried GPT4All's C# binding to no aval)

**Comment by BruceKristelijn** [comment]
> I tried this, but it unfortunately crashes unity (2021.3.27f1) without explanation. I experienced this same sort of crash when trying to using LLamaSharp through a NuGet Package Getter for Unity. I am not sure why the issue persists.
> 
> A user in the SciSharp discord found a work around by running LLama seperately on a webserver and then using unity websockets to connect to it.
> 
> It feels like cheating in a way, and I continue to find a way to run it natively. (I have also tried GPT4All's C# binding to no aval)
> 
> Edit:
> 
> * I am using .NET 4.5 not the standard 2.1
> * Tried building the project instead of playing it in editor, still crashes.

With the new 4.0 version I am also experiencing crashes and annoying RAM usage. I am thinking of creating an additional .net based webserver and spin that up at the start of the player.

**Comment by Xsanf** [comment]
Did you use a package or a project?
There is some difference there. It all works for me. Unity crashes only after restarting the project from under the editor. This is due to the fact that Unity is not able to unload dll from memory. I tried to unload it myself when the application is finished, but this does not always help.

**Comment by martindevans** [comment]
I'll close this issue since it's quite old now (and isn't tracking any bugs, as far as I can tell?)

Right now Unity isn't a platform that we "officially" support, but I know some people have successfully been using LLamaSharp within Unity.
