### ISSUE TITLE
Wrong Link to LLaMA2-7B Model in the readme

### ISSUE THREAD

**Issue by hswlab** [SciSharp/LLamaSharp#250]
I noticed, that there is the same Link used for both models in the readme. I think, it should be "https://huggingface.co/TheBloke/llama-2-7B-Guanaco-QLoRA-GGUF" for LLaMA2-7B

![image](https://github.com/SciSharp/LLamaSharp/assets/12501993/d5f387db-9cfc-42f4-a834-586792d6ac95)

By the way, what tool can be used to generate such gif animations as shown in the console demo? :)
https://github.com/SciSharp/LLamaSharp/blob/master/Assets/console_demo.gif

**Comment by AsakusaRinne** [comment]
Hi thank you for reporting us that! Would you mind open a PR to revise it? I've already closed down my computer and am going to bed :)

> By the way, what tool can be used to generate such gif animations as shown in the console demo? :)

What I used is ScreenToGif, which is a good open-source software. In fact the demo gif is quite old, if you have a better gif for showing the usage of LLamaSharp, welcome to PR it!

**Comment by hswlab** [comment]
You always get responses so quickly here, which is a completely new experience for me on GitHub^^'. Thank you very much. The Link has been updated.
