### ISSUE TITLE
WInform

### ISSUE THREAD

**Issue by betolley** [SciSharp/LLamaSharp#262]
Examples works perfect for me as a console app.
I created a winform and when I run I can't get the text field from the session.chatasync.

await foreach (var text in session.ChatAsync(prompt, new InferenceParams() { Temperature = 0.6f, AntiPrompts = new List<string> { "User:" } }))
{
    Console.Write(text);
    txtResponse.Text += text;
}

If I change the app type to console the information is shows and the console works.  I can put in a prompt and it does the correct answer.  But the txtResponse.Text field doesn't get updated but the console.write code works in the console app.

Any suggestions?

**Comment by saddam213** [comment]
Most likey because the LLamaSharp thread is not the UI thread

Try invoking the call back to the UI thread

Sorry my WinForms is rusty, but should be somthing like:
```
txtResponse.Invoke((MethodInvoker)delegate {
    // UI thread
    txtResponse.Text = newText;
});

```

**Comment by betolley** [comment]
That worked perfect.  Only one more question.  I asked what is the largest planet.  It answered and asked what is the smallest, what is the brightest, what is the darkest, what is the oldest.  Why did it not just answer my question and stop?

**Comment by saddam213** [comment]
This can depend on many thisngs, from the Model used, the Prompt, the Executor or even the AntiPrompt

Maybe make sure you are using the Interactive or Instruct executors not Stateless, but Im just guessing as I dont know your setup

**Comment by betolley** [comment]
Is anywhere I can read about the paramaters that affect things?  I see Temperature = 0.9f, MaxTokens = 128 .  What do these mean? Also are there others?

**Comment by martindevans** [comment]
This might be a good article to get you started: https://txt.cohere.com/llm-parameters-best-outputs-language-ai/
