### ISSUE TITLE
Not generating emojis correctly

### ISSUE THREAD

**Issue by AshD** [SciSharp/LLamaSharp#265]
Prompt: Write a Christmas message with emojis

Using the InstructExecutor.InferAsync() with the Mistral Instruct 7B model

Output: ������🎉Merry Christmas!���🏻���

Looks like the output is not getting tokenized correctly.

Thanks,
Ash

**Comment by martindevans** [comment]
This is a known issue, and is actually a surprisingly common issue across tokenizers in many projects! For example try [this tool](https://huggingface.co/spaces/Xenova/the-tokenizer-playground) in text mode and paste in some emoji. It's caused when one single _character_ is represented by multiple _tokens_.

This has been fixed in the `StatelessDecoder` by using the [`StreamingTokenDecoder`](https://github.com/SciSharp/LLamaSharp/blob/master/LLama/StreamingTokenDecoder.cs). That same fix will need to be applied to the other executors at some point.

**Comment by AshD** [comment]
Thanks Martin. 

Quick question - Would this cause an issue with Chinese and Japanese characters too?

Thanks,
Ash

**Comment by martindevans** [comment]
> Would this cause an issue with Chinese and Japanese characters too?

Yes! In fact the issue report that got me working on this issue was from someone using Korean, but there were other related issues from people using Cyrillic and Chinese characters (and I'd spotted it myself in English, but with emoji).

It's not every character in those languages, just ones which the tokenizer cannot represent in a single token (which seems to be fairly rare).

**Comment by AshD** [comment]
Thanks Martin.
I tried the StatelessExecutor. 
It did give me correct emojis but then continued to output nonsense text. Pasting a small snippet below.

 🎁🎅🎈 Merry Christmas! 💙🎊industriëšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšćîšìîšćîšìîšćîšćìšćîššìšćîshć****š️šćîšćìšćîshccššćîshć~\šćìšćîshćìšćîshćìšćîshćìšćîshćìšćîshćìšćîshćìšćîshćìšćîshćìšćîshćššćîshćìšćîshć~\ishšćîshćìšćîshćìšćîshćìšćîshćìšćîshćìšćîshćìšćîshćššćîshćìšćîshćìšćîshćìšćîshćìšćîshćššćîshćìšćîshćîshćîshć Industîshć îshîshćindustîshćİshš️šīshćîshćìšćîshćîshćîshćîshćîshćîshćîshćîshćîshćîshćîshćîshćîshćîshćîshšishšćîshšš️ìšćîshćîshćîshćîshćîshćîshšìšćîshšìšćîshćîshšìšćîshšìšćîshšìšćîshšìšćîshšìš️šššīshšìšćîshšš️ìšćîshšishšćîshšìšćîshšš️ìššìšćîshšìšćîshšìšćîshšìšćîshšīshšš️ìššš️ìšîshšıshšìš️6îshšìšćîshšìšćîshšìšćîshšìš️shîshćîshšìšćîshšīshšishšćîshšìšćîshšıshšìš-----------------š--------------------îshš---------------------,6š--------------------îshš----------------îshć Industîshš️5š--------------------îshšīshš

**Comment by martindevans** [comment]
What did you have set as your antiprompts?

**Comment by AshD** [comment]
List<string> { "<END>", "User:", ">" }

**Comment by martindevans** [comment]
From the antiprompts it looks like it's "correct" that it never stopped - it never generated any of the antiprompts. Could you try _exactly_ the same model and prompt in the main llama.cpp project to see if it produces the same output? It may just be that the model is getting confused by the emoji and gets stuck outputting nonsense.

**Comment by hswlab** [comment]
I have just tried the current version of the Master Branch with emoji in the text, unfortunately they still seem to be displayed incorrectly. 

![image](https://github.com/SciSharp/LLamaSharp/assets/12501993/758c61c7-eb37-41fe-bbe9-26cd8e24dd61)

Do I need to activate the StreamingTokenDecoder feature somehow? 
I has used the avx2 binaries for testing, which I downloaded here:
https://github.com/SciSharp/LLamaSharp/actions/runs/6762323560

**Comment by martindevans** [comment]
Was this using the `StatelessExecutor`? The `StreamingTokenDecoder` fixes the problem, but it's only being used in that one executor right now. Someone is going to have to modify the other executors to use it.

**Comment by hswlab** [comment]
@martindevans Do you mean the Inference Type "Stateless"?
This seem to work with emoji, but it is writing some strange text :D
![image](https://github.com/SciSharp/LLamaSharp/assets/12501993/b816ee87-e235-4009-bd01-48ab06cd5660)

**Comment by hswlab** [comment]
Oh, I think this problem is caused by a different model. Previously I tested with vicuna-7b-v1.5.Q3_K_M.gguf which was caused this strange behaviour in the text output. but now I tried llama-2-7b-chat.Q5_K_M.gguf, which gives me a much better result :)

![image](https://github.com/SciSharp/LLamaSharp/assets/12501993/cf11401d-b11f-430e-b0ef-401f6f3a171a)

**Comment by martindevans** [comment]
That still looks like the model is running on without stopping. What are the antiprompts set to?

**Comment by hswlab** [comment]
The Antiprompt is set to default "User:"

**Comment by martindevans** [comment]
Ah I guess we're not looking at the raw text here, it's presumably stripping out the antiprompt so we can't see it.

**Comment by saddam213** [comment]
the web example does a bit of extra filtering using `ITextStreamTransform`, so could be worth checking against vanilla LLamaSharp to confirm, its possible the web is causing stateless to go awol

**Comment by AsakusaRinne** [comment]
Shall we take this issue as completed?

**Comment by AshD** [comment]
I just tested this with the latest master branch and it works :-)

Closing ...
