### ISSUE TITLE
TODO: update the documentation

### ISSUE THREAD

**Issue by AsakusaRinne** [SciSharp/LLamaSharp#267]
The documentation has been outdated after v0.5.1. I'll update it after the next release. And I'll appreciate for any help about it.

**Comment by vikramvee** [comment]
@AsakusaRinne can I help here?

**Comment by martindevans** [comment]
@vikramvee help with the documentation would be **very much** appreciated!

A few ideas for things that could be done:
 - Add a new version (at the moment there are versioned docs for 0.4 and 0.5)
 - Regenerate automatically generated docs
 - Check that scripts in [Examples](https://github.com/SciSharp/LLamaSharp/tree/master/docs/Examples) all work, update broken ones
 - Add new examples based on the examples [in the code](https://github.com/SciSharp/LLamaSharp/tree/master/LLama.Examples/Examples).
 - Check for broken links (e.g. https://github.com/SciSharp/LLamaSharp/issues/467)
 - General update of [getting started](https://scisharp.github.io/LLamaSharp/0.5/GetStarted/) (copy versions table from readme, remove old models, add some new ones etc).

**Comment by vikramvee** [comment]
I am on that, will understand the project. And Keep updating you with the progress.

**Comment by AsakusaRinne** [comment]
The docs have been updated since v0.11.1. If you have any idea about how to improve it, please feel free to comment here or open a new issue. Thank you! @vikramvee
