### ISSUE TITLE
Linux cuda crash

### ISSUE THREAD

**Issue by ChengYen-Tang** [SciSharp/LLamaSharp#270]
I'm getting a crash using LLamaSharp.Backend.Cuda11
This problem occurs in 0.6.0 and 0.7.0, and is normal in 0.5.1
![image](https://github.com/SciSharp/LLamaSharp/assets/32535494/aa01f453-2bc8-4ecf-91ae-cb2eba55117c)

Env:
Ubuntu 22.04
![image](https://github.com/SciSharp/LLamaSharp/assets/32535494/d7af4df3-da69-49fe-8eab-49854b287bff)

**Comment by martindevans** [comment]
We have a new set of binaries ready to release in the next version (very soon). Could you try pulling the master branch and testing if it fixes this issue?

**Comment by ChengYen-Tang** [comment]
Same error

**Comment by martindevans** [comment]
What CPU and GPU are you using?

**Comment by ChengYen-Tang** [comment]
CPU: I7-8700
GPU: Titan RTX 24G

**Comment by AsakusaRinne** [comment]
It's quite weird because the only difference on compilation of native library since v0.6.0 is avx. 

We've published v0.8.0 just now, with a fix for cuda library (but not sure if it's helpful for this issue) and the cuda feature detection in #275. Could you please have a try with it?

If it still doesn't work, you could add `NativeLibraryConfig.WithLibrary({Your_DLL_PATH})` at the very beginning of your code, to load a cuda library compiled yourself. That could be a temporary fix.

**Comment by ChengYen-Tang** [comment]
Oh, it’s normal
Another question, how should I stop printing logs?

**Comment by AsakusaRinne** [comment]
> Oh, it’s normal

Is the v0.8.0 normal or your self-compiled library normal?

> Another question, how should I stop printing logs?

Stopping logs from llama.cpp is an another issue. Currently you could try to redirect the outputs to other where.

**Comment by AsakusaRinne** [comment]
Update: [this comment](https://github.com/SciSharp/LLamaSharp/issues/33#issuecomment-1714736219) will allow you to capture the outputs from native library and output them anywhere else.

**Comment by ChengYen-Tang** [comment]
> > Oh, it’s normal
> 
> Is the v0.8.0 normal or your self-compiled library normal?
> 
> > Another question, how should I stop printing logs?
> 
> Stopping logs from llama.cpp is an another issue. Currently you could try to redirect the outputs to other where.

v0.8.0

> Update: [this comment](https://github.com/SciSharp/LLamaSharp/issues/33#issuecomment-1714736219) will allow you to capture the outputs from native library and output them anywhere else.

Thank you.
