### ISSUE TITLE
Lora

### ISSUE THREAD

**Issue by betolley** [SciSharp/LLamaSharp#271]
I have LLamaSharp working with my c# Winform, thanks everyone for helping.  When I use [oobabooga](https://github.com/oobabooga/text-generation-webui) I have created a Lora.  Is it possible to load that with LLamaSharp?

**Comment by martindevans** [comment]
You should be able to add it to the `LoraAdapters` in the parameters when you load the model. It will be applied then.

**Comment by martindevans** [comment]
(Assuming a Lora created with oobabooga is compatible with llama.cpp of course).

**Comment by pugafran** [comment]
Can we do this with LlamaSharp llike in llama.cpp? (Use multiple lora adapters) 
If it's not implemented I would like to help, it is something I could really use for my project.
![image](https://github.com/SciSharp/LLamaSharp/assets/67395721/4764bf33-5865-4fb0-9fd0-796b940aa5f0)
