### ISSUE TITLE
LLamaSharp.SemanticKernel  Abnormal conversation

### ISSUE THREAD

**Issue by ynanech** [SciSharp/LLamaSharp#273]
Role conversion may fail due to capitalization reasons

`var role = Enum.TryParse<global::LLama.Common.AuthorRole>(chat.Role.Label, out var _role) ? _role : global::LLama.Common.AuthorRole.Unknown;
`

Main problem: When I only send one message, it will result in multiple rounds of conversation, which I really don't understand here
![QQ图片20231110114447](https://github.com/SciSharp/LLamaSharp/assets/20282409/dfc124f4-56bf-4389-9e30-bc8e62f43d8d)

project reference

`	<ItemGroup>
		<PackageReference Include="Microsoft.SemanticKernel" Version="1.0.0-beta5" />
		<PackageReference Include="LLamaSharp" Version="0.7.0" />
		<PackageReference Include="LLamaSharp.Backend.Cpu" Version="0.7.0" />
	</ItemGroup>
`

**Comment by AsakusaRinne** [comment]
Seems to be related with #186 , @xbotter any idea about it? It's most likely the problem of anti-prompt but I'm not sure how semantic-kernel makes it work.

**Comment by xbotter** [comment]
If necessary system instructions are missing in the dialogue, the output format may indeed exceed the expected results. It seems that some preliminary prompt engineering needs to be done. I will take a closer look.

**Comment by ynanech** [comment]
`Microsoft.SemanticKernel.Abstractions" Version="1.0.0-beta6` 
In the latest version of SemanticKernel, IChatStreamingResult and IChatResult changes have been made,LLamaSharp SemanticKernel library needs to be adjusted

**Comment by xbotter** [comment]
I noticed that the current LlamaSharpChatCompletion interface is using LlamaSharp's InteractiveExecutor model, which is not very suitable for stateless IChatCompletion. I will change it to stateless mode in the near future.

**Comment by AsakusaRinne** [comment]
This issue may have been solved by #341, could you please try it again with the master branch?

**Comment by martindevans** [comment]
Since it's been a while and this was probably fixed by #341 I'll close this issue now. If it's still a problem please don't hesitate to re-open it!
