### ISSUE TITLE
Is ChatAsync and InferAsync the same?

### ISSUE THREAD

**Issue by hswlab** [SciSharp/LLamaSharp#276]
In the LLama.Web implementation I noticed, that there is no ChatSession.ChatAsync used, as shown in the the LLamaSharp readme, but CreateExecutor.InferAsync.

Ist the ChatAsync Method the same as InferAsync?

This looks similar to me and both seems to initialize the Chat.
![image](https://github.com/SciSharp/LLamaSharp/assets/12501993/8058bde8-a9f6-4473-8247-ac304772bb83)
![image](https://github.com/SciSharp/LLamaSharp/assets/12501993/a09b853c-502f-4751-86be-95afe8ff5b16)

**Comment by AsakusaRinne** [comment]
They are almost the same when the executor is `LLamaInteractExecutor`. The `ChatSession` is a wrapper specially for chat mode. The only difference between `LLamaInteractExecutor.InferAsync` and `ChatSession.ChatAsync` is that `ChatAsync` may do some pre-process and post-process of the inference, which `InferAsync` only response the user's input.

**Comment by hswlab** [comment]
Ah, ok. Thank you :)
