### ISSUE TITLE
Comparing Performance of 70B Models with Different Versions (0.5.1 vs 0.7.0)

### ISSUE THREAD

**Issue by jinhuck** [SciSharp/LLamaSharp#279]
Xeon processor, 64GB of memory, and a P40 GPU with 24GB of VRAM.

================================================

For the smaller 7B model, the 0.7.0 version is a bit faster than 0.5.1

However, for the larger 70B model, the 0.7.0 version is noticeably slower compared to the 0.5.1 version. 

Tested two models: "fashiongpt-70b-v1.2.Q6_K.gguf" and "stellarbright.Q5_K_M.gguf."

===============================================================

0.5.1 version processes about 0.8 token per second (observed rate) 
0.7.0 version processes at a slower rate of around 0.3 tokens per second (observed rate) 

===============================================================

**Comment by AsakusaRinne** [comment]
Could you please try the latest v0.8.0 published just now? It fixed some performance problems.

**Comment by jinhuck** [comment]
Version 0.8.0 is nearly identical to version 0.5.1
++++++++++++++++++++++++++++++
fashiongpt-70b-v1.2.Q6_K.gguf
++++++++++++++++++++++++++++++
version 0.5.1 -  272 tokens / 346 secs = 0.786 tokens /sec
version 0.8.0 -  266 tokens / 346 secs = 0.768 tokens /sec
