### ISSUE TITLE
Not working with GPU backend cuda12.x

### ISSUE THREAD

**Issue by ChezzPlaya** [SciSharp/LLamaSharp#28]
I get an error on my machine when I try to run this on GPU. I've installed the Lllama.Backend.Cuda12 package. 

Running the nvidia-smi command gives me:

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 528.49       Driver Version: 528.49       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   47C    P8     9W /  60W |     93MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

and my C# code looks like:

```
using LLama;

string myModelPath = "models/wizard-vicuna-13B.ggmlv3.q4_1.bin";

var model = new LLamaModel(new LLamaParams(model: myModelPath, n_ctx: 1024, repeat_penalty: 1.2f, temp: 0.0001f, n_gpu_layers: 100));
var session = new ChatSession<LLamaModel>(model).WithAntiprompt(new[] { "User:" });
Console.Write("\nUser:");
while (true)
{
    Console.ForegroundColor = ConsoleColor.Green;
    var question = Console.ReadLine();
    Console.ForegroundColor = ConsoleColor.White;
    var outputs = session.Chat(question);
    foreach (var output in outputs)
    {
        Console.Write(output);
    }
}
```

And finally the exception:

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'LLama.Native.NativeApi' threw an exception.
 ---> LLama.Exceptions.RuntimeError: The native library cannot be found. It could be one of the following reasons:
1. No LLamaSharp backend was installed. Please search LLamaSharp.Backend and install one of them.
2. You are using a device with only CPU but installed cuda backend. Please install cpu backend instead.
3. The backend is not compatible with your system cuda environment. Please check and fix it. If the environment is expected not to be changed, then consider build llama.cpp from source or submit an iss
ue to LLamaSharp.
   at LLama.Native.NativeApi..cctor()
   --- End of inner exception stack trace ---
```

**Comment by AsakusaRinne** [comment]
Could you please provide the following information? It will help a lot for me to find the problem!

- Your operation system information and the cuda version you installed.
- Your dotnet runtime version.
- All the packages you installed.
- The files in your output directory, for example, `bin/Debug/netX.Y`, to see if the library file has been copied correctly.

**Comment by ChezzPlaya** [comment]
@AsakusaRinne 

OS: Windows 11 (64 bit)
.NET 7.0
Installed packages:
<img width="620" alt="image" src="https://github.com/SciSharp/LLamaSharp/assets/76159073/78bf9585-9c92-4866-a111-5f4987ef7a9a">
The folder: **Debug\net7.0\runtimes\win-x64\native** contains the libllama.dll

**Comment by ChezzPlaya** [comment]
sorry, my fault, the command nvcc --version gives me:

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

which is clearly not the v12.x that gives me the nvidia-smi command. That's confusing. 

Anyway, the v11 backend works fine.

**Comment by blackcement** [comment]
@AsakusaRinne , I have the same problem, can't figure out what I'm missing? Created a new project, the code is the same as the @ChezzPlaya .

`RuntimeError: The native library cannot be found. It could be one of the following reasons: 
1. No LLamaSharp backend was installed. Please search LLamaSharp.Backend and install one of them. 
2. You are using a device with only CPU but installed cuda backend. Please install cpu backend instead. 
3. The backend is not compatible with your system cuda environment. Please check and fix it. If the environment is expected not to be changed, then consider build llama.cpp from source or submit an issue to LLamaSharp.
`

OS: Windows 10 (64 bit) 19044.1288
.NET 7.0
CUDA\v11.7

![image](https://github.com/SciSharp/LLamaSharp/assets/61663301/ca582a90-3acc-415b-94b0-ab4bff734310)

![image](https://github.com/SciSharp/LLamaSharp/assets/61663301/792a7165-b583-4405-8e09-038e8a2e2e6c)

![image](https://github.com/SciSharp/LLamaSharp/assets/61663301/509f2df0-2985-4f23-be99-7e21a602055b)

![image](https://github.com/SciSharp/LLamaSharp/assets/61663301/148fa45d-e7b4-498c-b08e-e791f48cb591)

![image](https://github.com/SciSharp/LLamaSharp/assets/61663301/6a108aa3-1cc0-4343-943b-320f90787b4e)

**Comment by DavidixGT** [comment]
> @AsakusaRinne , I have the same problem, can't figure out what I'm missing? Created a new project, the code is the same as the @ChezzPlaya .
> 
> `RuntimeError: The native library cannot be found. It could be one of the following reasons:
> 
> 1. No LLamaSharp backend was installed. Please search LLamaSharp.Backend and install one of them.
> 2. You are using a device with only CPU but installed cuda backend. Please install cpu backend instead.
> 3. The backend is not compatible with your system cuda environment. Please check and fix it. If the environment is expected not to be changed, then consider build llama.cpp from source or submit an issue to LLamaSharp.
>    `
> 
> OS: Windows 10 (64 bit) 19044.1288 .NET 7.0 CUDA\v11.7
> 
> ![image](https://private-user-images.githubusercontent.com/61663301/255329158-ca582a90-3acc-415b-94b0-ab4bff734310.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MzU1MzcsIm5iZiI6MTcwMjczNTIzNywicGF0aCI6Ii82MTY2MzMwMS8yNTUzMjkxNTgtY2E1ODJhOTAtM2FjYy00MTViLTk0YjAtYWI0YmZmNzM0MzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDE0MDAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZWE3ZmVlOTM0ZTQ5N2Q3ODhiYjRkNWRmYTNjMDg0YTZjNDZlMjQ2YjBlNjY0ZmZiZWRmM2QzMDExNWJlOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.91UXVlwd7P-duUwaTUIr_Kg8ORn2bvGXda0iU20RxGo)
> 
> ![image](https://private-user-images.githubusercontent.com/61663301/255329398-792a7165-b583-4405-8e09-038e8a2e2e6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MzU1MzcsIm5iZiI6MTcwMjczNTIzNywicGF0aCI6Ii82MTY2MzMwMS8yNTUzMjkzOTgtNzkyYTcxNjUtYjU4My00NDA1LThlMDktMDM4ZThhMmUyZTZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDE0MDAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMmMwZjVkOTRhODBiMTU2NTM0M2JjNjk1ZjE1YTE2MWY1N2ZiMTljZmVjM2ZjYWNkMTcwODBhNTkyZDdjMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6WnRNzSJsQn1YPu-hgilukkWhZCBOGFI3jsuXM1_Z9M)
> 
> ![image](https://private-user-images.githubusercontent.com/61663301/255329741-509f2df0-2985-4f23-be99-7e21a602055b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MzU1MzcsIm5iZiI6MTcwMjczNTIzNywicGF0aCI6Ii82MTY2MzMwMS8yNTUzMjk3NDEtNTA5ZjJkZjAtMjk4NS00ZjIzLWJlOTktN2UyMWE2MDIwNTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDE0MDAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNDEyODZkNmM3Mjg4YWE4YmVmNmM2MDU1ZTY5YTk0ZDU4MDhkMWE1N2UxZTkzZGExMzRhOTM5ZWUxZjI2NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SQO74yG1nu4PXQCbl1RF--3jQ9-MGVRexRuq1d_4eJE)
> 
> ![image](https://private-user-images.githubusercontent.com/61663301/255329948-148fa45d-e7b4-498c-b08e-e791f48cb591.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MzU1MzcsIm5iZiI6MTcwMjczNTIzNywicGF0aCI6Ii82MTY2MzMwMS8yNTUzMjk5NDgtMTQ4ZmE0NWQtZTdiNC00OThjLWIwOGUtZTc5MWY0OGNiNTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDE0MDAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYmI4ZDE1MGU0MGJkODQyZGRhMGEwMjNmNDRkMjYyZTVjNWI3ZGQ0YjVmMjIxZGFmZjkzOWU5YjI3NWNiZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zzbsw2MgTmHuTe5lKsz9s0VHNmEmtUXTgZevxYRj8qQ)
> 
> ![image](https://private-user-images.githubusercontent.com/61663301/255329970-6a108aa3-1cc0-4343-943b-320f90787b4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MzU1MzcsIm5iZiI6MTcwMjczNTIzNywicGF0aCI6Ii82MTY2MzMwMS8yNTUzMjk5NzAtNmExMDhhYTMtMWNjMC00MzQzLTk0M2ItMzIwZjkwNzg3YjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDE0MDAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NmRmNWFhNGNkNzliYWYzMTJlOTgxNTk0ZDNiNWNmMGZhNjdlYTMzMTA3YzAwNGVjM2E0ZTE0OTZhN2M5ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LL0LBe0qP0I-dXlWPwoTtJj6--dLxnn7OP-d4KEY_AY)

попробуй установить куда12 и цпу бэкенд
