### ISSUE TITLE
License

### ISSUE THREAD

**Issue by secirugy** [SciSharp/LLamaSharp#3]
Just wondering about license; it says that it is MIT, which is great. But LLAMA itself is not for commercial use, so how the whole project is MIT (which allows commercial use?

**Comment by AsakusaRinne** [comment]
Hi, thank you for your reminder. To the best of my knowledge, "using LLaMa" could be separated into two parts, the model weights and the code to run model inference. The model weights, obviously, is not MIT. Neither is [Facebook official implementation](https://github.com/facebookresearch/llama). However, [llama.cpp](https://github.com/ggerganov/llama.cpp) is another opensource implementation which uses MIT. `LLamaSharp` is a .NET Binding of `llama.cpp` and provides extensions (for example, integration for ASP.NET core). Therefore we just keep the license the same with `llama.cpp`.

Besides, `llama.cpp` supports more than just LLaMa model, so does `LLamaSharp`. For example, [GPT4All](https://github.com/nomic-ai/gpt4all) is MIT, which makes it possible for the whole chain into commercial use.
