### ISSUE TITLE
Add an Agent like the LangChain does

### ISSUE THREAD

**Issue by ChezzPlaya** [SciSharp/LLamaSharp#30]
Would be great to see some extensible agent implementation for this repo.

**Comment by Oceania2018** [comment]
`LangChan` style like implementation will be done in our [BotSharp](https://github.com/SciSharp/BotSharp) project.

**Comment by ChezzPlaya** [comment]
@Oceania2018 Why will be this done within the BotSharp project? In my opinion the LangChain kind of Agent stuff shall not be a part of a Chatbot framework but rather an independent project, so itt can be used together with the LllamaSharp and/or BotSharp.
