### ISSUE TITLE
CUDA Error 12

### ISSUE THREAD

**Issue by ChezzPlaya** [SciSharp/LLamaSharp#31]
While using the InstructExecutor, I get this error:

`> CUDA error 12 at D:/development/llama/llama.cpp/ggml-cuda.cu:646: invalid pitch argument`

My C# code:

```
using LLama;
using LLama.Common;

string myModelPath = "model/wizardLM-7B.ggmlv3.q4_1.bin";

var model = new LLamaModel(new ModelParams(myModelPath));
var session = new InstructExecutor(model);

while (true)
{
    string question = File.ReadAllText("prompt.txt");
    var outputs = session.Infer(question, new InferenceParams
    {
        Temperature = 0.00001f,
        RepeatPenalty = 1.2f
    });
    foreach (var output in outputs)
    {
        Console.Write(output);
    }
}
```

**Comment by AsakusaRinne** [comment]
Hi, I guess it's because you were using a latest model (llama.cpp is under fast development and often has break changes). Could you please try it with the source code? Currently the master branch has followed up the master branch of llama.cpp except MAC support.

**Comment by Arlodotexe** [comment]
I'm on the latest prerelease (just got gguf support) and am getting this now. Always on the second message 🤔

**Comment by Arlodotexe** [comment]
@martindevans I loaded up the model you used to validate #122 and this error is always happening on the second message. Has happened with every model I've tried.

**Comment by martindevans** [comment]
That's odd, from a bit of searching that error seems to mean that the model is invalid (which can't be the case here). Does it happen with a pure CPU backend?

**Comment by Arlodotexe** [comment]
Seems it can be worked around by making a new instance of `InstructExecutor` every time.

**Comment by martindevans** [comment]
Could you show what code you are using before and after? If creating a new `InstructExecutor` works around the bug that sounds likely to be a LLamaSharp issue and not a llama.cpp issue!

**Comment by Arlodotexe** [comment]
> Could you show what code you are using before and after? If creating a new `InstructExecutor` works around the bug that sounds likely to be a LLamaSharp issue and not a llama.cpp issue!

The example in the OP should demonstrate the issue. Run as-is, it'll crash on the second message. Move the `session` inside the loop and it'll work every time.

**Comment by Arlodotexe** [comment]
Doesn't happen with CPU

**Comment by jihadkhawaja** [comment]
Having the same issue here with CUDA 12

**Comment by Arlodotexe** [comment]
Trying out `hermes-llongma-2-7b-8k.Q4_K_M.gguf`, I found that setting `ModelParams.ContextSize` to 8092 fixes the issue for both `InstructExecutor` and `InteractiveExecutor`.

Very odd, maybe it is an issue with llama.cpp 🤔

**Comment by AsakusaRinne** [comment]
Hi, could you please try it again with v0.7.0? I'll really appreciate that!
