### ISSUE TITLE
AIRequestSettings object can not be brute forced into a ChatRequestSettings object

### ISSUE THREAD

**Issue by futzy314** [SciSharp/LLamaSharp#313]
Hi, I'm trying to get a sample from SemanticKernel working with LlamaSharp, and its failing when the SemanticKernel plugin function specifies any settings.  I took a look at the code, and it's trying to brute force convert the AIRequestSettings object into a ChatRequestSettings object, which won't work.  There needs to be an actual conversion function instead.  I can take a stab at it if you like, I'd like to help out with the SemanticKernel integration.

**Comment by AsakusaRinne** [comment]
Hi, we'll appreciate it if you would like to help! Please feel free to ask me and @xbotter for help if there's any problem. Also, if you'd like to, you can join the discord channel to chat with us. :)

**Comment by xbotter** [comment]
Thank you for pointing out this issue, feel free to submit a PR to fix it.
