### ISSUE TITLE
Error CS1061

### ISSUE THREAD

**Issue by abduli123** [SciSharp/LLamaSharp#324]
Hi i was compiling the example Model Inference and Chat Session but i when i try it run it i found the error CS1061 in this line

while (prompt != "stop")
{
    foreach (var text in session.Chat(prompt, new InferenceParams() { Temperature = 0.6f, AntiPrompts = new List<string> { "User:" } }))
    {
        Console.Write(text);
    }
    prompt = Console.ReadLine();
}

also i already have intalled LLamaSharp and LLamaSharp.Backend.CPU this is how the code looks
![image](https://github.com/SciSharp/LLamaSharp/assets/24835728/433c1664-f8a8-4b96-b1b9-1dcec7c7bec4)

**Comment by martindevans** [comment]
`Chat` returns an `IAsyncEnumerable`, but you are not awaiting it anywhere.

Copying from [this example](https://github.com/SciSharp/LLamaSharp/blob/master/LLama.Examples/Examples/ChatSessionStripRoleName.cs#L33C21-L33C21) you need to do something like this:

```csharp
await foreach (var text in session.ChatAsync(prompt, new InferenceParams() { Temperature = 0.6f, AntiPrompts = new List<string> { "User:" } }))
// ^^ await!
{
    Console.Write(text);
}
```

**Comment by abduli123** [comment]
Alright thank you for the help.
