### ISSUE TITLE
Error when sending input to the model

### ISSUE THREAD

**Issue by Webslug** [SciSharp/LLamaSharp#328]
I am trying to make a text box and a richtext box to parse input and send it to the model but i keep getting this error when i send input to the model?  I am trying to use a GGUF model, i hope that's okay.  Any ideas what is wrong with my code? 

I am using .NET 8.0

System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'
ObjectDisposedException: Cannot access a disposed object.
Object name: 'Cannot use this `SafeLLamaContextHandle` - it has been disposed'.
![winform](https://github.com/SciSharp/LLamaSharp/assets/7551638/289e43cb-2e6d-4beb-a801-c733ff5b981a)

```
         static void Main()
        {
            ApplicationConfiguration.Initialize();
            LoadModel();
            Program.MainForm = new Form1();
            Application.Run(Program.MainForm);
        }
        
        //the function which triggers after enter is pressed
        public async static void ProcInput()
        {
           string prompt = MainForm.textBox1.Text;

            await foreach (var text in Program._session.ChatAsync(prompt, new InferenceParams() { Temperature = 0.6f, AntiPrompts = new List<string> { "User:" } }))
            { 
                Program.MainForm.richTextBox1.AppendText(text);
            }
        }

        public static void LoadModel()
        {
            string modelPath = "D:\\AI\\LMStudio\\models\\TheBloke\\zephyr-7B-beta-GGUF\\zephyr-7b-beta.Q4_K_S.gguf"; // change it to your own model path
            var parameters = new ModelParams(modelPath)
            {
                ContextSize = 1024,
                Seed = 1337,
                GpuLayerCount = 5
            };
            using var model = LLamaWeights.LoadFromFile(parameters);
            using var context = model.CreateContext(parameters);
            var prompt = "meow";
            var ex = new InteractiveExecutor(context);
            ChatSession session = new ChatSession(ex);
            Program._session = session;
            
        }
```   

```        internal unsafe object? InvokeDirectByRefWithFewArgs(object? obj, Span<object?> copyOfArgs, BindingFlags invokeAttr)
        {
            Debug.Assert(_argCount <= MaxStackAllocArgCount);

            if ((_strategy & InvokerStrategy.StrategyDetermined_RefArgs) == 0)
            {
                DetermineStrategy_RefArgs(ref _strategy, ref _invokeFunc_RefArgs, _method, backwardsCompat: true);
            }

            StackAllocatedByRefs byrefs = default;
#pragma warning disable CS8500
            IntPtr* pByRefFixedStorage = (IntPtr*)&byrefs;
#pragma warning restore CS8500

            for (int i = 0; i < _argCount; i++)
            {
#pragma warning disable CS8500
                *(ByReference*)(pByRefFixedStorage + i) =  (_invokerArgFlags[i] & InvokerArgFlags.IsValueType) != 0 ?
#pragma warning restore CS8500
                    ByReference.Create(ref copyOfArgs[i]!.GetRawData()) :
                    ByReference.Create(ref copyOfArgs[i]);
            }

            try
            {
                return _invokeFunc_RefArgs!(obj, pByRefFixedStorage);
            }
            catch (Exception e) when ((invokeAttr & BindingFlags.DoNotWrapExceptions) == 0)
            {
                throw new TargetInvocationException(e);
            }
        }
```

```
This exception was originally thrown at this call stack:
    LLama.Native.SafeLLamaContextHandle.ThrowIfDisposed()
    LLama.Native.SafeLLamaContextHandle.Tokenize(string, bool, bool, System.Text.Encoding)
    LLama.LLamaContext.Tokenize(string, bool, bool)
    LLama.InteractiveExecutor.PreprocessInputs(string, LLama.StatefulExecutorBase.InferStateArgs)
    LLama.StatefulExecutorBase.InferAsync(string, LLama.Abstractions.IInferenceParams, System.Threading.CancellationToken)
    LLama.ChatSession.ChatAsyncInternal(string, LLama.Abstractions.IInferenceParams, System.Threading.CancellationToken)
    LLama.ChatSession.ChatAsyncInternal(string, LLama.Abstractions.IInferenceParams, System.Threading.CancellationToken)
    LLama.ChatSession.ChatAsync(string, LLama.Abstractions.IInferenceParams, System.Threading.CancellationToken)
    LLama.ChatSession.ChatAsync(string, LLama.Abstractions.IInferenceParams, System.Threading.CancellationToken)
    llamsharp8.Program.ProcInput() in Program.cs
    ...
    [Call Stack Truncated]
```

**Comment by AsakusaRinne** [comment]
Please try it with dotnet 7.0 first since dotnet 8.0 may not be stable enough. TBH I'm not familiar with winform and WPF, the only part I feel suspicious is the following code:

```cs
using var model = LLamaWeights.LoadFromFile(parameters);
using var context = model.CreateContext(parameters);
```

I think the `using` should be removed since it may lead to an early disposing.

You can also refer to [LLama Stack](https://github.com/saddam213/LLamaStack), which contains examples of WPF with LLamaSharp.

**Comment by martindevans** [comment]
As AsakusaRinne pointed out your resource management isn't quite right.

`using var model = LLamaWeights.LoadFromFile(parameters);`

This is fine, it will unload the weights as soon as nothing is using them.

`using var context = model.CreateContext(parameters);`

This is the problem. As soon as you leave that scope (e.g. the method) the context is disposed (which frees all the memory it's using etc). The problem in this case is that as soon as you leave your `LoadModel()` method the context is destroyed. When you later try to use that context (e.g. in `ProcInput` when you call `ChatAsync`) it's already been disposed and you get that error.

You need to keep a reference to the context and dispose it once the conversation ends.

Rebuilding the executors to be easier to use (e.g. automatic management of this kind of thing) is a big task that's in progress at the moment.

**Comment by Webslug** [comment]
@AsakusaRinne  You're a legend, thank you very much. I removed using and it works fine now.

``
            var model = LLamaWeights.LoadFromFile(parameters);
            var context = model.CreateContext(parameters);
```

Is there a way to **unload** a model once it has been loaded by Llamasharp?  I am repeatedly testing different models and I it would be nice to switch to different models on the fly while the program is running.  I know there are numerous applications out there which do this already. 

I tried LlamaStack but I could not get the example WPF project to work due to an error with it, I'm awaiting feedback.  I still have dozens of questions.  

[martindevans](https://github.com/martindevans) When do you think the executors will be rebuilt?

**Comment by martindevans** [comment]
> Is there a way to unload a model once it has been loaded by Llamasharp?

If you dispose the `LLamaWeights` then they will be unloaded as soon as all of the contexts which are using those weights are disposed as well.

So you can do something like this:

```csharp
void YourSetupMethod()
{
    using var model = LLamaWeights.LoadFromFile(parameters);
    var context = model.CreateContext(parameters);
}

void UseTheContext()
{
    // You can use the context for as long as you like
}

void WhenYouAreDone()
{
    // When you're finished with this model
    context.Dispose();
}
```

**Comment by martindevans** [comment]
> When do you think the executors will be rebuilt?

No idea, it's incredibly complex. I would guess a month or two to get a new "low level" executor working (i.e. functional, but not very pleasant to use) and then we'll need to build abstractions around that to make it easier to use.

**Comment by martindevans** [comment]
It looks like the initial issue with the `ObjectDisposedException` exception has been resolved, so I'll close this issue now.
