### ISSUE TITLE
capturing the output

### ISSUE THREAD

**Issue by yakovw** [SciSharp/LLamaSharp#33]
Hello,
Thanks again for all the work you put in here.
The output that was written to the console when loading the model, is there a way to capture it in a windowed application?
I want to blog it, but I don't have direct access to it through C#

**Comment by yakovw** [comment]
Thank you very much, I tried all sorts of things too, but without success, maybe it's just not possible

**Comment by celsojr** [comment]
If you run a console app via `Process.Start()`, then you can read its output anywhere. Here's an example:

```c#
var proc = new Process 
{
    StartInfo = new ProcessStartInfo
    {
        FileName = "program.exe",
        Arguments = "command line arguments to your executable",
        UseShellExecute = false,
        RedirectStandardOutput = true,
        CreateNoWindow = true
    }
};
```

```c#
proc.Start();
while (!proc.StandardOutput.EndOfStream)
{
    string line = proc.StandardOutput.ReadLine();
    // do something with line
}
```

But of course it would be better to just consume some API endpoints like this:
http://localhost:8000/v1/chat/completions

Check out the `llama-cpp-python[server]`.

Refs.:

- https://stackoverflow.com/a/4291965/1812371
- https://github.com/abetlen/llama-cpp-python#web-server

**Comment by yakovw** [comment]
Of course I'm not going to run through a command line, it's ugly...
And it's not that important.
The rest of the solutions, well...
We will check
Thank you very much for checking for me

**Comment by ChezzPlaya** [comment]
I'd suggest to implement some sort on reactive extensions stuff, so one can simply subscribe to the output and capture/redirect it.

**Comment by yakovw** [comment]
The problem is that it comes from the C++ library and not from C#

**Comment by ChezzPlaya** [comment]
> The problem is that it comes from the C++ library and not from C#

https://github.com/Tyrrrz/CliWrap

**Comment by yakovw** [comment]
> > The problem is that it comes from the C++ library and not from C#
> 
> https://github.com/Tyrrrz/CliWrap

Very interesting, I will check it out

**Comment by celsojr** [comment]
> Of course I'm not going to run through a command line, it's ugly... And it's not that important. The rest of the solutions, well... We will check Thank you very much for checking for me

I don't think reading the `StandardOutput` of the `Process.Start()` is "ugly". It does exists for purpose. This is just a matter of opinion.

For example, I would not like having many external dependencies in simple programs/solutions or "not that important". But again, this is just my own opinion.

> https://github.com/Tyrrrz/CliWrap

@ChezzPlaya good one! I didn't know about it before. I think will give it a try later.

**Comment by martindevans** [comment]
You can use this to capture the logging output from llama.cpp:

```csharp
NativeApi.llama_log_set((level, message) =>
{
    // Do whatever you want!
});
```

Does that resolve this issue?

**Comment by martindevans** [comment]
I'll close this issue for now since I think it's resolved, but please feel free to re-open it if there's still a problem!
