### ISSUE TITLE
0.8.1: GGML_ASSERT: D:\a\LLamaSharp\LLamaSharp\llama.cpp:745: data

### ISSUE THREAD

**Issue by JohnGalt1717** [SciSharp/LLamaSharp#337]
I'm getting this error now on certain requests using several different models randomly. I do see this warning before: WARNING: failed to allocate 16000.00 MiB of pinned memory: out of memory

Which normally results in it falling back to CPU from CUDA but in these random cases it just blows up which even if in a try/catch results in termination of the application.

**Comment by AsakusaRinne** [comment]
Are you trying to offload layers to gpu as much as possible? Thus you want to catch the error if the current configuration is out-of-memory?

Please let me know if I misunderstand your condition. :)

**Comment by JohnGalt1717** [comment]
So I got a little more of an error. It appears it's llama.cpp code that is crashing, but instead of being handled, it takes down any process that LlamaSharp is hosted in even if there is a try/catch around it.

CUDA error 2 at D:\a\LLamaSharp\LLamaSharp\ggml-cuda.cu:6016: out of memory

In that error, it should have fallen back to CPU (which had tons of ram) but didn't instead it just crashed to the desktop.

**Comment by martindevans** [comment]
It looks like this is broadly the same issue as #343, with llama.cpp using assert to terminate the process instead of some kind of recoverable error handling (error return codes, exceptions etc)? If so I'll close this issue and we'll track it over in #343.

**Comment by JohnGalt1717** [comment]
I believe it is.

**Comment by iulix21** [comment]
I have thos error: GGML_ASSERT: /tmp/tmp25xydfjh/llama_cpp_python-0.2.53/vendor/llama.cpp/ggml-cuda.cu:8620: ptr == (void *) (g_cuda_pool_addr[device] + g_cuda_pool_used[device])
