### ISSUE TITLE
OpenBuddy models

### ISSUE THREAD

**Issue by yakovw** [SciSharp/LLamaSharp#34]
https://scisharp.github.io/LLamaSharp/0.4/GetStarted/
It is mentioned here that the OpenBuddy models are fine with the software
but...
In practice it doesn't work, it should work when the base of the software is updated, but until this update is done, it still doesn't work with these models
I mean the llama.cpp has been updated to work with these models
But it is not updated here anymore.

**Comment by AsakusaRinne** [comment]
Could you please have a try with the current master branch? I've updated the native libraries of windows and linux with corresponding changes in C#.

**Comment by yakovw** [comment]
I will check, thank you very much

**Comment by yakovw** [comment]
LLama.Exceptions.RuntimeError: 'Failed to load model W:\Models\llam\Uncensored\openbuddy-llama-ggml-7b-v4-q5_K.bin.enc.'
this is what i get

**Comment by yakovw** [comment]
Karen-The-Editor.ggmlv3.q5_K_M.bin
I have now tried it, and it does work nicely, thanks for the update
[Although what are the differences? I haven't found out yet]

**Comment by AsakusaRinne** [comment]
The difference is the native library file and some low-level APIs in C#. :)
