### ISSUE TITLE
v0.8.1 -- Unable to utilize CUDA in any way

### ISSUE THREAD

**Issue by Onkitova** [SciSharp/LLamaSharp#345]
Hello and thank you for the great project!

I am trying to utilize GPU (windows 11 + Nvidia 2060S with the most recent driver and CUDA 12.3) with [example console project](https://github.com/SciSharp/LLamaSharp/tree/master/LLama.Examples) from the repo. Unfortunately, despite 
`NativeLibraryConfig.Instance.WithCuda().WithLogs();`
it automatically loads just avx2 version:
![image](https://github.com/SciSharp/LLamaSharp/assets/119720012/7b4f99dc-c735-41d7-a374-ecc0dda51567)

If I am trying to manually adjust example project code with changing
`NativeLibraryConfig.Instance.WithCuda().WithLogs();`
to 
`NativeLibraryConfig.Instance.WithLibrary(@"C:\Users\Username\Desktop\LLamaSharp-master\LLamaSharp-master\LLama.Examples\bin\Debug\net6.0\runtimes\win-x64\native\cuda12\libllama.dll");`
I am getting an exception:

> System.TypeInitializationException: 'The type initializer for 'LLama.Native.NativeApi' threw an exception.'

> RuntimeError: Failed to load the native library [C:\Users\Username\Desktop\LLamaSharp-master\LLamaSharp-master\LLama.Examples\bin\Debug\net6.0\runtimes\win-x64\native\cuda12\libllama.dll] you specified.

Same goes for cuda11 version. Just for the sake of info: if I am trying to manually feed avx2 version of libllama.dll with exact NativeLibraryConfig.Instance.WithLibrary(%PATH%) thing -- everything loads and works fine.

Any ideas in which direction to dig to solve this?

**Comment by martindevans** [comment]
If loading the binary by passing the explicit path isn't working it's likely you're missing some dependencies.

**Comment by Onkitova** [comment]
> If loading the binary by passing the explicit path isn't working it's likely you're missing some dependencies.
Are there any other dependencies except CUDA Toolkit?

**Comment by AsakusaRinne** [comment]
@Onkitova  What is the result of `nvcc -V` and `nvidia-smi` in your windows powershell?

**Comment by Onkitova** [comment]
@AsakusaRinne thanks for spotting this and also confirming my hypothesis. 

So, the problem was that initially nvcc -V returned:

> ![Screenshot 2023-12-09 074418](https://github.com/SciSharp/LLamaSharp/assets/119720012/ba32b3fe-6e56-47bf-9ce8-348dd67ae8b4)


after a little investigation I found out that a complete clear reinstall of Cuda Toolkit (12.2 or 12.3 as well, can surely confirm BOTH working) in "Express mode" + restart of PC solve the problem.

> ![Screenshot 2023-12-09 081149](https://github.com/SciSharp/LLamaSharp/assets/119720012/43d3fb0d-ca4b-437f-8652-fb11dbe05504)

It was kind of my bad that initially I tried to install CUDA Toolkit in custom mode and select just "CUDA/Runtime" components (which, occasionally, don't install **nvcc**), while -- in order to install **nvcc** -- you need to select "CUDA/Development" components as well like that:

> ![Screenshot 2023-12-09 080005](https://github.com/SciSharp/LLamaSharp/assets/119720012/f1f9cede-6ed8-4b35-8fee-87e1800c6139)

Now everything works as expected:

> ![Screenshot 2023-12-09 071246](https://github.com/SciSharp/LLamaSharp/assets/119720012/3c1cc36d-9c25-4412-9491-b97fc87c7b14)

Thank you!

However, I would like to ask 1 more thing before closing this issue: is there a way to somehow embed **nvcc** -- or libraries it actually refers to -- in order to not require the whole CUDA Toolkit as a prerequisite to running applications using llamasharp (if we expect cuda to work as well)? 

When there is only current nvidia driver installed and cuda toolkit isn't -- there is no such thing as **nvcc**.

**Comment by AsakusaRinne** [comment]
> is there a way to somehow embed nvcc -- or libraries it actually refers to -- in order to not require the whole CUDA Toolkit as a prerequisite to running applications using llamasharp (if we expect cuda to work as well)?

I'm afraid that I don't know a convinient way to achieve it. Theoretically, what we need to do is to put the files exactly the correct paths of  a PC. However the configuration differs on devices and systems, which requires a huge amount of work to take account of all the cases. So I prefer not to include it in the roadmap. If there's an one-click way to install cuda toolkit with nuget in the future, please let us know and we'll discuss about it again. :)

**Comment by Onkitova** [comment]
> Theoretically, what we need to do is to put the files exactly the correct paths of a PC.

One thing I have noticed is that every cuda-utilizing software (including, for example, another LLM UI program -- LM studio, which works with driver only and no cuda toolkit requirement) somewhy embeds these 3 files:

![Screenshot 2023-12-09 092506](https://github.com/SciSharp/LLamaSharp/assets/119720012/e1d53338-acc6-4b5e-8044-75e78d4f39d3)
Other software example:
![Screenshot 2023-12-09 081105](https://github.com/SciSharp/LLamaSharp/assets/119720012/cbf32fb6-fc5c-4695-8ba4-289b810137d4)
Most of them doesn't require CUDA Toolkit as a prerequisite.

The same 3 files that original llama.cpp repo distributes with every release under this asset package:
 
![Screenshot 2023-12-09 092147](https://github.com/SciSharp/LLamaSharp/assets/119720012/514b051b-06f0-4443-be09-9fe0196967e4)

I am telling you because you are possibly more able to debug further than average user getting this

>    System.TypeInitializationException: 'The type initializer for 'LLama.Native.NativeApi' threw an exception.'
    RuntimeError: Failed to load the native library [C:\Users\Username\Desktop\LLamaSharp-master\LLamaSharp-master\LLama.Examples\bin\Debug\net6.0\runtimes\win-x64\native\cuda12\libllama.dll] you specified.

Maybe those 3 files are the ones we need to reference in order to mitigate the error without CUDA Toolkit?

I am closing this issue as solved, but for now I suggest you to consider adding something about CUDA Toolkit installation (especially the part about truly necessary components of it: development and runtime components branches).

**Comment by AsakusaRinne** [comment]
Thank you a lot for this information! I'll test if this approach will work without requiring a CUDA. It'll be a great enhancement if that works. I've opened an issue for it #350
