### ISSUE TITLE
Support for multiple backends, auto-select the most optimal

### ISSUE THREAD

**Issue by dluc** [SciSharp/LLamaSharp#349]
I'm [adding LLamaSharp to KernelMemory](https://github.com/microsoft/kernel-memory/blob/83ffa83031529f3ac9e04cfc7bf0341a8e5186ab/service/Core/AI/Llama/LlamaSharpTextGenerator.cs) and I'd like to import both the CPU and Cuda12 backend packages, leaving it to LlamaSharp to select the optimal one (or the user, via configuration).

Looking at `NativeLibraryConfig` and `NativeApi` the code to autoselect the best option seems to be there, but I can't find a way for it to select Cuda when available. It's not clear if that code is even used.

With csproj:
```xml
<PackageReference Include="LLamaSharp" /> 
<PackageReference Include="LLamaSharp.Backend.Cuda12" />
```
the code works as expected, running prompts with CUDA (faster).

With csproj:
```xml
<PackageReference Include="LLamaSharp" /> 
<PackageReference Include="LLamaSharp.Backend.Cpu" /> 
<PackageReference Include="LLamaSharp.Backend.Cuda12" />
```
the code always uses CPU backend, ie it takes 50% more time to run a prompt on my test workstation.

I tried adding this in a few places:
```csharp
NativeLibraryConfig.Instance.WithCuda(true)
```
but it doesn't help with the issue above.

Any suggestion?

**Comment by AsakusaRinne** [comment]
Could you please take a look of the file structure of your output directory? (`x64/debug/net6.0/runtimes` for example) Then please use `NativeLibraryConfig.Instance.WithLogs()` to see the details during backend selection.

**Comment by dluc** [comment]
## Test 1: only CPU nuget

**Time taken: 29 secs**

```xml
<PackageReference Include="LLamaSharp" /> 
<PackageReference Include="LLamaSharp.Backend.Cpu" />
```
```
[LLamaSharp Native] [Info] NativeLibraryConfig Description:
- Path: 
- PreferCuda: True
- PreferredAvxLevel: AVX2
- AllowFallback: True
- SkipCheck: False
- Logging: True
- SearchDirectories and Priorities: { ./ }
[LLamaSharp Native] [Info] Detected OS Platform: WINDOWS
[LLamaSharp Native] [Info] Detected cuda major version 12.
[LLamaSharp Native] [Info] Tried to load runtimes/win-x64/native/cuda12/libllama.dll but failed.
[LLamaSharp Native] [Info] ./runtimes/win-x64/native/avx2/libllama.dll is selected and loaded successfully.
```
<img width="71" alt="image" src="https://github.com/SciSharp/LLamaSharp/assets/371009/fd27d5cd-1a39-4702-8ccf-0c2be128771b">

## Test 2: only CUDA 12 nuget

**Time taken: 22 secs**

```xml
<PackageReference Include="LLamaSharp" />
<PackageReference Include="LLamaSharp.Backend.Cuda12" />
```
```
[LLamaSharp Native] [Info] NativeLibraryConfig Description:
- Path: 
- PreferCuda: True
- PreferredAvxLevel: AVX2
- AllowFallback: True
- SkipCheck: False
- Logging: True
- SearchDirectories and Priorities: { ./ }
[LLamaSharp Native] [Info] Detected OS Platform: WINDOWS
[LLamaSharp Native] [Info] Detected cuda major version 12.
[LLamaSharp Native] [Info] ./runtimes/win-x64/native/cuda12/libllama.dll is selected and loaded successfully.
```

Under "native" there's only one folder with the DLL inside:
<img width="64" alt="image" src="https://github.com/SciSharp/LLamaSharp/assets/371009/5590f922-7c3e-477c-8d9a-b69690b79345">


## Test 3: both CPU and CUDA 12 nugets

**Time taken: 29 secs**

```xml
<PackageReference Include="LLamaSharp" /> 
<PackageReference Include="LLamaSharp.Backend.Cpu" />
 <PackageReference Include="LLamaSharp.Backend.Cuda12" />
```
```
[LLamaSharp Native] [Info] NativeLibraryConfig Description:
- Path: 
- PreferCuda: True
- PreferredAvxLevel: AVX2
- AllowFallback: True
- SkipCheck: False
- Logging: True
- SearchDirectories and Priorities: { ./ }
[LLamaSharp Native] [Info] Detected OS Platform: WINDOWS
[LLamaSharp Native] [Info] Detected cuda major version 12.
[LLamaSharp Native] [Info] ./runtimes/win-x64/native/cuda12/libllama.dll is selected and loaded successfully.
```

**FunctionalTests\bin\Debug\net7.0\runtimes:**
<img width="80" alt="image" src="https://github.com/SciSharp/LLamaSharp/assets/371009/df52232c-d203-43e7-9b52-a42c1e5349e0">

**FunctionalTests\bin\Debug\net7.0\runtimes\win-x64\native:**
<img width="80" alt="image" src="https://github.com/SciSharp/LLamaSharp/assets/371009/066e7603-ac42-4edd-a978-aa04db95c500">
<img width="117" alt="image" src="https://github.com/SciSharp/LLamaSharp/assets/371009/6abb9103-b1f0-4069-b0b8-9ab06a74d202">

**Comment by dluc** [comment]
@AsakusaRinne so everything looks ok from the logs, but as you can see the time taken doesn't match.

* Test 1: only CPU nuget - Time taken: 29 secs
* Test 2: only CUDA 12 nuget - Time taken: 22 secs
* Test 3: both CPU and CUDA 12 nugets - Time taken: 29 secs

**Comment by AsakusaRinne** [comment]
If you delete the `libllama.dll` at the root of output path, would the time taken act as expected? Note that after removing the file, please don't re-compile the project.

**Comment by martindevans** [comment]
Also you could try adding a breakpoint in [here](https://github.com/SciSharp/LLamaSharp/blob/master/LLama/Native/NativeApi.Load.cs#L308). From there you can see the exact set of binaries it's going to try (`libraryTryLoadOrder`) and which one it succeeds on.

**Comment by dluc** [comment]
I've created a new project to run these tests and taken the steps to manually delete the DLL files. Interestingly, in this new project, the performance timings between cuda12 and avx2 are too close to definitively say if there's an issue. For the time being, I'm placing my trust in the logs. If an opportunity arises where I can obtain a machine with a more powerful Nvidia card, I'll conduct further tests where the performance gap would likely be more evident.

**Comment by AsakusaRinne** [comment]
@dluc If needed, you could set `GpuLayerCount` a larger number to increase the time gap between cpu version and gpu version.
