### ISSUE TITLE
Debugger Stops if Calling TensorSplitsCollection

### ISSUE THREAD

**Issue by hswlab** [SciSharp/LLamaSharp#351]
When initializing the Model Params with

`
ModelParams parameters = new ModelParams(modelPath)
{
    ContextSize = 1024
};
`

My debuger in Visual Studio just stops. 
Something is wrong with this parameter initialization in the ModelParams object

`
TensorSplits = new TensorSplitsCollection();
`

It makes no problem on another windows 10 pc but on my notebook. I have no idea why this is happening, because I'm not able to debug it :)

My notebook is just supporting avx, but my pc can also use avx2. Probably this is the reason? I was testing with v0.8.1 of llamasharp and the avx binaries of this archive https://github.com/SciSharp/LLamaSharp/actions/runs/6921572568

**Comment by martindevans** [comment]
When the `TensorSplitsCollection` is created it runs this code:

```csharp
internal readonly float[] Splits = new float[NativeApi.llama_max_devices()];
```

If you just try to execute that, does it crash in the same way?

**Comment by hswlab** [comment]
I'm only using the nuget package right now on my notebook and can't edit the llamasharp code. But I tried calling NativeApi.llama_max_devices() in my code directly and the same thing happens. The debugger aborts. It seems, that llama_max_devices can't be callen on my notebook .

**Comment by martindevans** [comment]
The NativeApi call just directly calls llama.cpp and there's no other C# code involved, so I think you'll have to report this one to llama.cpp.

**Comment by martindevans** [comment]
I went to look at llama.cpp and the contents of `llama_max_devices` are:

```cpp
int llama_max_devices(void) {
    return LLAMA_MAX_DEVICES;
}
```

So there's probably something else going wrong here!

**Comment by hswlab** [comment]
I currently have looked at the ModelParams method on PC and notebook in the debugger. Somehow this method looks different. On the PC the constructor looks like this. 
![image](https://github.com/SciSharp/LLamaSharp/assets/12501993/29dd5500-c768-4568-a77d-00c3b4259c0f)

But on the notebook the constructor looks like this
image will be uploaded in a minute,

I'm actually using the same GIT status on both pcs. If the constructor on the notebook and PC were swapped, it probably wouldn't crash when calling llama_max_devices, because my PC has no problems with this method. But I don't understand why the constructor looks different at all. Maybe I'll see a bit clearer tomorrow^^.
