### ISSUE TITLE
How to train on own data

### ISSUE THREAD

**Issue by Amine-Smahi** [SciSharp/LLamaSharp#379]
Hi team,
Thank you for the amazing efforts,

I would like to use LLamaSharp with my own data, can someone guide me on how can i accomplish that, my goal is that the user can chat, and responses are based on my knowledge base,

Thank you in advance 🙏

**Comment by martindevans** [comment]
Training/finetuning isn't something that you can do with LLamaSharp at the moment (I'm not sure how you're even able to do it with llama.cpp itself).

It sounds to me like you may not need training though, if you want to provide documents with extra context to the LLM then you might want to look into using RAG through semantic kernel.
