### ISSUE TITLE
How do I make a custom build on MacOS?

### ISSUE THREAD

**Issue by Johnhersh** [SciSharp/LLamaSharp#38]
When I make a custom build on MacOS it makes a libllama.so file. However it seems Llamasharp is expecting a .dll file? I also see a libllama.dylib, and the runtimes folder has other dlls. How do we determine which runtime it uses?

The reason I'm trying to do this is the latest llama.cpp project has support for Metal and it runs much faster on my hardware. I'm trying to build an API around it, which I can do with the files from /runtime out of the box, but I'm not familiar enough with building C++ to include my custom build in there.

**Comment by AsakusaRinne** [comment]
LLamaSharp uses P/Invoke to interop with native library. It's the dotnet runtime's responsibility to decide which file to use since the call is only something like `DllImport("libllama")`.

Because I don't have a MAC device, it's the community effort that makes the MAC library file, which is `libllama.dylib`. Is it possible to generate it on your MAC book?

**Comment by Johnhersh** [comment]
> LLamaSharp uses P/Invoke to interop with native library. It's the dotnet runtime's responsibility to decide which file to use since the call is only something like `DllImport("libllama")`.
> 
> Because I don't have a MAC device, it's the community effort that makes the MAC library file, which is `libllama.dylib`. Is it possible to generate it on your MAC book?

Yes, this is essentially what I came here to ask, is how do I do that? I don't see a way to build the .dylib file. When I build the project with libraries what I get is a .so file

So is all that is needed is just putting that .so file in there? Or do I also need to generate the .dylib file? If so, how do I build the dylib file?

**Comment by SignalRT** [comment]
> When I make a custom build on MacOS it makes a libllama.so file. However it seems Llamasharp is expecting a .dll file? I also see a libllama.dylib, and the runtimes folder has other dlls. How do we determine which runtime it uses?
> 
> The reason I'm trying to do this is the latest llama.cpp project has support for Metal and it runs much faster on my hardware. I'm trying to build an API around it, which I can do with the files from /runtime out of the box, but I'm not familiar enough with building C++ to include my custom build in there.

I make a PR to the repository with metal support. You already have that version on my fork if you want to test it

**Comment by Johnhersh** [comment]
> > When I make a custom build on MacOS it makes a libllama.so file. However it seems Llamasharp is expecting a .dll file? I also see a libllama.dylib, and the runtimes folder has other dlls. How do we determine which runtime it uses?
> > The reason I'm trying to do this is the latest llama.cpp project has support for Metal and it runs much faster on my hardware. I'm trying to build an API around it, which I can do with the files from /runtime out of the box, but I'm not familiar enough with building C++ to include my custom build in there.
> 
> I make a PR to the repository with metal support. You already have that version on my fork if you want to test it

That's super cool, I'll check it out. Thank you!

As someone not good with C++, how did you generate that .metal and .dylib file from the llama.cpp project? I'd like to understand how that process works in case I want to make custom builds

**Comment by SignalRT** [comment]
![image](https://github.com/SciSharp/LLamaSharp/assets/16475613/f24f1398-cd07-485c-b3ce-ff8d30291054)

And LLAMA_METAL=Off if you want a only CPU version

**Comment by drasticactions** [comment]
`.so` is a static framework, you need to compile llama with `-DBUILD_SHARED_LIBS=ON` to build a dynamic version, which this binding expects.
