### ISSUE TITLE
Add solar llm support

### ISSUE THREAD

**Issue by darcome** [SciSharp/LLamaSharp#395]
Can you please add support for solar models like this one: https://huggingface.co/TheBloke/SOLAR-10.7B-Instruct-v1.0-GGUF

It seems these models are obtaining the highest ranking in huggingface leaderboard: https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard

Thanks in advance!

**Comment by martindevans** [comment]
Support for new models is something that needs to be done in the main llama.cpp project, once that's done we'll pick up support for it when the binaries we distribute are updated (usually about once a month).

Do you know version of llama.cpp introduced SOLAR support? It's possible that we already have support for them in the master branch.

**Comment by martindevans** [comment]
We've just released 0.9.1 with a new set of llama.cpp binaries, which _may_ add SOLAR support (untested, but the date looks about right).

**Comment by darcome** [comment]
This is what I get when I try solar with 0.9.1:

![image](https://github.com/SciSharp/LLamaSharp/assets/18150093/b2372a2b-b3c1-4009-9938-4cc97ee9b76f)

**Comment by martindevans** [comment]
Odd. I just tested `solar-10.7b-instruct-v1.0.Q5_K_M.gguf` with v0.9.1 (CPU backend) and it worked perfectly.

Which backend are you using? (And if it's not CPU only, could you try that please).

**Comment by darcome** [comment]
I am using CPU backend:

![image](https://github.com/SciSharp/LLamaSharp/assets/18150093/c137523d-3676-4eab-a1ad-781fab400a3b)

**Comment by martindevans** [comment]
I noticed that although you linked to `SOLAR-instruct` in your initial message (which is what I've been testing with) your code mentions `SOLAR-instruct-uncensored`. I'm downloading that to test now.

**Comment by martindevans** [comment]
I just tried with `solar-10.7b-instruct-v1.0-uncensored.Q5_K_M.gguf` and that works too! Is it possible your model file is corrupted?

**Comment by martindevans** [comment]
@darcome are you still having issues with SOLAR, or was it just a corrupt model file?

**Comment by darcome** [comment]
It works perfectly with gpt4all.

![image](https://github.com/SciSharp/LLamaSharp/assets/18150093/069d6ee7-0133-4d00-a7b4-382f37d8a21f)

**Comment by martindevans** [comment]
I just noticed in your example code in [this comment](https://github.com/SciSharp/LLamaSharp/issues/395#issuecomment-1880126133) there is no ".gguf" file extension on the file you're trying to load. Is that correct?

**Comment by martindevans** [comment]
Well I'm glad it turned out to be something simple to fix in the end! I'll add some additional checking into the `LoadWeights` call so you get a sensible error message in the future, instead of an access violation exception!
