### ISSUE TITLE
What is a good local model for generating Embeddings?

### ISSUE THREAD

**Issue by AshD** [SciSharp/LLamaSharp#406]
I am using Mistral 7B Instruct v0.2 with LlamaSharp embeddings but it seems to be failing to match with items in this list. Is there an issue with Cosine Matches with this model? Is there another local model that works better?

https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example15_TextMemoryPlugin.cs

```
       SemanticTextMemory textMemory = new(memoryStore, embeddingGenerator);

        Console.WriteLine("== PART 1a: Saving Memories through the ISemanticTextMemory object ==");

        await textMemory.SaveInformationAsync(MemoryCollectionName, id: "info1", text: "My name is Andrea", cancellationToken: cancellationToken);
        await textMemory.SaveInformationAsync(MemoryCollectionName, id: "info2", text: "I work as a tourist operator", cancellationToken: cancellationToken);
        await textMemory.SaveInformationAsync(MemoryCollectionName, id: "info3", text: "I've been living in Seattle since 2005", cancellationToken: cancellationToken);
        await textMemory.SaveInformationAsync(MemoryCollectionName, id: "info4", text: "I visited France and Italy five times since 2015", cancellationToken: cancellationToken);

         await foreach (var answer in textMemory.SearchAsync(
            collection: MemoryCollectionName,
            query: "where did I grow up?",
            limit: 2,
            minRelevanceScore: 0.79,
            withEmbeddings: true,
            cancellationToken: cancellationToken))
        {
            Console.WriteLine($"Answer: {answer.Metadata.Text}");
        }
```

Expected Answer:  "My family is from New York","I\u0027ve been living in Seattle since 2005"

Actual Answer: [No Match]

Thanks,
Ash

**Comment by martindevans** [comment]
Maybe I'm misunderstanding something, but "new york" doesn't seem to be mentioned anywhere in the saved information?

**Comment by AshD** [comment]
Good catch Martin. I missed one text addition, "my family is from New York"

**Comment by AshD** [comment]
I tried to use https://huggingface.co/intfloat/e5-mistral-7b-instruct but ran into conversion errors.
https://github.com/ggerganov/llama.cpp/discussions/4786

**Comment by martindevans** [comment]
Did adding that extra text resolve the initial issue?

**Comment by AshD** [comment]
No. The non instruct Mistral 7B v0.1 gave me slightly better matches (0.31 relevance scores) compared to the Mistral 7B Instruct v0.2 (0.2 relevance scores).

Reading stuff on this issue elsewhere, it looks like the way to go is to use a model specifically designed for embedding but I could not find a GGUF version of an embedding model and when I tried to convert it them (the top ones from the MTEB space), they failed with model architecture not supported.

If anyone has a GGUF version of a model that works well for embedding, would appreciate if you point me to it. 

Thanks,
Ash

**Comment by martindevans** [comment]
In that case I'd recommend opening a discussion on the main llama.cpp repo, you'll probably get a better response over there (just because it's a bigger repo, with more people who can answer your question).

**Comment by AshD** [comment]
I opened one yesterday https://github.com/ggerganov/llama.cpp/discussions/4786

Hopefully, someone will respond.

**Comment by martindevans** [comment]
I was thinking a more general discussion asking for embedding model recommendations.

**Comment by AshD** [comment]
Will do

**Comment by AshD** [comment]
Did some more research and I found that lama.cpp does not support embedding models as of now. 

This project does https://github.com/xyzhang626/embeddings.cpp

I will try it out tomorrow.
