### ISSUE TITLE
Example code in the main README.MD does not work with 0.9.1.

### ISSUE THREAD

**Issue by darcome** [SciSharp/LLamaSharp#414]
This is a screenshot from a copy paste from the Quick Start guide and it doesn't work anymore.

![image](https://github.com/SciSharp/LLamaSharp/assets/18150093/2c443c4c-1353-44ae-ad7b-57923d4de63b)

Can you please update it to reflect the new way of interacting with llamasharp? I think this is very important because if someone tries the code in the readme and it doesn't work, probably will throw the library in the bin and use something else :D

Thanks in advance!

**Comment by martindevans** [comment]
I've just opened #415 with an update to the readme that should fix this. If you could confirm on that PR if it works for you that'd be great :)
