### ISSUE TITLE
Add auto gpu layer count detection

### ISSUE THREAD

**Issue by ChezzPlaya** [SciSharp/LLamaSharp#42]
Currently, we have to provide the right amount of gpu layer count for each model individually. 

It would be nice, if the best possible amount of gpu layer count can be computed or estimated **automagically** dependent of user's gpu capability.

**Comment by martindevans** [comment]
Some related upstream discussion:
 - https://github.com/ggerganov/llama.cpp/issues/3719

**Comment by martindevans** [comment]
I'm going to close this one as wontfix for now. Sorry :(

Implementing it in LLamaSharp itself isn't possible. We would need changes upstream in llama.cpp to calculate the number. Of course if that does ever get implemented in llama.cpp then LLamaSharp will use it!

@ChezzPlaya if you're still interested in this feature please open a feature request on llama.cpp (and link it here). That's the first step required!
