### ISSUE TITLE
Verbose and GPU layers = -1 - are both missing?

### ISSUE THREAD

**Issue by Kaotic3** [SciSharp/LLamaSharp#421]
Usually when loading up a model with Llama you can specify n_gpu_layers=-1 and this will use all the available layers.

You can also add "verbose=False" and bypass the output messages of loading and making inferences.

It looks like this in python:

`llm = Llama(model_path=model_path, n_gpu_layers=-1, n_ctx=4096, verbose=False)`

I noted when I tried:

`var parameters = new ModelParams(modelPath)
{
    ContextSize = 4096,
    Seed = 1337,
    GpuLayerCount = -1,
};`

It tried to offload -1 GPU layer.

I tried looking for "Verbose" or something similar, went through the entire list reading the description and could not find it.

Thanks btw, this is awesome, I was so sick to death of working in python it was great to find a solution in C# so I can use a real programming language! lol

**Comment by martindevans** [comment]
> n_gpu_layers = -1

I was initially quite confused by this!

1. [This line](https://github.com/ggerganov/llama.cpp/blob/42ea63c5a3da01d4a94e906d8565868012c79f4f/common/common.h#L60) says that -1 is "default" (whatever that means).
2. Then [this line](https://github.com/ggerganov/llama.cpp/blob/42ea63c5a3da01d4a94e906d8565868012c79f4f/common/common.cpp#L1032) simply _does nothing_ if the value is -1, which kind of makes sense if it's using the default.
3. However, over [here](https://github.com/ggerganov/llama.cpp/blob/42ea63c5a3da01d4a94e906d8565868012c79f4f/llama.cpp#L9560) we can see that the default is **0**!

So from the cpp code, -1 means "no layers".

However, looking over at the Python code I found [this](https://github.com/abetlen/llama-cpp-python/blob/142a9e1bc3227c511a204f941fc4a058c2db4577/llama_cpp/llama.py#L848C9-L850C69) which converts -1 into `0x7FFFFFFF`, thus offloading all layers. So this is a special behaviour introduced by llama-cpp-python.

In your own code I'd recommend just setting `int.MaxValue` when you want to offload all layers.

In fact if you're interested in contributing to LLamaSharp it would be an easy PR to add some validation to the `GpuLayerCount` in [this method](https://github.com/SciSharp/LLamaSharp/blob/master/LLama/Extensions/IModelParamsExtensions.cs#L24) to ensure it's not a silly value like -1. Or to replace any negative number with `int.MaxValue`, to get something like the python behaviour.

> Verbose

I'm think this is another Python specific behaviour. llama.cpp has a `llama_log_set` method which is called whenever a message is logged (if not set it just prints it out). I guess llama-cpp-python must be hooking that method automatically and redirecting messages based on if verbose is set. As far as I know there's no verbose flag you can set in llama.cpp itself.

You should call `NativeApi.llama_log_set` with your own callback, then you can process messages however you like (e.g. redirect to a proper logging provider and suppress the categories you don't care about).

**Comment by Kaotic3** [comment]
You know, I didn't think that the python implementation might have introduced those quality of life improvements.

Wouldn't this implement the -1 in the ToLlamaModelParams you referred to?  Sorry, not that great with GitHub to be doing pull requests into a live repo that isn't my own.

```
if (@params.UseMemoryLock && !NativeApi.llama_mlock_supported())
    throw new NotSupportedException("'UseMemoryLock' is not supported (llama_mlock_supported() == false)");
if (@params.UseMemorymap && !NativeApi.llama_mmap_supported())
    throw new NotSupportedException("'UseMemorymap' is not supported (llama_mmap_supported() == false)");
if (@params.GpuLayerCount == -1)
    @params.GpuLayerCount = int.MaxValue;
```

**Comment by martindevans** [comment]
Rather than making -1 a special case I'd do it as:

```csharp
if (@params.GpuLayerCount < 0)
    @params.GpuLayerCount = int.MaxValue;
```

That way any negative value mean "all layers".

> Sorry, not that great with GitHub to be doing pull requests into a live repo that isn't my own.

The process is fairly simple:
1. Push your change into a branch in your fork
2. Visit https://github.com/SciSharp/LLamaSharp/pulls
3. At the top, there should be a button asking if you want to open a PR for your new branch
4. Done!

If you're struggling with it, I'm happy to add this change for you. Just say so - I don't want to take away a chance for you to contribute!

**Comment by Kaotic3** [comment]
You know, I thought about the < 0 and then I thought - well, -1 means something to people who perhaps have used the Python port - and therefore those people would be expecting to offload all layers to the GPU and the int.MaxValue would make sense.

But I think I over thought it - what are the changes of "accidentally" typing a minus number there?

I will try and do a pull request, as I would like to contribute if I can - as this is a rather good project.

**Comment by Kaotic3** [comment]
In my pull request, I forgot, I removed net8.0 from the csproj as I was trying to get the unit-tests to run.

**Comment by martindevans** [comment]
That's fine, you can just re-add it and push to the same branch in your fork. It will update the PR :)

**Comment by martindevans** [comment]
I'll close this one, since #424 has resolved the main issue.
