### ISSUE TITLE
Can't load phi-2 model

### ISSUE THREAD

**Issue by Camel-RD** [SciSharp/LLamaSharp#429]
Im trying to load this file dolphin-2_6-phi-2.Q5_K_M.gguf
and LLamaWeights.LoadFromFile throws this exception:

> System.AccessViolationException
>   HResult=0x80004003
>   Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>   Source=<Cannot evaluate the exception source>
>   StackTrace:
> <Cannot evaluate the exception stack trace>
>

**Comment by martindevans** [comment]
Support for Phi2 was added to llama.cpp quite recently, we'll need to update the binaries that we distribute to include support. This is beaing tracked in #381 :)
