### ISSUE TITLE
Falcon 7b instruct 5bit doesn't work

### ISSUE THREAD

**Issue by ChezzPlaya** [SciSharp/LLamaSharp#43]
https://huggingface.co/TheBloke/falcon-7b-instruct-GGML/tree/main

I encounter this error when I try to load the 5bit model:

```
error loading model: missing tok_embeddings.weight
```

**Comment by martindevans** [comment]
As far as I can tell the `ggcc` files are not compatible with llama.cpp and are instead used by [a fork](https://github.com/cmp-nct/ggllm.cpp)?

It looks like the mainline llama.cpp does not yet support Falcon. Here are some relevant upsteam issue to keep an eye on, once these are completed we should be able to add Falcon support:
 - Tracking Issue: https://github.com/ggerganov/llama.cpp/issues/1602
 - Roadmap: https://github.com/users/ggerganov/projects/7/views/1?filterQuery=falcon
 - Related work (major refactor of file formats): https://github.com/ggerganov/llama.cpp/pull/2398

**Comment by cmp-nct** [comment]
GGUC is for https://github.com/cmp-nct/ggllm.cpp

**Comment by martindevans** [comment]
The tracking issue I mentioned above is now marked as complete. I think the LLamaSharp 0.5.1 release should support Falcon now.
