### ISSUE TITLE
Responses are always Chinese

### ISSUE THREAD

**Issue by kiebor** [SciSharp/LLamaSharp#439]
Trying to use the BotSharp integration for LlamaSharp, I've encountered an issue where all responses are in Chinese and always the same text. 

你好，我是小芭。您可以对我说“小芭，帮我做什么”，我会尽力帮助您。

The repo owner of BotSharp suggested I submit the problem here.

For reference, https://github.com/SciSharp/BotSharp/issues/253.

I'm at a loss for why this would be happening, save for a misconfiguration. I was under the impression this should all simply work with minimal setup. Is anyone able to steer me in the right direction?

**Comment by martindevans** [comment]
Could you try the model out in some of the LLamaSharp examples (e.g. just simple stateless chat) and see if it speaks Chinese to you there?

**Comment by kiebor** [comment]
Just tested a few of the example scenarios, and the model responds in English. Within BotSharp it refers to itself as Xiaoba, which is why I opened the bug in that repo. It's more like some overriding agent configuration is active than an inherent issue with the model or LlamaSharp library.

**Comment by martindevans** [comment]
That sounds more likely to be an issue with BotSharp than with LLamaSharp to be honest.

**Comment by kiebor** [comment]
Thanks. That's what I was thinking.
