### ISSUE TITLE
on linux centos 8 get The type initializer for 'LLama.Native.NativeApi' threw an exception

### ISSUE THREAD

**Issue by lmxin123** [SciSharp/LLamaSharp#457]
Unhandled exception. System.TypeInitializationException: The type initializer for 'LLama.Native.NativeApi' threw an exception.
 ---> LLama.Exceptions.RuntimeError: The native library cannot be correctly loaded. It could be one of the following reasons: 
1. No LLamaSharp backend was installed. Please search LLamaSharp.Backend and install one of them. 
2. You are using a device with only CPU but installed cuda backend. Please install cpu backend instead. 
3. One of the dependency of the native library is missed. Please use `ldd` on linux, `dumpbin` on windows and `otool`to check if all the dependency of the native library is satisfied. Generally you could find the libraries under 
your output folder.4. Try to compile llama.cpp yourself to generate a libllama library, then use `LLama.Native.NativeLibraryConfig.WithLibrary` to specify it at the very beginning of your code. For more informations about compilation, please refer 
to LLamaSharp repo on github.
   at LLama.Native.NativeApi..cctor()
   --- End of inner exception stack trace ---
   at LLama.Native.NativeApi.llama_max_devices()
   at LLama.Abstractions.TensorSplitsCollection..ctor()
   at LLama.Common.ModelParams..ctor(String modelPath)
   at Program.<Main>$(String[] args) in Program.cs:line 12
   at Program.<Main>(String[] args)
Aborted (core dumped)

**Comment by martindevans** [comment]
Which backend (CPU/CUDA) are you using?

**Comment by lmxin123** [comment]
> Which backend (CPU/CUDA) are you using?

I use cpu , .net 8.0

**Comment by martindevans** [comment]
That must mean your system is missing a dependency which the libllama.so requires. It's compiled on Ubuntu (see [here](https://github.com/SciSharp/LLamaSharp/blob/master/.github/workflows/compile.yml#L17-L45)), so it must be something Ubuntu ships with that Centos8 does not.

**Comment by lmxin123** [comment]
How can we solve this problem

**Comment by martindevans** [comment]
It's not really something I know a lot about. Did you try `ldd` as suggested in the initial error message? That might give some hints.

**Comment by lmxin123** [comment]
I have tried it, but it cannot be solved. Could it be a problem with. net 8

**Comment by martindevans** [comment]
You could try with .net6 instead, I think it's unlikely to be a dotnet issue though tbh. What did ldd output?

**Comment by lmxin123** [comment]
use ubuntu2204 ,the above error did not occur
