### ISSUE TITLE
Porting to a winform

### ISSUE THREAD

**Issue by Webslug** [SciSharp/LLamaSharp#46]
I've been trying to port this to a VS Winform using a rich text box as the output as opposed to the console.   Are there some good WinForm examples using LlamaSharp which I can use? 

My goal is to incorporate this into a program for the visually disabled and they cannot use the terminal.

The model I use works fine in a terminal however when I try and incorporate LLamasharp into a Win Form the output from the same model can vary.

**Comment by yakovw** [comment]
Someone made such a project in WPF
But first I need to understand what your problem is, the exact same code only works for you in the console?

**Comment by Jefdem1** [comment]
https://www.jeffdemuth.com/blogs/llama.html
Not sure if it helps but i posted my code here for setting everything up and some example code using a winform.

**Comment by AsakusaRinne** [comment]
I guess the problem may come from .net framework in winform. I think using WPF will be better because of the compatibility for dotnet core.

> Someone made such a project in WPF

@yakovw May I ask for a link of this project?

**Comment by saddam213** [comment]
> I guess the problem may come from .net framework in winform. I think using WPF will be better because of the compatibility for dotnet core.
> 
> > Someone made such a project in WPF
> 
> @yakovw May I ask for a link of this project?

https://github.com/saddam213/LLamaStack/tree/master/LLamaStack.WPF#readme
