### ISSUE TITLE
[Proposal] Drop support for netstandard2.0 and .NET 6.0

### ISSUE THREAD

**Issue by jasoncouture** [SciSharp/LLamaSharp#466]
## Why
To improve performance, we can swap out [DllImport] with [LibraryImport].
The reason this improves performance, is instead of the JIT needing to figure out marshalling at runtime, Marshalling is instead generated with a source generator. This allows it to be optimized at build time, instead of runtime.

## But why do we need to remove these to get `[LibraryImport]`?
LibraryImport was introduced in .NET 7, and is not supported on those platforms.
The netstandard TFM (Target framework moniker) was replaced in .NET 5 with net5.0
net5.0 is to .NET 5, what netstandard2.0 is to .NET Core 2.0.

## What about .NET 6 though?
.NET 6's end of life is November 12, 2024. While we shouldn't just randomly drop frameworks because they're EOL (.NET 7 actually goes EOL before 6 does), I think if a version becomes a blocker for a feature, and it's at or near it's end of life, it should be dropped.

## Other considerations

In the grand scheme of things, the performance difference is approximately 2-3% faster. This would likely have no visible impact to users of LlamaSharp. I'd still advocate for this change, but this is really meant to start a discussion on the topic.

**Comment by martindevans** [comment]
Using `[LibraryImport]` is something I've considered a few times. Unfortunately I think dropping netstandard2.0 support is a non-starter, since afaik it's required for Unity (which we don't have an "official" package for, but I know a lot of people use the library within Unity, so I'd rather not break it).

Would dropping netstandard2.0 also entail dropping support for .NET Framework?

**Comment by jasoncouture** [comment]
It indeed would break <= .NET 5. But there are not going to be any new versions past 4.x.

I'll close the issue, it's definitely important to continue to support Unity at least, until they get off their rear and host .NET 7/8 instead of relying on the old framework hosting APIs.

**Comment by AsakusaRinne** [comment]
@martindevans Maybe we could use condition-compiling to introduce this performance improvement? Like below

```cs
#if NET7_OR_HIGHER
    [LibraryImport]
    void func();
#else
    [DllImport]
    void func();
#endif
```

**Comment by martindevans** [comment]
We could, personally I've avoided it since it adds even more complexity to the binary update process.

Do you know how of a performance benefit this is? As I understand it it improves the performance on the _first_ call of a function, but doesn't make much difference after that?

**Comment by AsakusaRinne** [comment]
In the description of this issue, approximately 2-3% improvement is confirmed. It does mess the code layout if we add it in the way I said. Why there's not a macro in C#, just like C++.  :(

**Comment by martindevans** [comment]
One idea I have toyed around with but haven't implemented is something to take llama.h and to auto generate the entire native bindings in C#. If we had something like that I think it would make sense to add the `LibraryImport`/`DllImport` attributes as appropriate. Might be worth investigating in the future.
