### ISSUE TITLE
Providing instructions on how to build libllama

### ISSUE THREAD

**Issue by Orfeous** [SciSharp/LLamaSharp#5]
Hello!

Great work so far, i have tons of fun with it. However libllama.dll which is included is outdated, and i just cant figure out how to build it myself. llama.cpp build scripts always end up with executables instead of a dll.

Some instructions on how to update it would be much appreciated.

**Comment by AsakusaRinne** [comment]
Hi, glad to here that `LLamaSharp` works well for you. For building `llama.cpp` library, please use `cmake .. -DBUILD_SHARED_LIBS=ON` to config the cmake build (with other options such as openblas and cublas). Then you'll find the .dll or .so file. We'll also update the library today or tomorrow. Thank you for your reminder. :)

**Comment by Orfeous** [comment]
Awesome! Thank you.

**Comment by DifferentialityDevelopment** [comment]
I got llama built with your instructions and was able to get it running with the latest version of llama.cpp, the issue I encountered was rather that currently you can't pass the parameters to indicate how many layers to offload to the GPU using cuBLAS or OpenBLAS, unless I'm missing something.

**Comment by AsakusaRinne** [comment]
@DifferentialityDevelopment The master branch has been updated and `n_gpu_layers` param was added. Please try with master branch, or with v0.2.2 several hours later.
