### ISSUE TITLE
Anyone realyy successs by following the steps in the Get Started? 

### ISSUE THREAD

**Issue by tiger2014** [SciSharp/LLamaSharp#509]
Anyone realyy successs by following the steps in the Get Started? I never success.

**Comment by martindevans** [comment]
Do you mean the [Quick Start](https://scisharp.github.io/LLamaSharp/0.5/GetStarted/) guide? If so, what's the problem you're seeing?

**Comment by vikramvee** [comment]
@tiger2014  I had done the setup some days ago. Let me know issues you are facing. I can help you out here.

**Comment by martindevans** [comment]
Unfortunately our docs aren't in a great state at the moment, they've fallen behind development of the asset. I believe it has been renamed `ChatAsync` and you'll need to await it.

**Comment by vikramvee** [comment]
@tiger2014 : Clone the repository at your end, install the required dependencies. Set the LLama.Examples as start up project and you should be able to see the console app with multiple options.

**Comment by tiger2014** [comment]
> @tiger2014 : Clone the repository at your end, install the required dependencies. Set the LLama.Examples as start up project and you should be able to see the console app with multiple options.

Never work.
![image](https://github.com/SciSharp/LLamaSharp/assets/6703612/a2e639c6-70e7-4606-b746-83b7951520f2)
![image](https://github.com/SciSharp/LLamaSharp/assets/6703612/a0d46ebf-0861-422f-9fbc-a88157e41c64)
![image](https://github.com/SciSharp/LLamaSharp/assets/6703612/de335354-3475-4855-b814-401d3cd33e76)
![image](https://github.com/SciSharp/LLamaSharp/assets/6703612/58a3bfce-519e-43fb-8081-b4208a9cf0ce)

**Comment by martindevans** [comment]
A `.bin` model is not compatible with llama.cpp. You need to use a `.gguf` model.

**Comment by tiger2014** [comment]
> A `.bin` model is not compatible with llama.cpp. You need to use a `.gguf` model.

There is only .bin file link on the page of the ['Get Started'](https://huggingface.co/AsakusaRinne/LLamaSharpSamples/tree/v0.3.0/LLaMa/7B). So, can you share a link of .gguf.

And hope there will be working Console prject sample with full steps.

**Comment by martindevans** [comment]
Try one of [these](https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF/tree/main) :)

**Comment by tiger2014** [comment]
> Try one of [these](https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGUF/tree/main) :)

Thank you so much. Successed!

**Comment by martindevans** [comment]
Since it looks like it's working for you I'll close this issue, feel free to re-open if there's still a problem
