### ISSUE TITLE
Gemma Is Not Supported

### ISSUE THREAD

**Issue by zddtpy** [SciSharp/LLamaSharp#533]
This is a. net 8.0 console project. When I was running it, the following error occurred,'Attempted to read or write protected memory. This is often an indication that other memory is corrupt'. Can anyone provide some help.thanks.The model used is Google's gemma-2b

**Comment by martindevans** [comment]
Gemma is a very new model format that's not supported in LLamaSharp yet. Support was added to llama.cpp yesterday, we'll hopefully upgrade our version within a month or so :)

**Comment by zddtpy** [comment]
> Hi @zddtpy, I had a similar error when I followed the steps on https://github.com/SciSharp/LLamaSharp?tab=readme-ov-file#installation
> 
> In my case the error was resolved by removing the "cuda" package and installing the "cpu" one instead.

emm.maybe i have install the "cpu",but not work

**Comment by zddtpy** [comment]
> Gemma is a very new model format that's not supported in LLamaSharp yet. Support was added to llama.cpp yesterday, we'll hopefully upgrade our version within a month or so :)

looking forward to you

**Comment by swharden** [comment]
As as aside, this seems to be a pretty common error message. It comes up in a lot of issues...

* #533
* #492
* #464
* #524
* #429
* #441
* #189

It may be helpful to catch this error and provide a more descriptive message of what may have gone wrong. Maybe pointing users to a URL with "things to try" would be helpful.

**Comment by zsogitbe** [comment]
There is no special code needed in LLamaSharp for Gemma to work. You just need to recompile the Cpp code yourself and it will work (I have tested the Gemma models already).

**Comment by martindevans** [comment]
> You just need to recompile the Cpp code yourself and it will work (I have tested the Gemma models already)

Note that in general you can't just recompile an up-to-date version of llama.cpp and use it with LLamaSharp. llama.cpp is constantly making small breaking changes to their API, so almost every update of the binaries requires a bit of tweaking to the C# binding layer.

**Comment by martindevans** [comment]
gemma should be supported since the last set of binary updates (0.11.x), so I'll close this issue now :)
