### ISSUE TITLE
.NET WinForms: Setup project: Cannot find Dependencies for .NET 8/6

### ISSUE THREAD

**Issue by SINAPSA-IC** [SciSharp/LLamaSharp#548]
Hello.

Visual Studio 2022 17.9.1 Community
.NET SDK 8.0.2, installed (from https://dotnet.microsoft.com/en-us/download/dotnet/8.0 ... SDK 8.0.201 ... Windows x64)
Both LLamaSharp & Backend.CPU: 0.10.0
WinForms application, on .NET 6.0 (the behavior below, including the Dependencies, is the same for: 1) .NET 8.0 and 2) Console App)
The application works as expected, so:

I've Added a Setup project to the solution, in order to deploy the working application to another computer which may not have .NET 8/6 on it.

In Solution Explorer:
- WinForms App:
-- Packages:
--- LLamaSharp (0.10.0)
--- LLamaSharp.Backend.CPU (0.10.0)

- Setup1:
-- View... File System... Application Folder:
--- Added: as Project Output: the Primary Output of the WinForms app
--- No Detected Dependencies were listed
--- Added: Assembly:  AppFolder\bin\Debug\net8.0-windows\LLamaSharp.dll
--- Detected Dependencies:
---- Microsoft. Extensions.DependencyInjection.Abstractions.dll
---- Microsoft. Extensions.Logging.Abstractions.dll

-> Rebuild Solution (2 projects: the WinForms App and Setup1):

in the Output Window:

------ Starting pre-build validation for project 'Setup1' ------ 
WARNING: Unable to find dependency 'SYSTEM.RUNTIME' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.LINQ.EXPRESSIONS' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.LINQ.EXPRESSIONS' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.COLLECTIONS.CONCURRENT' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.COLLECTIONS.CONCURRENT' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.INTEROPSERVICES' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.INTEROPSERVICES' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.LOADER' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.LOADER' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.COLLECTIONS' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.COLLECTIONS' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.COMPONENTMODEL' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.COMPONENTMODEL' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.IO.MEMORYMAPPEDFILES' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.IO.MEMORYMAPPEDFILES' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.LINQ' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.LINQ' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.CONSOLE' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.CONSOLE' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.COMPILERSERVICES.UNSAFE' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.COMPILERSERVICES.UNSAFE' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.MEMORY' (Signature='CC7B13FFCD2DDD51' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.MEMORY' (Signature='CC7B13FFCD2DDD51' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.INTEROPSERVICES' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.INTEROPSERVICES' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.COLLECTIONS' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.COLLECTIONS' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.TEXT.JSON' (Signature='CC7B13FFCD2DDD51' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.TEXT.JSON' (Signature='CC7B13FFCD2DDD51' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.COMPONENTMODEL.PRIMITIVES' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.COMPONENTMODEL.PRIMITIVES' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.INTRINSICS' (Signature='CC7B13FFCD2DDD51' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.INTRINSICS' (Signature='CC7B13FFCD2DDD51' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.INTEROPSERVICES.RUNTIMEINFORMATION' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.INTEROPSERVICES.RUNTIMEINFORMATION' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'LLamaSharp.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.INTEROPSERVICES' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.Logging.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME.INTEROPSERVICES' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.Logging.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.THREADING' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.Logging.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.THREADING' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.Logging.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.Logging.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.RUNTIME' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.Logging.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.COLLECTIONS' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.Logging.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.COLLECTIONS' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.Logging.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.MEMORY' (Signature='CC7B13FFCD2DDD51' Version='6.0.0.0') of assembly 'Microsoft.Extensions.Logging.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.MEMORY' (Signature='CC7B13FFCD2DDD51' Version='6.0.0.0') of assembly 'Microsoft.Extensions.Logging.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.COLLECTIONS.CONCURRENT' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.Logging.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.COLLECTIONS.CONCURRENT' (Signature='B03F5F7F11D50A3A' Version='6.0.0.0') of assembly 'Microsoft.Extensions.Logging.Abstractions.dll'
------ Pre-build validation for project 'Setup1' completed ------
------ Pre-build validation for project 'Setup1' completed ------
2>------ Rebuild All started: Project: Setup1, Configuration: Debug ------
2>------ Rebuild All started: Project: Setup1, Configuration: Debug ------
Building file 'H:\programs2022_desktop\Setup1\Debug\Setup1.msi'...
Building file 'H:\programs2022_desktop\Setup1\Debug\Setup1.msi'...
Building file 'H:\programs2022_desktop\Setup1\Debug\Setup1.msi'...
Building file 'H:\programs2022_desktop\Setup1\Debug\Setup1.msi'...
WARNING: Including primary output of project 'WinFormsApp1.csproj' with target framework '.NETCoreApp v6.0' may result in incomplete content. See here: https://go.microsoft.com/fwlink/?linkid=2112157
WARNING: Including primary output of project 'WinFormsApp1.csproj' with target framework '.NETCoreApp v6.0' may result in incomplete content. See here: https://go.microsoft.com/fwlink/?linkid=2112157
WARNING: Including primary output of project 'WinFormsApp1.csproj' with target framework '.NETCoreApp v6.0' may result in incomplete content. See here: https://go.microsoft.com/fwlink/?linkid=2112157
WARNING: Including primary output of project 'WinFormsApp1.csproj' with target framework '.NETCoreApp v6.0' may result in incomplete content. See here: https://go.microsoft.com/fwlink/?linkid=2112157
Packaging file 'WinFormsApp1.dll'...
Packaging file 'WinFormsApp1.dll'...
Packaging file 'WinFormsApp1.dll'...
Packaging file 'WinFormsApp1.dll'...
Packaging file 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'...
Packaging file 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'...
Packaging file 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'...
Packaging file 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'...
Packaging file 'WinFormsApp1.runtimeconfig.json'...
Packaging file 'WinFormsApp1.runtimeconfig.json'...
Packaging file 'WinFormsApp1.runtimeconfig.json'...
Packaging file 'WinFormsApp1.runtimeconfig.json'...
Packaging file 'LLamaSharp.dll'...
Packaging file 'LLamaSharp.dll'...
Packaging file 'LLamaSharp.dll'...
Packaging file 'LLamaSharp.dll'...
Packaging file 'Microsoft.Extensions.Logging.Abstractions.dll'...
Packaging file 'Microsoft.Extensions.Logging.Abstractions.dll'...
Packaging file 'Microsoft.Extensions.Logging.Abstractions.dll'...
Packaging file 'Microsoft.Extensions.Logging.Abstractions.dll'...
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

If the LLamaSharp.dll is Not added as Assembly/File, its two Dependencies also are not being added, and the Rebuild of the Setup package completes without /severe errors:

[...]
WARNING: Including primary output of project 'WinFormsApp1.csproj' with target framework '.NETCoreApp v8.0' may result in incomplete content. See here: https://go.microsoft.com/fwlink/?linkid=2112157
10:31:45:173	Packaging file 'WinFormsApp1.dll'...
10:31:45:182	Packaging file 'WinFormsApp1.runtimeconfig.json'...
10:31:45:496	========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

... incomplete indeed: in the folder where the App was installed there are these files only:
- WinFormsApp1.dll
- WinFormsApp1.runtimeconfig.json
(although the Properties of the App told it that it is a Windows Forms one, instead of a Class Library)

What could be done in this case? How to deploy the application? I think that the LLamaSharp.dll should be deployed along with the .exe, but its Dependencies via Abstractions cannot be resolved.
Looks like the Setup will not start, even if .NET 8/6 is present, and (probably normal) If LLamaSharp.dll is placed in the Application Folder -> the only DLLs are the two referring the Abstractions...

**Comment by AsakusaRinne** [comment]
Hi, will be building succeed if you remove LLamaSharp and add microsoft semantic-kernel as dependency for example? 

> I've Added a Setup project to the solution, in order to deploy the working application to another computer which may not have .NET 8/6 on it.

Sorry but I know little about the distribution of .NET applications. Could you please tell more about what the Setup project is?

**Comment by SINAPSA-IC** [comment]
Hello.

Thank you. 

Let's try it thatta way then.

All I do with LLamaSharp (regardless of its version) is in Microsoft Visual Studio 2022 Community >= 17.9.1

I have installed the MS Semantic Kernel as per the instructions here:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/README.md

1. open the Solution using LLamaSharp
2. (re)build the Solution in order to create the .exe or .dll
3. View... Solution Explorer... (Ctrl Alt L)
4. right-click on the name of Solution -> Add -> New Project... Setup Project: Create a Windows Installer project to which files can be added
5. right-click on the name of Setup project -> View -> File System
6. right-click on Application Folder -> Add -> Projct Output... Primary Output
7. in Solution Explorer, under the name of Setup Project, appears: "Detected Dependencies" and "Primsry output from [name of Solution]
8. The "Detected Dependencies" folder is empty
9. right-click again on "Application Folder" - to add LLamaSharp.dll
10. Add -> Assembly...
11. Browse... to file LLamaSharp.dll
12. I use the LLamaSharp.dll in [Solution name]\bin\Release\"net 8.0-windows"
13. Visual Studio crashes
14. restart it
15. rebuild the Solution using LLamaSharp
16. repeat steps 7 (add the Primary Output = no dependencies) to 11 (add LLamaSharp.dll)
17. in Solution Explorer, under the name of Setup Project, in the folder "Detected Dependencies" appear "Microsoft.Extensions.DependencyInjection.Abstractions.dll" and "Microsoft.Extensions.Logging.Abstractions.dll"
18. build the entire solution: the Solution using LLamaSharp.dll and the Setup project:
19. in Solution Explorer: righ-click on the name of the whole solution ("2 of 2 projects"): Rebuild Solution
20. in the Output window, the same announcements appear:
21. ------ Starting pre-build validation for project 'sinforma_setup' ------ 
WARNING: Unable to find dependency 'SYSTEM.COLLECTIONS' (Signature='B03F5F7F11D50A3A' Version='8.0.0.0') of assembly 'Microsoft.Extensions.Logging.Abstractions.dll'
WARNING: Unable to find dependency 'SYSTEM.THREADING' (Signature='B03F5F7F11D50A3A' Version='8.0.0.0') of assembly 'Microsoft.Extensions.Logging.Abstractions.dll'
WARNING: Unable 
[...]
Building file 'H:\... ...\sinforma_setup.msi'...
WARNING: Including primary output of project 'blabla.csproj' with target framework '.NETCoreApp v8.0' may result in incomplete content. See here: https://go.microsoft.com/fwlink/?linkid=2112157
Packaging file 'Microsoft.Extensions.Logging.Abstractions.dll'...
Packaging file 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'...
Packaging file 'sinforma.runtimeconfig.json'...
Packaging file 'LLamaSharp.dll'...
Packaging file 'blabla.dll'...
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

The .exe is not there. Nor the other expected Dependencies of Abstractions...

**Comment by SINAPSA-IC** [comment]
(sorry - the many Edits were mostly for misspelled words)

**Comment by SINAPSA-IC** [comment]
Now - adding the Microsoft.SemanticKernel.Abstractions.dll as an Assembly:

Solution Explorer -> File System -> Application Folder

right-click -> Add -> Assembly
Browse... to file 
C;\... ...\nuget\packages\microsoft.semantickernel.abstractions\1.5.0\lib\netstandard2.0
choose the file:
Microsoft.SemanticKernel.Abstractions.dll

This is being Added to the "Application FoldeR" along with 
- seemingly all its Dependencies
- which appear to be sufficient for the Setup Solution to be Built:
(although with Warnings that the files are under File Protection)

Packaging file 'netstandard.dll'...
Packaging file 'System.Security.SecureString.dll'...
Packaging file 'Microsoft.Extensions.Logging.Abstractions.dll'...
Packaging file 'Microsoft.SemanticKernel.Abstractions.dll'...
Packaging file 'System.Xml.XPath.XDocument.dll'...
Packaging file 'System.Runtime.InteropServices.RuntimeInformation.dll'...
Packaging file 'System.ValueTuple.dll'...
Packaging file 'System.Net.Http.dll'...
Packaging file 'System.Net.Sockets.dll'...
Packaging file 'Microsoft.Extensions.DependencyInjection.Abstractions.dll'...
Packaging file 'System.Runtime.Serialization.Primitives.dll'...
Packaging file 'System.Data.Common.dll'...
Packaging file 'sinforma.runtimeconfig.json'...
Packaging file 'System.Security.Cryptography.Algorithms.dll'...
Packaging file 'System.Threading.Overlapped.dll'...
Packaging file 'System.Diagnostics.StackTrace.dll'...
Packaging file 'System.IO.Compression.FileSystem.dll'...
Packaging file 'System.IO.Compression.dll'...
Packaging file 'LLamaSharp.dll'...
Packaging file 'System.Runtime.Serialization.Xml.dll'...
Packaging file 'sinforma.dll'...
Packaging file 'System.Diagnostics.Tracing.dll'...
Packaging file 'System.Globalization.Extensions.dll'...
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========

**Comment by SINAPSA-IC** [comment]
**The issue was SOLVED** this way:

Thank you! to [AsakusaRinne](https://github.com/AsakusaRinne)] here.

To create a Setup project resulting in a .msi file which can be used to install the (WinForms) App (onto another computer with .NET 8.0/6.0):

Visual Studio Community 2022 17.9.1:

1. install the Microsoft.SemanticKernel as indicated at:
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/README.md
2. build the Solution that is using LLamaSharp.dll
3. create a Setup Project ->
4. View -> File System
5. to the "Application Folder":
6. Add -> Assembly -> the EXECUTABLE file of the LLamaSharp solution: blabla.exe
7  Add -> Assembly: Browse... to the 
Microsoft.SemanticKernel.Abstractions.dll as an Assembly
(it usually is in the C:\Users\username\.nuget\packages\microsoft.semantickernel\1.5.0\lib\

then, possibly in:

\netstandard2.0\

as the file:
Microsoft.SemanticKernel.Abstractions.dll

8. the Dependencies of this^ .dll are being detected and Added to the "Application Folder" as well.
9. rebuild the entire Solution: the (WinForms) App and the Setup Project
10. run the .msi installer on the (other) computer
11. in the folder where it was installed, check on the presence of all packaged^ .dlls - they should be there
12. launch the App.exe - it should start

**Comment by AsakusaRinne** [comment]
Thank you for so much detailed information! I'll try to reproduce this issue.

Two more questions please. Which files should be existed if all things go well? And is console program able to reproduce it?

**Comment by AsakusaRinne** [comment]
There's a delay of message so plz ignore my last comment. Thank you for providing the solution!

**Comment by SINAPSA-IC** [comment]
All's well that ends well... Well... the "issue" remains with Documenting the creation of such a Setup file - candidly, I say that I was _very_ interested in this because I want to install such a conversation program in the workplace... kinda showoff, yep.

I've tried both with 
- WinForms App
-- a simple dialog with
--- one Button for Browsing for the .gguf file of the LLM of interest
--- one Label to show this filename
--- one Button for sending the Prompt to the LLM,
--- two TextBoxes - one for the Prompt, the other for the Response
--- a timer/30sec and a statusbar with a label that would show the datetime
--- the .exe for this should be around 100 KB

In this case, I expected that the Primary Output to be the .exe.
However, the Setup Project considered that the Primary Output was a DLL.

So, in order for the _necessary_ files (the exe and LLamaSharp.dll) to be deployed with the resulting .msi:
- added manually to the "Application Folder": the .exe of the WinForms App 
- added manually to the "Application Folder": LLamaSharp.dll
- added manually to the "Application Folder": Microsoft.SemanticKernel and the Microsoft.SemanticKernel.Abstractions
- added automatically to the "Application Folder", by VS2022: the DLLs of the Dependencies of .Abstractions, after adding the SemanticKernel^

The .msi will deply these files and the .exe should run.

- Console App
-- the process is the same as for a WinForms App.


Now then... you've deleted the comment... what was the second question? :)



I intend to write a tutorial of sorts about all this 
- in a PDF
- and as a post on Medium
I'll post the links here, so that you/the users do with it as you see fit.


Thank you heartil;y!

**Comment by SINAPSA-IC** [comment]
Strike that...

You might as well delete the posts above.

**It does not work.**

wtx

The Dependencies are packaged and deployed, but
The messages are still there. Didn't see them :(

Back to square 1.5
- only a part of Dependencies are resolved, 
- **not those to components of .NET**
![imgls1](https://github.com/SciSharp/LLamaSharp/assets/158754254/9e80b9dc-7c2e-4127-9ffd-9095ca38de08)

![imgls2](https://github.com/SciSharp/LLamaSharp/assets/158754254/7ee81a0b-7895-4c84-8b01-b0a24d2f8941)

**Comment by SINAPSA-IC** [comment]
The .exe 
- will open/run/launch when /double-clicked on the computer where it has been **built/installed**
- will open/run/launch when /double-clicked on the computer where it has been **built and deployed/installed**
- will not open/run/launch when /double-clicked on a computer where it has been **deployed/installed**

.NET 8 SDK is installed on both computers.

Beats me.

**Comment by SINAPSA-IC** [comment]
I've COPIED the contents of the bin/Release folder onto another computer
where the program WILL run.

Beats me a-gin.
![imgls3](https://github.com/SciSharp/LLamaSharp/assets/158754254/9fb5c4f6-b2c7-47d9-96fc-fd7b2d41c8c1)

**Comment by SINAPSA-IC** [comment]
I need /some fresh air.

Air Antarcica, or Mars even.


At least it works again.

I shall delete the steps above, about the deployment via setup program, and insert them below this post.

In Visual Studio:
- to the setup package in the "Application Folder":
-- aside from the .exe of the Application, the .dll named the same MUST be Added too
- the setup .msi 
-- will be built WITH THE SAME WARNINGS about the impossiblity to resolve dependencies to Collections, Json and the rest in .NET 8.0
-- but it will deploy the .dll along with the .exe, this DLL being essential for the .exe to run, Forrest, run.


So I guess this issue may be Closed a-gin.


This HAS TO be tested to deth, some feedback from the community would do a whole lotta good...

**Comment by AsakusaRinne** [comment]
It seems that we had misunderstandings at the beginning, sorry for the confusion. :)

Let's clear it together. You had a winform app depending on LLamaSharp and you find it unable to be distributed correctly because some files/dependencies are not dealt with correctly when building the project. 

> will the building succeed if you remove LLamaSharp and add microsoft semantic-kernel as dependency for example?

I meant that you could try building without LLamaSharp but with another arbitrary library to see if it's a problem due to LLamaSharp. Installing semantic-kernel is not expected to fix anything.

If it's indeed a problem related to LLamaSharp, then please put the log and output files list here, which will help us to fix the problem.

**Comment by SINAPSA-IC** [comment]
As far as I'm concerned, it is you! who provided the solution.

All's well that ends well... the "issue" remains with Documenting the creation of such a Setup file.

In order for an App which is using LLamaSharp to be packaged and deployed/installed on any computer with .NET 8.0/6.0, at this moment - it would be **useful** if results of tests by the community would be shown here - the steps to build such a setup .msi are:

In Visual Studio 2022 (Community  17.9.1)
- Build the App - as an EXE, presumably
- Add a Setup Project to its Solution
- wherein the Setup project:
-- to the "Application Folder":  add manually **LLamaSharp.dll** (it should be in the Release or the Debug folder of the program)
-- to the "Application Folder": **add manually the EXE of the program**
-- to the "Application Folder": **add manually the DLL with the same name as the EXE**
-- to the "Application Folder": **add manually: Microsoft.SemanticKernel** 
-- to the "Application Folder": **add manually: Microsoft.SemanticKernel.Abstractions**
-- to the "Application Folder", _added automatically by VS2022_: the DLLs of the Dependencies of .Abstractions, after adding the SemanticKernel^

The .msi will deploy these files and the .exe should run; repeat, 
- .NET 8.0/6.0 must exist on the computer
- the DLL named the same as the EXE must be in the folder with the EXE and the other DLLs-Dependencies.

Sheesh.


Thank you heartily!

**Comment by AsakusaRinne** [comment]
Though I'm still a bit confused by why adding semantic-kernel makes everything okay, I'm happy that your project finally works!

If there's any other related problem in the future, please feel free to reopen this issue or open a new issue. :)

**Comment by SINAPSA-IC** [comment]
It is possible, I daresay probable, that the program would be deployed as functional if someone, without installing the Semantic Kernel, only Adds to the setup project the EXE as an Assembly/File _along_ with the Primary Output which seems to be the DLL.

This is why some more testing is needed. Afterwards, a proper guide; not a statistics on 2 computers configured the same...

Perhaps someone will indeed run a test under these conditions:
- absence of Semantic Kernel
- to the setup package -> File System -> Add -> Assembly/File: the .exe of the program and the .dll both named the same
- build, deploy /somewhere, launch the .exe, see if it works

**Comment by SINAPSA-IC** [comment]
it works that^ way, too:
- in the setup project -> File System -> ONLY ADDED:
- LLamaSharp.dll
- programname.DLL
- programname.EXE
- Rebult the setup project
- installed on another computer
- launched the EXE, it worked
For what it's worth, an image with the contents of the folder where the program was installed:

![imgls4](https://github.com/SciSharp/LLamaSharp/assets/158754254/dcb7a1e6-0176-4654-b604-0a9a2fc50c9f)

**Comment by SINAPSA-IC** [comment]
Looks like the Problem may be very simple: the addition of the EXE to the setup package.

_Usually_, by Primary Output of a /WinForms application, VS means the EXE - not in this case, though, where it took the DLL as Primary Output (it may be a .NET 8 thing), whereas the EXE had to be added manually, although it is the sine-qua-non part of the plot.

More testing is still welcome; LLamaSharp programs will be deployed all around.
