### ISSUE TITLE
Can't find verbose to set it to false.

### ISSUE THREAD

**Issue by HikiWaltz** [SciSharp/LLamaSharp#554]
Very new here coming from python but needed true threads... lol
Grateful it exists

I can't find anywhere a way to set the loading verbosity of the model to false.
ModelParams don't have it, neither does LLamaWeights.

The Documentation only mentions it in llamamodel, that I assume was already removed(?), as it was said in the documentation itself that it would, in favor of llamaweights.

`string modelPath = "GGUF-Dolphin-Mistral-2.6-DPO-Laser-7B-Q8.gguf";

// Load a model
var parameters = new ModelParams(modelPath)
{
    ContextSize = 32768,
    GpuLayerCount = 33,
    Threads = 12,
    Seed = (uint)rnd.Next(1, 999999999),
    BatchSize = 512
};
var model = new LLamaWeights(parameters);

// Initialize a chat session
var context = model.CreateContext(parameters);
var ex = new InteractiveExecutor(context);
session = new ChatSession(ex);`

**Comment by SignalRT** [comment]
May be you are looking for:

`public NativeLibraryConfig WithLogs(bool enable = true)`

**Comment by HikiWaltz** [comment]
Sorry, but how/where would I add this?
Can't seem to find any reference to it on the documentation and no hints as to which parameters it needs to be instantiated.

**Comment by martindevans** [comment]
You use it like `NativeLibraryConfig.Instance.WithLogs(false)`.

However I think you're probably looking for something a little different. As I understand it in the Python wrapper setting `verbose=false` suppresses all of the log output from llama.cpp?

I think if you want something similar in LLamaSharp you'll need to hook a log callback. This is a function that gets called every time llama.cpp wants to log a message.

```csharp
NativeApi.llama_log_set((level, message) => {
    // Do whatever you want here
    Console.WriteLine(message);
});

**Comment by HikiWaltz** [comment]
Yeah.. In python, verbose=false on llm(...) will suppress everything.
Tbh, I dunno if I understand how to do what you've said... But I'll try it here.
For a threaded console app using LLama, it's kinda important to have a way to suppress it.
Thank you.
I'll try it and if it works I'll post it here and close the issue.

**Comment by HikiWaltz** [comment]
Well... It doesn't remove everything. Device and Capabilities identification are still present, but it's a lot lot less lines and manageable since I can clean the console after the models are loaded and no new log messages show up...

Thanks

> You use it like `NativeLibraryConfig.Instance.WithLogs(false)`.
> 
> However I think you're probably looking for something a little different. As I understand it in the Python wrapper setting `verbose=false` suppresses all of the log output from llama.cpp?
> 
> I think if you want something similar in LLamaSharp you'll need to hook a log callback. This is a function that gets called every time llama.cpp wants to log a message.
> 
> ```cs
> NativeApi.llama_log_set((level, message) => {
>     // Do whatever you want here
>     Console.WriteLine(message);
> });
> ```

**Comment by martindevans** [comment]
@HikiWaltz could you paste an example of exactly what is still printed? I'd like to fix that.

If it's coming from LLamaSharp we should provide a way to suppress it.

If it's coming from llama.cpp it's a bug on their side that the log hook doesn't catch it.

**Comment by HikiWaltz** [comment]
To suppress the loading I used:

`NativeApi.llama_log_set((level, message) => { return; });`

An then a Console.Clear() after loading the models.

What remains:

`ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA RTX A4500, compute capability 8.6, VMM: yes`

**Comment by martindevans** [comment]
putting 3 backticks around code will do it:

```language_name
code goes here
```

<img width="233" alt="firefox_2024-02-29_13-40-10" src="https://github.com/SciSharp/LLamaSharp/assets/177519/e204a7f8-d7c1-456f-9d57-ddaf193a0a0e">

**Comment by martindevans** [comment]
I've opened an issue about it on llama.cpp: https://github.com/ggerganov/llama.cpp/issues/5797
