### ISSUE TITLE
The document update is too old

### ISSUE THREAD

**Issue by lmxin123** [SciSharp/LLamaSharp#558]
https://scisharp.github.io
The document is still version 0.5. Do you have any update plans？

**Comment by martindevans** [comment]
Unfortunately our docs are quite out of date at the moment. There is an issue https://github.com/SciSharp/LLamaSharp/issues/267 open to update the docs, but someone needs to step up to do it :)

**Comment by AsakusaRinne** [comment]
Hi, the docs have been updated since v0.11.1. Please check it again. :)
