### ISSUE TITLE
Exception "EmbeddingMode must be true" after upgrading to v0.10.0

### ISSUE THREAD

**Issue by LSXAxeller** [SciSharp/LLamaSharp#579]
After upgrading packages from version 0.9.1 to version 0.10.0, when attempting to load the model using LLamaWeights.LoadFromFile, I encounter the exception EmbeddingMode must be true (Parameter 'params').

```
try
{
    var modelPath = $"PATH_TO_MODEL";
    GenerationModelParameters = new ModelParams(modelPath)
    {
        ContextSize = 4096,
        GpuLayerCount = AppConfig.Instance.Device == Device.GPU ? 41 : 0 // TODO: Automatically determine GPU layer count based on free GPU memory and layer size
    };
    GenerationModel = LLamaWeights.LoadFromFile(GenerationModelParameters);

    Extensions.Notify(new NotificationContent { Title = "Text Generation", Message = $"Text Generation Model loaded Successfully", Type = NotificationType.Information });

}
catch (Exception ex)
{
    Extensions.Notify(new NotificationContent { Title = "Text Generation", Message = $"Model Switching to {SelectedGenerationModel.Name} Failed, Exception: {ex.Message}", Type = NotificationType.Error });
}
```

**Comment by martindevans** [comment]
Can you post the full stack trace of the error? Thanks.

**Comment by LSXAxeller** [comment]
```
System.ArgumentException
  HResult=0x80070057
  Message=EmbeddingMode must be true (Parameter 'params')
  Source=LLamaSharp
  StackTrace:
   at LLama.LLamaEmbedder..ctor(LLamaWeights weights, IContextParams params, ILogger logger)
   at EGOIST.ViewModels.Pages.TextViewModel.<GenerationSwitchModels>b__52_0() in E:\Native\Projects\EGOIST\EGOIST\ViewModels\Pages\TextViewModel.cs:line 266
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

I figured it out. It seems that when I use GenerationModelEmbedder = new(GenerationModel, GenerationModelParameters);, it requires EmbeddingMode = true in GenerationModelParameters. This wasn't necessary in previous versions. Sorry, I'm not very familiar with Visual Studio and detailed stack traces yet.

**Comment by martindevans** [comment]
One of the changes in 0.10.0 was that the `LLamaEmbedder` requires `EmbeddingMode = true` set. previously it would modify your config to set it, which wouldn't always be what you wanted (e.g. if the config is shared, that might get enabled without you realising it). Sounds like you've bumped into that.

> how to use OpenCL backend

I'm not sure of the status, but I don't think OpenCL is available for LLamaSharp yet. Some initial work was done to add CLBLAST in 0.10.0, but (as far as I know) it's not shipped to nuget yet.

**Comment by martindevans** [comment]
Since you'vce figured out the problem I'll close this issue :)
