### ISSUE TITLE
No LLamaSharp backend was installed

### ISSUE THREAD

**Issue by blackcement** [SciSharp/LLamaSharp#58]
I have the same problem, can't figure out what I'm missing? Created a new project, 

![image](https://github.com/SciSharp/LLamaSharp/assets/61663301/ed6b341b-680e-434c-9315-ad47acbe4417)

`RuntimeError: The native library cannot be found. It could be one of the following reasons:

No LLamaSharp backend was installed. Please search LLamaSharp.Backend and install one of them.
You are using a device with only CPU but installed cuda backend. Please install cpu backend instead.
The backend is not compatible with your system cuda environment. Please check and fix it. If the environment is expected not to be changed, then consider build llama.cpp from source or submit an issue to LLamaSharp.
`
OS: Windows 10 (64 bit) 19044.1288
.NET 7.x
CUDA\v11.7

![image](https://github.com/SciSharp/LLamaSharp/assets/61663301/91f2a616-3a95-4440-b2f0-0e2daaff5630)

![image](https://github.com/SciSharp/LLamaSharp/assets/61663301/a74cedde-15f5-4598-9d64-c39da547a1d3)

![image](https://github.com/SciSharp/LLamaSharp/assets/61663301/96eb4784-2f49-4c29-a969-ad67d27ae6d8)

![image](https://github.com/SciSharp/LLamaSharp/assets/61663301/539e2e18-4caa-479b-9621-ef108e831ad3)

![image](https://github.com/SciSharp/LLamaSharp/assets/61663301/4b9fe401-19be-47ed-94bf-2037d515b925)

**Comment by TonySCruze** [comment]
I have this same issue with cuda 11.7 when attempting to use GPU backend. Cpu backend works fine. But no GPU backend work out the box for me. Might have to build from source and see if that works. If building from source work someone please ping me.

**Comment by ThomasVestergaard** [comment]
+1 on this.
Windows 11 Pro, 10.0.22621 Build 22621

<img width="646" alt="image" src="https://github.com/SciSharp/LLamaSharp/assets/3762409/5a018fea-206a-4290-9921-5e7ab57053cb">

<img width="1279" alt="image" src="https://github.com/SciSharp/LLamaSharp/assets/3762409/8cc28847-655c-450a-b694-85113abc841e">

**Comment by ThomasVestergaard** [comment]
I cloned the source and tested again, this error occurs when calling native llama. Happens on llama_empty_call().
So it's an upstream thing I suppose.

**Comment by martindevans** [comment]
I don't think it's an upstream thing. it usually indicates that either the dependencies don't exist (e.g. backends not installed), or you can't load them for some reason.

**Comment by ThomasVestergaard** [comment]
So I made it work by manually replacing the libllama.dll after I compiled my application.
Here's how to reproduce:

1. When you reference LLamaSharp and GPU/CPU nuget packages, a folder is created in the output directory containing libllama.dll. In my case it was here: \bin\Debug\net7.0\runtimes\win-x64\native\libllama.dll
2. After you have compiled you application, remove the libllama.dll file in this directory.
3. Clone the LlamaSharp repository and locate either libllama-cuda11.dll or libllama-cuda12.dll depending on your needs.
4. Copy one of the dll's into your output folder and name it libllama.dll
5. Start your compiled application via command line. If you run it via your IDE the libllama.dll file will be overriden by the one that does not work.

**Comment by ThomasVestergaard** [comment]
It seems someone on teh discord server also discovered this solution a few days ago.

**Comment by martindevans** [comment]
Hopefully [this PR](https://github.com/SciSharp/LLamaSharp/pull/65) (which will probably be in the next release) will fix this problem (at least for windows, someone needs to do a PR to extend it for Linux and MacOS). It has a [list of DLLs](https://github.com/SciSharp/LLamaSharp/blob/2013f9df045d104abcbc9723ffc36ef7df3ed365/LLama/Native/NativeApi.cs#L53) which it tries to load in order of priority (with CUDA at the top).

**Comment by RobertRappe** [comment]
I'm experiencing the same error but for the CPU backend as well, I've tried the prereleases as well and continue to get the "RuntimeError: The native library cannot be found." fail, I also tried to replace libllama.dll from a few sources but didn't have any success there either.

**Comment by GalactixGod** [comment]
I presume you are all compiling LlamaSharp right and having this issue.
Here's the steps that worked for me to resolve this matter

1. If you want compile llama.cpp -> rename the dll to llamalib.dll and put it in the runtimes folder in the LlamaSharp project
2. Compile your code -> llamasharp compiles successfully by using your new DLL.
3. Create your **new project** that will reference llamasharp and add a reference from your project to the LlamaSharp project.
4. Your project should compile properly assuming there's no other errors
5. At runtime you will get an error such as "no backend was found"
6. The problem is that llamalib.dll is not getting into YOUR output folder. LlamaLib.dll is being used by Llamasharp to compile but it's not included in the llamasharp output so you need to add llamalib.dll to your output folder.
7. Enjoy!

**Comment by martindevans** [comment]
> llama.cpp now uses GGUF and seems to break with the current version of LlamaSharp

Or you can use this branch #122 :)

**Comment by Arthur-Lee** [comment]
I have encountered the same issue. However, I have manually installed Cuda Toolkit for windows and build llamacpp from source, the dynamic library works fine, you can download from here https://developer.nvidia.com/cuda-downloads

After that, I use the packed dynamic library, it works like magic. So, I assume you may need to install the CUDA toolkit to resolve this error. Maybe just the minimal CUDA runtime is required, but I don't verify that.

**Comment by JeremyBickel** [comment]
This happened to me, and I had to install the nuget backend package and attach it to the LlamaSharp project. Then my project could make a project dependency on it, and it got past llama_empty_call().

**Comment by BLC3000** [comment]
Mine is hanging on llama_empty_call, and not giving any errors, it just hangs.  Mac os.

**Comment by BLC3000** [comment]
Got past that error by copying libllama.dylib and libllama.dll from the LLamaSharp/runtimes folder to my local /usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.11/ folder.

**Comment by nappa0326** [comment]
@BLC3000 I have same problem. I am currently unable to get LLamaSharp to work under MacOS. Can anyone give me a working sample and how to build it?

**Comment by mikey5656** [comment]
@BLC3000  Thank you, I tried your approach and it's already running on mac

**Comment by AsakusaRinne** [comment]
> @BLC3000 I have same problem. I am currently unable to get LLamaSharp to work on MacOS. Can anyone give me a working sample and how to build it?

Sorry for seeing it so late. Have you solved the problem? If not, we'd like to help you if you could provide some detailed informations. :)

**Comment by nappa0326** [comment]
@AsakusaRinne Thanks for your reply. The details of the situation are very simple: I have cloned and built LLamaSharp 0.6.0 on Intel Mac (Core i5-7360U) and am trying to run 'LLama.Examples', but an exception occurs immediately after execution. Does LLamaSharp not work on an iMac to begin with?
![2023-10-28 131437](https://github.com/SciSharp/LLamaSharp/assets/4612828/c59f4157-8a3c-4484-a747-09b7a0706eee)

**Comment by SignalRT** [comment]
@nappa0326, the MacOS binaries provided are for ARM architecture.

**Comment by nappa0326** [comment]
@SignalRT I understand. Should I assume that there won't be support for Intel-based Macs in the future?

**Comment by martindevans** [comment]
It would be possible to add support for intel Macs, using the feature selection stuff (which is currently in master, but unused) to decide which dylib to load.

As a shorter term workaround though, you should be able to compile Intel+Mac binaries yourself and use them. You just need to make sure you use _exactly_ the same commit version as LLamaSharp (see the "llama.cpp commit ID" [here](https://github.com/SciSharp/LLamaSharp#installation)).

**Comment by AsakusaRinne** [comment]
@martindevans As an extension of this topic, is `feature selection stuff` able to detect if there's openblas on the host to install corresponding binaries now?

**Comment by martindevans** [comment]
> is feature selection stuff able to detect if there's openblas on the host to install corresponding binaries now?

Not at the moment, but if someone can come up with an `is_openblas_installed()` method it could be integrated very easily.

**Comment by martindevans** [comment]
We're providing MacOS x86_64 binaries now, so this issue should be resolved :)
