### ISSUE TITLE
Streaming output does not support StreamingChatMessage Content

### ISSUE THREAD

**Issue by xuzeyu91** [SciSharp/LLamaSharp#584]
When I use the SK extension to load LLamaSharp again, StreamingChatMessage Content will prompt an unsupported exception, while I can use StreamingTextContent. But this is not very compatible with OpenAI and Azure OpenAI

**Comment by AsakusaRinne** [comment]
Hi, could you please provide a minimal example for us to reproduce it? Even if pseudo code will help a lot.

**Comment by xuzeyu91** [comment]
![e8453c91bff1e8e21e7f84b2b719d38](https://github.com/SciSharp/LLamaSharp/assets/26290929/d78dc26b-b4f8-4a1b-aaed-73801672e552)
These are two different issues, and I have now resolved them by not specifying the type
 _kernel.InvokeStreamingAsync(function: func, arguments: new KernelArguments() { ["input"] = msg });

**Comment by AsakusaRinne** [comment]
Close this issue as completed. Feel free to reopen it if any problem in the future.
