### ISSUE TITLE
Drastic CUDA compute speed drop in last version

### ISSUE THREAD

**Issue by zsogitbe** [SciSharp/LLamaSharp#601]
I have tested the last version and compared to a former version I was using the CUDA compute utilization dropped to around 25-30% (very slow). Before it was also not 100%, but around 80%. This is a problem. Is there somewhere a default parameter that you have changed? Can we set somewhere a parameter to get nearly 100% CUDA compute utilization?
Note: this problem is related to the C# code (using the same C++ dll).

**Comment by AsakusaRinne** [comment]
@martindevans For your attention here. I knew few about the changes in past two months. :)

**Comment by zsogitbe** [comment]
Rinne, About something else: Could you please make an experimental branch for me called 'exp_cscpp' and add llama.cpp as submodule in the 'llama.cpp' folder? I would like to start some experiments with one simple VS solution for both C++ and C# code. The aim is to have several Configurations for each needed setup (what is in the runtime folder now) and simply compile both C++ and C# code in one run.

**Comment by martindevans** [comment]
I'm not aware of anything that should have reduced CUDA utilisation.

Here's the complete changeset since 0.9.1: https://github.com/SciSharp/LLamaSharp/compare/0.9.1...v0.10.0, I'm having a look through it now.

**Comment by martindevans** [comment]
Possible relevant changes:
 - `ModelParams.SplitMode` is new (default to `None`, i.e. do not aplit across multiple GPUs)
 - `result.n_gpu_layers = @params.GpuLayerCount < 0 ? int.MaxValue : @params.GpuLayerCount;` has been added into `IModelParamsExtensions` (I can't see how this would slow anything down though).
 - `StatelessExecutor` is using `Decode` instead of `Eval`. Major change in how inference is done.

None of these seem likely to be guilty :/

**Comment by martindevans** [comment]
Have you tried the `master` branch btw? Would be good to know if it's still an issue there

**Comment by zsogitbe** [comment]
Yes, I will test it. At first site, you are clever because I think that it is the CPU threads what probably changed. Is it possible that it went to only 1 thread lately?

**Comment by zsogitbe** [comment]
I can think of two things:
- your suggestion of low number of CPU threads set somewhere. The question is where this is set and how to change it to have near 100% GPU utilization?
- or this code with batch size 1: _batch = new LLamaBatch(1);

**Comment by martindevans** [comment]
If you're testing on master comparing to 0.9.1 then there are a few more changes (https://github.com/SciSharp/LLamaSharp/compare/v0.10.0...master):

 - `DefragThreshold`, disabled by default so should be the same as before.
 - `LLamaContext.GenerationThreads`/`LLamaContext.BatchThreads` - there are just reading out a value that was there before. Worth checking them though to see if they're unexpectedly low.
 - `Eval` removed, all executors using `Decode`
 - `SafeLLamaContextHandle.GlobalInferenceLock` ensures there's only one inference going on at once.

> or this code with batch size 1

`LLamaBatch` doesn't take a constructor parameter any more, but when it did that just set some internal array sizes (capacity for simultaneous sequences) not the inference batch size.

**Comment by zsogitbe** [comment]
After hours testing the latest master branch code I have found the reason of the slow down with CUDA, but not the root cause in the code. Maybe you will have more success with my info:

Old code CUDA params (in my test example):
- llama_new_context_with_model:  CUDA0 compute buffer size =   250.01 MiB
- llama_new_context_with_model:  CUDA_Host compute buffer size =     8.00 MiB
- llama_new_context_with_model:  graph splits (measure): 3

Latest (master branch) code CUDA params:
- llama_new_context_with_model: CUDA0 compute buffer size =   478.50 MiB
- llama_new_context_with_model: CUDA_Host compute buffer size =   592.00 MiB
- llama_new_context_with_model: graph splits (measure): 66

The new code makes a much larger compute buffer and a much higher graph splits for some reason. This must be the reason for the slow down. We should find what new code causes this.

**Comment by martindevans** [comment]
That's a good catch. What model, parameters and hardware are you testing with?

From skimming through the code it seems like "Graph splits" is how many times the computation moves from one compute device to another. If you're testing in a machine with 1 CPU and 2 GPUs then 3 makes sense. Obviously 66 never makes sense (unless you have a lot of GPUs 🤣).

**Comment by zsogitbe** [comment]
I have found the problem. It was the C++ dll. I have used a few days newer C++ dll. When I use the dll from the distribution, then the problem disappears. This means that some problems are expected when upgrading to a next version of the C++ dll. They have changed how to calculate the split. Hopefully, it will just be a parameter which is not set.
