### ISSUE TITLE
Embedding recommended model

### ISSUE THREAD

**Issue by mphacker** [SciSharp/LLamaSharp#61]
Anyone have a suggestion for embedding models to use with LlamaSharp?  I have not had any luck getting any models to work.

**Comment by Oceania2018** [comment]
Is it what you want? 
It can be used to get embedding from LLM.
[GetEmbedding Example](https://github.com/SciSharp/LLamaSharp/blob/master/LLama.Examples/NewVersion/GetEmbeddings.cs)

**Comment by yakovw** [comment]
I don't understand what you mean, all the models I tried, GGML, they all worked so far

**Comment by mphacker** [comment]
Interesting. I have tried multiple models but I am not getting any results. I am using the code below and I end up with a zero length array.

` var embedder = new LLamaEmbedder(new ModelParams(embeddingModelPath));
            string text = "hello, LLM.";
            float[] embeddings = embedder.GetEmbeddings(text);

            embedder.Dispose();`

LLamaSharp 0.4.1-preview package

**Comment by mphacker** [comment]
BTW... I tried:  nous-hermes-13b.ggmlv3.q5_1.bin and wizardLM-7B.ggmlv3.q5_1.bin

**Comment by mphacker** [comment]
think I found the issue. I was using the CUDA 12 backend which you are not supporting yet in the preview. :(  Switched to CPU backend and I got results.   Sorry for the alarm.
