### ISSUE TITLE
Information on new important updates in llama.cpp

### ISSUE THREAD

**Issue by zsogitbe** [SciSharp/LLamaSharp#627]
There have been 3 important updates to the llama.cpp recently (a few days ago). One of them is the addition of pipeline parallelism (multi-threading) (https://github.com/ggerganov/llama.cpp/pull/6017). The other important update was the correction of the embeddings bug. And one more update to release all GPU memory (this was also a bug - memory was not released). Thank you [slaren](https://github.com/slaren)!

These are very important updates. Looking forward to the addition of the latest llama.cpp code to LLamaSharp.

**Comment by IntptrMax** [comment]
I have tested recently updated llama.cpp on llava, it can run quickly and can save at least 50% time on llava1.6, my GPU is 3070, and model is llava1.6 q4k.

Wish llama.cpp in LLamaSharp can be updated.

**Comment by martindevans** [comment]
See #662, that update should include these things.
