### ISSUE TITLE
LLava_shared.dll in LLamaSharp.Backend.Cuda12 is for CPU only

### ISSUE THREAD

**Issue by IntptrMax** [SciSharp/LLamaSharp#639]
The llava_shared.dll in  LLamaSharp.Backend.Cuda12 is only 850KB, the file size is much smaller than llava_shared.dll with cuda. It will take about 126000+ ms to embding an image. Take it to llava_shared.dll from llama.cpp release 2214, image embding time will be no more than 1000 ms. Will this can be updated in next LLamaSharp release?

[Current]
![image](https://github.com/SciSharp/LLamaSharp/assets/87850139/9a3c2a81-be9b-4458-9dd3-d2f713467f91)

[Dll replaced]
![image](https://github.com/SciSharp/LLamaSharp/assets/87850139/b1501826-5ca8-46f0-9afa-7aa56169186e)

**Comment by AsakusaRinne** [comment]
That's unexpected, we will add a patch release ASAP. @martindevans Could you please help with updating the `compile.yml` and triggering it?

**Comment by AsakusaRinne** [comment]
v0.11.2 has been released in #651, please take a try to see if this issue has been fixed.

**Comment by IntptrMax** [comment]
It works well and have a wonderful speed! Thank you!
