### ISSUE TITLE
Clip model from LLaVA is not using GPU, but LLaVA model is using GPU in the same piece of code.

### ISSUE THREAD

**Issue by dcostea** [SciSharp/LLamaSharp#650]
Congratulations for adding LLaVA support starting with version 0.11.1.
It works very well!

Still, clip model is very slow.
I have Cuda12 and llava-mistral model is using GPU, as expected, but the clip model is not, instead is using the CPU.

![image](https://github.com/SciSharp/LLamaSharp/assets/15055082/4cfec578-d747-4a1e-820e-8c828bed824e)

![image](https://github.com/SciSharp/LLamaSharp/assets/15055082/57d0fa89-eac3-449b-ab3d-763fe175151b)

 <PackageReference Include="LLamaSharp.Backend.Cuda12" Version="0.11.1" />
 
 NativeLibraryConfig.Instance
    .WithCuda(true)
    .WithLogs(true)
    .WithAvx(NativeLibraryConfig.AvxLevel.Avx512);
 
Should the clip model run on GPU as well?

**Comment by AsakusaRinne** [comment]
Thank you for reporting us for this problem! It's the same with #639, which is supposed to be fixed by #647. We will publish a patch release 0.11.2 soon.

**Comment by AsakusaRinne** [comment]
v0.11.2 has been released in https://github.com/SciSharp/LLamaSharp/pull/651, please take a try to see if this issue has been fixed. Thank you!

**Comment by Lyrcaxis** [comment]
> v0.11.2 has been released in #651, please take a try to see if this issue has been fixed. Thank you!

Perfect timing! Any ETAs on when it's gonna be on nuget?

**Comment by dcostea** [comment]
wow, look here, less than half of a second!
![image](https://github.com/SciSharp/LLamaSharp/assets/15055082/5b896997-e5cf-494d-ad91-1ac7ac0c281b)
isn't it beautiful?

Thank you!

**Comment by dcostea** [comment]
issue is fixed!
