### ISSUE TITLE
Flash Attention 2

### ISSUE THREAD

**Issue by yakovw** [SciSharp/LLamaSharp#66]
Flash Attention 2 is out, they say it saves half the time, when will it be here?
Thanks for everything

**Comment by martindevans** [comment]
Relevant upstream discussion: https://github.com/ggerganov/llama.cpp/discussions/2257

**Comment by yakovw** [comment]
I understand that it is a matter of time, we will wait patiently
Thank you

> Relevant upstream discussion: [ggerganov/llama.cpp#2257](https://github.com/ggerganov/llama.cpp/discussions/2257)
