### ISSUE TITLE
NativeLibraryConfiguration WithLogs 

### ISSUE THREAD

**Issue by xuzeyu91** [SciSharp/LLamaSharp#675]
In version 0.11.2, WithLogs is missing
NativeLibraryConfiguration
.Instance
.WithCuda (false);
.WithLogs (true);
How should I print logs to determine if I am using a GPU

**Comment by AsakusaRinne** [comment]
Please pass `LogLevel.Debug` to `WithLogs`.

**Comment by xuzeyu91** [comment]
Thank you, I have found a new way of writing
```
NativeLibraryConfig
   .Instance
   .WithCuda(false)
   .WithLogCallback((level, message) => {
       Console.WriteLine($"[llama {level}]: {message.TrimEnd('\n')}");
   });
```
