### ISSUE TITLE
LLAMA 3

### ISSUE THREAD

**Issue by tiger2014** [SciSharp/LLamaSharp#679]
Hi Team,

LLAMA 3 can be used in this frame?

Thanks

**Comment by KirillianAmu** [comment]
it does function right now, but in my experience rather poorly, likely due to the weird prompt formatting that llama 3 has.

**Comment by adammikulis** [comment]
If llama3 is being overly verbose, add "<|eot_id|>" to the AntiPrompts. I've had good results with it so far and it seems to have more personality than Mistral Instruct v0.2.

**Comment by imxcstar** [comment]
> If llama3 is being overly verbose, add "<|eot_id|>" to the AntiPrompts. I've had good results with it so far and it seems to have more personality than Mistral Instruct v0.2.

I added <|eot_id|>, but it seems to have no effect

**Comment by martindevans** [comment]
I'm not sure if our antiprompt detection will properly handle special tokens like that. I know there's special case handling for EOS in some places. That could be a good improvement to the antiprompt processing for someone to make.

**Comment by AsakusaRinne** [comment]
Hi, #708 has added an example of LLaMA3 chat session. I'll appreciate it if you would like to try it and report problem to us if any. To run it, please pull the latest code of master branch and run the example project. :)

**Comment by adammikulis** [comment]
Will [PR #6920 from llama.cpp](https://github.com/ggerganov/llama.cpp/pull/6920) resolve this issue?

**Comment by AsakusaRinne** [comment]
@adammikulis I'll update the native library binaries following https://github.com/ggerganov/llama.cpp/pull/6920. Besides you could also try the current master branch, which has already provided an example of LLaMA3.

**Comment by dlyz** [comment]
I think `x == EOS` should be replaced everywhere with a `llama_token_is_eog(x)` that should be true for all end-of-something tokens. Antiprompt for `<|eot_id|>` won't help cause special tokens are not rendered.

https://github.com/ggerganov/llama.cpp/pull/6745#issuecomment-2069181015

**Comment by AsakusaRinne** [comment]
>  I think x == EOS should be replaced everywhere with a llama_token_is_eog(x) that should be true for all end-of-something tokens. Antiprompt for <|eot_id|> won't help cause special tokens are not rendered.

That's right, we'll add such things soon. For now you could use "�" as anti-prompt as a temporary resolution.

**Comment by martindevans** [comment]
> I think x == EOS should be replaced everywhere with a llama_token_is_eog(x)

This has actually been done in PR #712 (along with updating the binaries).

**Comment by martindevans** [comment]
llama3 has been supported for a while, so I'll close this issue now.
