### ISSUE TITLE
How to rebuild LLamaSharp backends

### ISSUE THREAD

**Issue by kuan2019** [SciSharp/LLamaSharp#690]
Hello, 
   I have checked the entire project from this repository and searched for keywords on the internet but didn't find any results. Does there has any way to rebuild backends (e.g. LLamaSharp.Backend.Cpu) ?

**Comment by AsakusaRinne** [comment]
If what you are asking is to compile DLLs from llama.cpp source code, please refer to [this doc](https://scisharp.github.io/LLamaSharp/0.11.2/ContributingGuide/).

If you've already had the DLLs and want to build a nuget package, please refer to [LLamaSharp.Backend.Cpu.nuspec](https://github.com/SciSharp/LLamaSharp/blob/master/LLama/runtimes/build/LLamaSharp.Backend.Cpu.nuspec). With the following command you'll get a nuget package. Note that you should run it in its folder, or modify the paths in the nuspec file your self. For more information, please refer to [this ci script](https://github.com/SciSharp/LLamaSharp/blob/master/.github/prepare_release.sh).

```shell
$ nuget pack filename.nuspec
```

**Comment by martindevans** [comment]
For reference, the build script which is used to generated the binaries is [here](https://github.com/SciSharp/LLamaSharp/blob/master/.github/workflows/compile.yml). Every binary included in any of our backend packages is built with this action, you can see the complete history of runs [here](https://github.com/SciSharp/LLamaSharp/actions/workflows/compile.yml).

**Comment by martindevans** [comment]
I'll close this one now since the question was answered and there hasn't been any activity for a while.
