### ISSUE TITLE
[BUG]: DefragThreshold default is not matching llama.cpp and probably not intended

### ISSUE THREAD

**Issue by dlyz** [SciSharp/LLamaSharp#716]
### Description

`DefragThreshold` is 0 by default in LLamaSharp with the intent that it will disable defragmentation on the threshold excess.

https://github.com/SciSharp/LLamaSharp/blob/6bf010d719ec10c7b224d60deaf5b5c79a742a65/LLama/Abstractions/IContextParams.cs#L112

https://github.com/SciSharp/LLamaSharp/blob/6bf010d719ec10c7b224d60deaf5b5c79a742a65/LLama/Common/ModelParams.cs#L103

But actually it should be negative to disable this mechanics (-1). 0 means "do defrag when the smallest fragmentation discovered".

This may negatively (maybe sometimes positively) impact performance in some advanced cases, for example with batching.

See llama.cpp default https://github.com/ggerganov/llama.cpp/blob/3ab8b3a92ede46df88bc5a2dfca3777de4a2b2b6/llama.cpp#L11630

### Reproduction Steps

\-

### Environment & Configuration

\-

**Comment by martindevans** [comment]
Good catch! Would you be itnerested in putting together a PR to fix this?

The easiest fix would be to just add a default value of `-1`. I think a better fix would be to change `float DefragThreshold` to `float? DefragThreshold` and then to convert `null` to `-1` in [here](https://github.com/SciSharp/LLamaSharp/blob/6bf010d719ec10c7b224d60deaf5b5c79a742a65/LLama/Extensions/IContextParamsExtensions.cs#L42).

**Comment by Neilblaze** [comment]
@AsakusaRinne Is this up for grabs?

**Comment by martindevans** [comment]
Unless @dlyz is already working on it, I think it's open to whoever moves first :)

**Comment by dlyz** [comment]
Yeah, sorry, couldn't find time for it yet, maybe closer to the end of the week. @Neilblaze if you can do it earlier, you should definitely take it.

If we go with nullable `DefragThreshold`, we should probably make `Seed` nullable too, because 'no seed' constant is not obvious.

**Comment by Neilblaze** [comment]
> Yeah, sorry, couldn't find time for it yet, maybe closer to the end of the week. @Neilblaze if you can do it earlier, you should definitely take it.

Cool I'll try my best to raise a PR asap, but meanwhile, I'm waiting for this confirmation ↓

> If we go with nullable `DefragThreshold`, we should probably make `Seed` nullable too, because 'no seed' constant is not obvious. And in `LLamaContext.SetSeed` too.

Once @martindevans confirms, I can make the updates. Thanks!

**Comment by martindevans** [comment]
Making seed billable for the default is a good idea. Go for it @Neilblaze :)
