### ISSUE TITLE
How to better provide system information for LLMs

### ISSUE THREAD

**Issue by K1tiK4** [SciSharp/LLamaSharp#734]
### Description

How should I give system information to LLM so that it can use it when there is a question that requires this information?

**Comment by AsakusaRinne** [comment]
Hi, if you are saying `system prompt`, please use `ChatMessage` to add a message of role `System` to the chat session. If you want the LLM to take use of some external knowledge such as a PDF documentation, please use `LLamaSharp.kernel-memory`, which provides RAG abilities.

**Comment by K1tiK4** [comment]
Is it possible to implement ChatMessage in instructExecutor?

**Comment by AsakusaRinne** [comment]
Sorry for the late reply. Could you please give an example about how you want to use LLM? It's a bit confusing to me because I'm not sure whether "system information" refers to "system prompt" here.
