### ISSUE TITLE
LLAVA Configuration

### ISSUE THREAD

**Issue by hswlab** [SciSharp/LLamaSharp#737]
### Description

I have difficulties to figure out, how to correctly config the LLava example.

First I Initialized the backend with a path to libllama.dll and llava_shared.dll in 
`NativeLibraryConfig.Instance.WithLibrary(llamaPath, llavaPath);`

![image](https://github.com/SciSharp/LLamaSharp/assets/12501993/6401690c-0f37-47eb-835c-7182ed1b2a38)

Then I tried to Implement something like shown in [this example](https://github.com/SciSharp/LLamaSharp/blob/master/LLama.Examples/Examples/LlavaInteractiveModeExecute.cs). I don't understand where to find the suitable Models I need for 
```
string multiModalProj = UserSettings.GetMMProjPath();
string modelPath = UserSettings.GetModelPath();
```
![image](https://github.com/SciSharp/LLamaSharp/assets/12501993/97367509-045b-4854-8d4f-401e8fe2b3b8)

modelPath, I belive is the model, I can download [here](https://hf-mirror.com/Mozilla/llava-v1.5-7b-llamafile/resolve/main/llava-v1.5-7b-mmproj-Q4_0.gguf). But what is a clipModel, and where can I get it?

**Comment by SignalRT** [comment]
You can see in Llama.Unitest.csproj the URLs of the models used in the example and UnitTest:

 https://huggingface.co/cjpais/llava-1.6-mistral-7b-gguf/resolve/main/llava-v1.6-mistral-7b.Q3_K_XS.gguf
 https://huggingface.co/cjpais/llava-1.6-mistral-7b-gguf/resolve/main/mmproj-model-f16.gguf

You will have both files in any vision model.

**Comment by hswlab** [comment]
Ah, thank you. So both models can be found at Huggingface. That's something completely new to me, usually I'm using just a single model^^'

**Comment by SignalRT** [comment]
Yes, you should download both files from the model you choose to use. Normally you will have several quantized models and one projection model

Llava is using CLIP with an MML Projection (mmproj).

You can find the details in this paper:

https://arxiv.org/pdf/2310.03744

**Comment by AsakusaRinne** [comment]
Maybe some documentations are necessary. :D
