### ISSUE TITLE
[BUG]: When using the output IAsyncEnumerable<string> of session.ChatAsync() strings are not streamed into client

### ISSUE THREAD

**Issue by koureasstavros** [SciSharp/LLamaSharp#762]
### Description

I am using Microsoft HostedWebAssembly under .NET8, that means the solution has three projects, one client, one server and one shared. So client communicates to server though web apis. I have the following code:
```
public async static IAsyncEnumerable<string> ChatLocalAsync(Shared.Models.Application.ChatRequest chat)
{
    //CONFIGS
    string param_model_path = Parameters.model_language_local_path; //USED FOR CUSTOM MODEL PATH

    CancellationToken cancellationToken = new CancellationToken();
    CancellationTokenSource cancellationTokenSource = new CancellationTokenSource();
    cancellationToken = cancellationTokenSource.Token;

    var parameters = new ModelParams(param_model_path)
    {
        ContextSize = 4096, // The longest length of chat as memory.
        GpuLayerCount = 0 // How many layers to offload to GPU. Please adjust it according to your GPU memory.
    };

    if (model == null)
    { model = LLamaWeights.LoadFromFile(parameters); }
    if (context == null)
    { context = model.CreateContext(parameters); }

    var executor = new InteractiveExecutor(context);

    // Add chat histories as prompt to tell AI how to act.
    var chatHistory = new ChatHistory();
    chatHistory.AddMessage(AuthorRole.System, chat.context);
    chatHistory.AddMessage(AuthorRole.User, "Hello, I need your support.");
    chatHistory.AddMessage(AuthorRole.Assistant, "Hello, How may I help you today?");

    InferenceParams inferenceParams = new InferenceParams()
    {
        MaxTokens = 1024, // No more than 256 tokens should appear in answer. Remove it if antiprompt is enough for control.
        AntiPrompts = new List<string> { "User:" } // Stop generation once antiprompts appear.
    };

    ChatSession session = new(executor, chatHistory);
    Console.Write("The chat session has started.");

    await foreach (string? result in session.ChatAsync(new ChatHistory.Message(AuthorRole.User, chat.prompt), inferenceParams, cancellationToken))
    {
        if (result != null)
        { yield return result; }
    }
}
```

This result is being processed in razor component using this code:
```
CancellationToken cancellationToken = GetCancellationToken();
chatResponse.response = string.Empty;
var requestContent = new StringContent(System.Text.Json.JsonSerializer.Serialize(chatRequest), Encoding.UTF8, "application/json");
var requestMessage = new HttpRequestMessage(HttpMethod.Post, "api/chat/communicate_async")
{
    Content = requestContent
};
//requestMessage.Headers.Accept.Append(new MediaTypeWithQualityHeaderValue("application/stream+json"));
requestMessage.SetBrowserResponseStreamingEnabled(true); // Enable response streaming

var response = await Http.SendAsync(requestMessage, HttpCompletionOption.ResponseHeadersRead);
IAsyncEnumerable<string?> results = response.Content.ReadFromJsonAsAsyncEnumerable<string>();
await foreach (string? result in results)
{
    chatResponse.response += result;
    StateHasChanged();
}
```

But the client waits until the server function finish in order to present the results. Instead messages in server console seems that are written as streaming. I have tested the same with other LLM library and the streaming on client works, for example the following code from Azure.AI:
```
await foreach (StreamingChatCompletionsUpdate chatUpdate in client.GetChatCompletionsStreaming(completionsOptions, cancellationToken))
{
    string? result = chatUpdate.ContentUpdate;
    if (result != null)
    { yield return result; }
}
```

Any ideas?

### Reproduction Steps

Create a session and provide the LLM a context "You are an expert" and a prompt "Generate 100 random words"

### Environment & Configuration

- Operating system: Windows
- .NET runtime version: .NET8
- LLamaSharp version: 0.12.0
- CUDA version (if you are using cuda backend): No
- CPU & GPU device: CPU

**Comment by AsakusaRinne** [comment]
Hi, would you like to share a minimal HostedWebAssembly project? I'm not very familiar with the razor,  so it'll be great if I can have such an example to simply run it to reproduce this BUG.

**Comment by koureasstavros** [comment]
@AsakusaRinne, here is a Blazor Hosted WebAssembly Demo Repository

Under left sidebar there is a menu "Chat", this will navigate you to the chatting page
Button Communicate Async, will sent the context and prompt you have entered and will wait for response streaming
Button Communicate Test, will place a dummy context and prompt in order to debug faster each time you change code
Button Communicate Clear, will clear the response window of previous iteration with the model, so you can check the new result

Specs:
IDE: VS 2022
Platform: Windows
Framework: .NET8
Repository: https://github.com/koureasstavros/LLAMASharpBlazor

Let me know

**Comment by AsakusaRinne** [comment]
I've found a workaround for it.

1. Yield return the values in async mode [here](https://github.com/koureasstavros/LLAMASharpBlazor/blob/main/LLAmaSharp/Server/Services/Service_Chat.cs#L19).
2. Insert `await Task.Delay(TimeSpan.FromMilliseconds(1));` to [this loop](https://github.com/koureasstavros/LLAMASharpBlazor/blob/main/LLAmaSharp/Server/Controllers/Controller_Chat.cs#L33), just before the yield return.

It makes me very confused... I can't understand why sleeping for 1 ms saves me from this problem. I believe it's a .NET/ASP.NET issue instead of a LLamaSharp issue.

**Comment by koureasstavros** [comment]
Indeed it works, I will try to identify why this is happening, many thanks.

**Comment by koureasstavros** [comment]
I will close this issue for now.
