### ISSUE TITLE
Phi-3-medium-128k-instruct - error due to tensor shape expected 245, got 243

### ISSUE THREAD

**Issue by koureasstavros** [SciSharp/LLamaSharp#765]
### Background & Description

Using LLamaSharp and loading a 128K instruct model like Phi-3-medium-128k-instruct.gguf it throws an error
`llama_model_load: error loading model: done_getting_tensors: wrong number of tensors; expected 245, got 243`

According to this issue from llama.cpp https://github.com/ggerganov/llama.cpp/issues/7478 this added recently so I suppose if lama.cpp is updated in this library it should be fixed.

### API & Usage

Use 128K instruct models

### How to implement

Update lama.cpp library

**Comment by martindevans** [comment]
These new binaries have been released, so I'll close this issue now. If it's still a problem please don't hesitate to reopen :)
