### ISSUE TITLE
Unable to Utilize Full CPU Capacity During Inference

### ISSUE THREAD

**Issue by LSXAxeller** [SciSharp/LLamaSharp#784]
### Description

I am experiencing an issue where the CPU usage does not exceed 65% when performing inference tasks using the Inference and InferenceConcurrent methods in my application. Despite trying different approaches such as await foreach, Parallel.ForEach, and a custom dataflow library (TBL), the CPU usage remains limited. I am unsure if this limitation is due to LLamaSharp's InferAsync method, llama.cpp constraints, or if there is an issue with my implementation.

## Code Sample
```
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Threading.Tasks.Dataflow;
using EGOIST.Domain.Entities;
using EGOIST.Domain.Interfaces;
using LLama;
using LLama.Abstractions;
using LLama.Common;
using static LLama.InteractiveExecutor;

namespace EGOIST.Application.Inference.Text;

public class InferenceService(ILLamaExecutor inference) : IInference
{
    public void Dispose()
    {
        switch (inference)
        {
            case StatefulExecutorBase statefulExecutor:
                statefulExecutor.Context.Dispose();
                statefulExecutor.ClipModel?.Dispose();
                break;
            case StatelessExecutor statelessExecutor:
                statelessExecutor.Context.Dispose();
                statelessExecutor.ClipModel?.Dispose();
                break;
        }
    }

    public IAsyncEnumerable<T> Inference<T>(string prompt, IEnumerable<T> blacklist, TextGenerationParameters parameters, CancellationToken cancellationToken)
    {
        var messageParams = new InferenceParams()
        {
            MaxTokens = parameters.MaxTokens,
            Temperature = parameters.Randomness,
            TopP = parameters.RandomnessBooster,
            TopK = (int)(parameters.OptimalProbability * 100),
            FrequencyPenalty = parameters.FrequencyPenalty,
            AntiPrompts = (IReadOnlyList<string>)blacklist
        };

        return (IAsyncEnumerable<T>)inference.InferAsync(prompt, messageParams, cancellationToken);
    }

    public async IAsyncEnumerable<T> InferenceConcurrent<T>(string prompt, IEnumerable<T> blacklist, TextGenerationParameters parameters, [EnumeratorCancellation] CancellationToken cancellationToken)
    {
        var messageParams = new InferenceParams()
        {
            MaxTokens = parameters.MaxTokens,
            Temperature = parameters.Randomness,
            TopP = parameters.RandomnessBooster,
            TopK = (int)(parameters.OptimalProbability * 100),
            FrequencyPenalty = parameters.FrequencyPenalty,
            AntiPrompts = (IReadOnlyList<string>)blacklist
        };

        Debug.WriteLine($"Inference Concurrent: {prompt}");
        
        var tokens = (IAsyncEnumerable<T>)inference.InferAsync(prompt, messageParams, cancellationToken);

        var bufferBlock = new BufferBlock<T>(new DataflowBlockOptions { CancellationToken = cancellationToken });

        var actionBlock = new ActionBlock<T>(async token =>
        {
            Debug.WriteLine("Inference Concurrent 02: ActionBlock Processing Token");

            if (blacklist.Any(x => token!.ToString()!.Contains(x?.ToString()!, StringComparison.CurrentCultureIgnoreCase)))
            {
                Debug.WriteLine($"FILTERED: {token}");
                await bufferBlock.SendAsync((T)(object)"FILTERING MECHANISM TRIGGERED", cancellationToken);
                bufferBlock.Complete();
                cancellationToken.ThrowIfCancellationRequested();
            }
            else
            {
                Debug.WriteLine($"PROCESSED: {token}");
                await bufferBlock.SendAsync(token, cancellationToken);
            }
        }, new ExecutionDataflowBlockOptions { MaxDegreeOfParallelism = DataflowBlockOptions.Unbounded, CancellationToken = cancellationToken });

        var linkOptions = new DataflowLinkOptions { PropagateCompletion = true };
        bufferBlock.LinkTo(actionBlock, linkOptions);

        await foreach (var token in tokens.WithCancellation(cancellationToken))
        {
            Debug.WriteLine($"INFERRED: {token}");
            await actionBlock.SendAsync(token, cancellationToken);
        }

        actionBlock.Complete();
        await actionBlock.Completion;

        bufferBlock.Complete();

        while (await bufferBlock.OutputAvailableAsync(cancellationToken))
        {
            Debug.WriteLine("BufferBlock Output Available");
            var processedToken = await bufferBlock.ReceiveAsync(cancellationToken);
            yield return processedToken;
        }

        Debug.WriteLine("Inference Concurrent 06: BufferBlock Disposed");
    }

    public Task<bool> IsFirstRun(string type)
    {
        if (type == nameof(StatefulExecutorBase) && inference is StatefulExecutorBase executer)
            return Task.FromResult(((InteractiveExecutorState)executer.GetStateData()).IsPromptRun);

        return Task.FromResult(false);
    }
}
```

## Screenshots
**Inference Method**
![Screenshot 2024-06-04 162358 - INFERENCE](https://github.com/SciSharp/LLamaSharp/assets/56027532/a839c231-67b2-4a97-a3f4-f068491bb2c0)

**InferenceConcurrent Method**
![Screenshot 2024-06-04 162722 - INFERENCE CONCURRENT](https://github.com/SciSharp/LLamaSharp/assets/56027532/6861f5af-3461-49f8-a89d-b1f937888da3)

**Comment by martindevans** [comment]
> Despite trying different approaches such as await foreach, Parallel.ForEach, and a custom dataflow library (TBL)

In general there's not much point in trying to parallelise LLamaSharp. llama.cpp is already internally parallel and will try to use however many threads you have specified in [ModelParams](https://github.com/SciSharp/LLamaSharp/blob/master/LLama/Common/ModelParams.cs#L49) to serve a single request as quickly as possible. Tuning that threads number can help squeeze a little more performance out (just try every value from 1 to CoreCount and see what's fastest).

However, Language models are usually **memory bandwidth** bound, i.e. the main constraint isn't how much work the CPU can do, but rather how fast it can load data from main memory. That would probably show up in task manager as low utilisation (exactly like you're screenshots).

For comparison try this same model but with 16 bit weights weights (or whatever the largest is you can fit in memory) and with 2 bit weights. If memory bandwidth is your limit then the smaller weights should be faster (and show more processor utilisation) because the balance will shift from loading weights into memory, towards computing results with those weights.

**Comment by LSXAxeller** [comment]
> However, Language models are usually **memory bandwidth** bound, i.e. the main constraint isn't how much work the CPU can do, but rather how fast it can load data from main memory. That would probably show up in task manager as low utilisation (exactly like you're screenshots).
> 
> For comparison try this same model but with 16 bit weights weights (or whatever the largest is you can fit in memory) and with 2 bit weights. If memory bandwidth is your limit then the smaller weights should be faster (and show more processor utilisation) because the balance will shift from loading weights into memory, towards computing results with those weights.

Since I am using 16GB RAM, I am limited to Q5_K_M models as the largest. I tried using a smaller IQ2_XS model `Kunoichi-DPO-v2-7B-IQ2_XS` but I am still limited to a maximum of 55% CPU usage. You may be right that this is a memory issue, as my RAM speed is 2666MHz, and I didn't notice such issues when I was using the GPU.
