### ISSUE TITLE
Cannot figure out how to switch backend to OpenCL 

### ISSUE THREAD

**Issue by tsorman** [SciSharp/LLamaSharp#793]
### Description

I am writing an application and I want to have it run on both NVidia and AMD GPUs depending on the machine with the option to run on the CPU is the user wishes so..

I have loaded the Nuget packages for all the backends:
CPU,
CUDA11,
CUDA12,
OPENCL

So far I have managed to switch between CUDA and CPU using the 
NativeLibraryConfig.All.WithCuda(false); and NativeLibraryConfig.All.WithCuda(true); on an NVIDIA machine. 
When I am trying to run the same build on a machine that has and AMD GPU I only get the CPU to work

I have tried the following if there is an AMD card detected.
Set NativeLibraryConfig.All.WithCuda(false); uses the CPU
NativeLibraryConfig.All.WithCuda(true); uses the CPU
Did not used any of the calls above and still uses the CPU 

I went through the available calls but I could not see anything referring to OpenCL or clblast so I used the following call with the same result
NativeLibraryConfig.All.WithLibrary(<path to cblast llama dll>, path to cblast llava dll);

When I am making a build with the OpenCL nuget package only then I can see that the AMD GPU is being used and I can see that OpenCL is mentioned in the console output.

I am not sure if I am missing anything so any help would be appreciated.
Thanks in advance.

**Comment by martindevans** [comment]
Support for the OpenCL backend will be dropped in the next update, see here: https://github.com/SciSharp/LLamaSharp/pull/782

**Comment by tsorman** [comment]
@martindevans 
Thanks a lot for the reply.
I am looking forward for the next update.

**Comment by martindevans** [comment]
I'll close this one now, since I think the question has been answered :)
