### ISSUE TITLE
first token must be BOS

### ISSUE THREAD

**Issue by bbzkfmzyjtbf** [SciSharp/LLamaSharp#8]
Hi, 
Thank you, this project is amazing

At some point I got this error

> llama_eval_internal: first token must be BOS
llama_eval: failed to eval

Which throw this exception, from https://github.com/SciSharp/LLamaSharp/blob/master/LLama/Logger.cs#L6

> System.IO.FileNotFoundException: 'Could not load file or assembly 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'. The system cannot find the file specified.'

Note I compiled LLamaSharp from master as I needed the latest version to support the latest GGML

Regards

**Comment by AsakusaRinne** [comment]
Hi, thank you for telling us that! It seems to be caused by that the latest llama.cpp always requires BOS. I've made a possible fix in the latest commit. If the error still appears, could you please provide some steps to reproduce it?

**Comment by AsakusaRinne** [comment]
I tried it with master branch. Though I couldn't reproduce the same BUG, there were indeed some strange behaviors. I've fixed them in v0.2.3. Could you please update and have another try?

**Comment by bbzkfmzyjtbf** [comment]
Definitely better, I haven't been able to reproduce the issue

Thank you again for your work
