### ISSUE TITLE
[BUG]: Bad Typo in LLama/Extensions/IContextParamsExtensions.cs ?

### ISSUE THREAD

**Issue by SerialKicked** [SciSharp/LLamaSharp#805]
### Description

While i was looking around the code trying to figure a few issues compared to base LLama.cpp (memory consumption and repetition penalty doing weird things), I found this:

https://github.com/SciSharp/LLamaSharp/blob/c1302ef89f8f9f4c604718a631253ed06ac9b677/LLama/Extensions/IContextParamsExtensions.cs#L50-L51

param.TypeV and param.TypeK are both assigned to result.type_k

I'm not exactly an expert in LLama.cpp / GGUF architecture, but it seems there's a mix-up.

### Reproduction Steps

N/A

### Environment & Configuration

- Operating system: Win11
- .NET runtime version: 8.0
- LLamaSharp version: 0.13
- CUDA version (if you are using cuda backend): 12
- CPU & GPU device: RTX3060 12GB

**Comment by martindevans** [comment]
That's definitely a bug! If you'd like to make a PR to fix it that would be appreciated :)

**Comment by SerialKicked** [comment]
Sure thing, if you can wait until this week-end (otherwise, feel free to change the line, I won't mind.)
