### ISSUE TITLE
[BUG]: llama_encode has no implementation

### ISSUE THREAD

**Issue by taotaow** [SciSharp/LLamaSharp#863]
### Description

Could not load type 'LLama.Native.SafeLLamaContextHandle' from assembly 'LLamaSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because the method 'llama_encode' has no implementation (no RVA).,stack:   at LLama.LLamaContext..ctor(LLamaWeights model, IContextParams params, ILogger logger)
   at LLama.StatelessExecutor..ctor(LLamaWeights weights, IContextParams params, ILogger logger)

### Reproduction Steps

LLama.Native.SafeLLamaContextHandle class
**private static extern int llama_encode(SafeLLamaContextHandle ctx, LLamaNativeBatch batch);**
no DllImport like other extern methods

### Environment & Configuration

- Operating system: win
- .NET runtime version: 6.0
- LLamaSharp version:0.14.0

**Comment by martindevans** [comment]
You're right that `llama_encode` is missing a DllImport attribute! I'll fix that now.

What did you do to trigger this exception though? I've been using 0.14.0 in my own projects without any issues.

**Comment by martindevans** [comment]
I've merged #864 which should fix the issue. I'd still like to know more about what exactly triggered it for you though, just in case there's a deeper issue.

**Comment by taotaow** [comment]
//gguf compilcated converted from https://huggingface.co/alibaba-pai/pai-bloom-1b1-text2prompt-sd-v2
var modelPath = "ggml-model-Q4_K_M.gguf");
var parameters = new ModelParams(modelPath)
    {
        ContextSize = 256,
    };
var modelWeight = LLamaWeights.LoadFromFile(parameters);
//throw exception,version 0.13.0 is ok
var statelessExecutor = new StatelessExecutor(modelWeight, parameters,NullLogger.Instance);

**Comment by taotaow** [comment]
llamasharp 0.15.0 had solved this problem,thank you

**Comment by taotaow** [comment]
llamasharp 0.15.0 had solved this problem,thank you
