### ISSUE TITLE
[BUG]: ChatHistory and kv-cache in unsync (Possible MemLeak)

### ISSUE THREAD

**Issue by TheFrieber** [SciSharp/LLamaSharp#867]
### Description

You can change and edit messages like you want in `ChatHistory` or `ChatSession`, but that's worthless as the AI will not pick that up correctly. 
Simply sayd, there is something Duplicated in the context. When editing something in `_session.History.Messages` e.g the Content and then using `_context.NativeHandle.KvCacheUpdate();` to "apply" it:
It'll work, the change is visible, but the stuff before edit still exists:
Before Edit:
![image](https://github.com/user-attachments/assets/754b2afe-a848-4013-be27-cf2dd5e76b2d)
After Edit (Changed Username):
![image](https://github.com/user-attachments/assets/18209634-ffb1-4b63-9044-0b20b596dae9)
The Issue: + The printed Json is not in sync with the context
![image](https://github.com/user-attachments/assets/8c6547a5-6566-4a3f-b4b4-b9ab8f2f009a)

### Reproduction Steps

[...]
```
var realOldMessage = _session.History.Messages.FirstOrDefault(m => m.Content == oldMessage.Text);
realoldMessage.Content = newText;
Console.WriteLine(_chatHistory.ToJson());
```
Before Generation:
`_context.NativeHandle.KvCacheUpdate();`

Generate.
And then Desaster.

### Environment & Configuration

- Operating system: Windows 10
- .NET runtime version: .NET 8.0
- LLamaSharp version: 0.14.0
- CUDA version (if you are using cuda backend): Cuda12
- CPU & GPU device: Ryzen 5 2600 & Rtx 4070

### Known Workarounds

None.

**Comment by martindevans** [comment]
> `_context.NativeHandle.KvCacheUpdate();`

This only applies the results of other operations that have been queued up, and is usually handled automatically by llama.cpp. It's _very_ rare that you need to call it yourself.

I'm not very familiar with `ChatHistory`/`ChatSession`, but as far as I'm aware they don't really support editing the context like this.
