### ISSUE TITLE
[BUG]: Vulkan - bad output after a while

### ISSUE THREAD

**Issue by DGdev91** [SciSharp/LLamaSharp#868]
### Description

Hi everyone, i noticed something wierd with the new Vulkan backend.

It seems to run fine at first, but then it starts to generate random stuff.
Last time i tried it was wiith version 0.10.0 and OpenCL backend, worked fine. Of course i tried also the cpu backend on the latest version, and worked fine too.
I tried also to run llama.cpp with vulkan and worked fine

To test it quickly, i just created a simple .net 8 console application, filled it with the example code from the quickstart, and then added the nuget package reference in the csproj

Here's an example:
![Screenshot 2024-07-25 191118](https://github.com/user-attachments/assets/62c65add-762b-4baa-9ac0-8d0120f2ab40)

While this is with the CPU backend
![Screenshot 2024-07-25 191531](https://github.com/user-attachments/assets/b458f2f6-419b-409d-9a9e-33f7b7a334d5)

### Reproduction Steps

- Create a new .net 8 console project
- Copy the example from the quickstart (https://scisharp.github.io/LLamaSharp/0.14.0/QuickStart/) into Program.cs
- Edit @"<Your Model Path>" with the path to a gguf model (i used https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/blob/main/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf)
- Add this to the .csproj file:
- `<ItemGroup>
   <PackageReference Include="LLamaSharp" Version="0.14.0" />
   <PackageReference Include="LLamaSharp.Backend.Vulkan" Version="0.14.0" />
 </ItemGroup>`
- Launch the program and make some questions until it breaks

### Environment & Configuration

- Operating system: Windows 11 / ArchLinux
- .NET runtime version: 8
- LLamaSharp version: 
- CUDA version (if you are using cuda backend): None - AMD GPU + Vulkan
- CPU & GPU device: AMD Ryzen 7 3800x / AMD RX 7900XT

**Comment by m0nsky** [comment]
Thanks for the report. I think this is the same bug as seen [here](https://github.com/ggerganov/llama.cpp/issues/8092), which was fixed in [this PR](https://github.com/ggerganov/llama.cpp/pull/8479). The PR was merged into llama.cpp master on July 15th, only 4 days after the latest LLaamSharp binary update, so it should land in the next one.

**Comment by m0nsky** [comment]
@DGdev91 a new LLamaSharp release is out now, could you test this again?

**Comment by DGdev91** [comment]
> @DGdev91 a new LLamaSharp release is out now, could you test this again?

Yep, seems like it's working fine now. Closing the issue.
