### ISSUE TITLE
llamasharp provider for langchain.net is outdated

### ISSUE THREAD

**Issue by markat1** [SciSharp/LLamaSharp#882]
### Description

I asked langchain.net about llamasharp integration and they told me it hasn't been updated in a while -  [se here](https://github.com/tryAGI/LangChain/discussions/410#discussioncomment-10198082)

**Comment by markat1** [comment]
It might also be outdated for kernel memory as well?

**Comment by HavenDV** [comment]
I checked and it works, so I don't think any action is required.
