### ISSUE TITLE
[BUG]: fatal error using gemma-2-2b-it

### ISSUE THREAD

**Issue by newsletternewsletter** [SciSharp/LLamaSharp#892]
### Description

Using gemma-2-2b-it-GGUF (e.g. bartowski/gemma-2-2b-it-GGUF, Q6_K) in the InstructModeExecute example, the following fatal error occurs and the process dies:
`D:\a\LLamaSharp\LLamaSharp\src\llama.cpp:11741: fatal error`

The model runs fine in llama.cpp b3506 and this error did not happen LLamaSharp 0.14.0.

full logs attached: [logs.txt](https://github.com/user-attachments/files/16486334/logs.txt)

### Reproduction Steps

Load gemma-2-2b-it-GGUF mentioned above in the example InstructModeExecute.

### Environment & Configuration

- Operating system: Windows
- .NET runtime version: dotnet 8.0
- LLamaSharp version: 0.15.0
- CPU device: Intel

### Known Workarounds

unknown

**Comment by newsletternewsletter** [comment]
I found a workaround by replacing the native llama.cpp DLLs (CPU) from the LLaMaSharp 0.15.0 NuGet package with the latest llama.cpp DLLs (e. g. llama-b3565-bin-win-avx2-x64).

It is most likely a bug of the native DLLs in the LLaMaSharp 0.15.0 NuGet. Using more recent version works.

**Comment by martindevans** [comment]
Just a note that in general using binaries from the wrong version of llama.cpp is _not_ expected to work! There are frequent breaking changes in the c-api that might lead to crashes (if you're lucky) or just incorrect behavior.

**Comment by newsletternewsletter** [comment]
It's fixed in the latest release 0.16.0.
