### ISSUE TITLE
Integrate the semantic kernel via API

### ISSUE THREAD

**Issue by geffzhang** [SciSharp/LLamaSharp#9]
The [semantic kernel](https://github.com/microsoft/semantic-kernel) provides a very good infrastructure for integrating LLM, developing a connector package to integrate into the semantic kernel

**Comment by AsakusaRinne** [comment]
> You can encapsulate a connector package here, similar to https://github.com/microsoft/semantic-kernel/tree/main/dotnet/src/Connectors/Connectors.AI.HuggingFace . This way we can iterate freely

Thank you. I've opened an issue in `semantic-kernel` to ask if the integration could be added to the repo (I'll work for it). I'll made a package ourselves if the proposal is not supported.

**Comment by KKD4Soei** [comment]
请问是否有量化成功的经验，ggml-vic13b-q5_1.bin 模型本地量化时失败了。
![image](https://github.com/SciSharp/LLamaSharp/assets/58964439/0b9dabd0-6400-4beb-bddc-0c711390b957)

**Comment by geffzhang** [comment]
use LLamaSharp to implement the Completion and Embedding interfaces of the semantic kernel
https://github.com/xbotter/semantic-kernel-LLamaSharp

**Comment by AsakusaRinne** [comment]
> 请问是否有量化成功的经验，ggml-vic13b-q5_1.bin 模型本地量化时失败了。 ![image](https://user-images.githubusercontent.com/58964439/241667769-0b9dabd0-6400-4beb-bddc-0c711390b957.png)

q5_1已经是量化过后的了，可以试一下量化fp32或者fp16模型，或者切换一下LLamaSharp的版本
