### ISSUE TITLE
[BUG]: gemma-2-9b-it-GGUF - error loading model

### ISSUE THREAD

**Issue by nicholusi2021** [SciSharp/LLamaSharp#901]
### Description

I've been using gemma-2-9b-it-GGUF in LM studio and it's working a lot better for me than Meta-Llama-3-8B-Instruct-GGUF.  I really like it but I'm getting this error when I try to use it in LLamaSharp:
 
error loading model: error loading model architecture: unknown model architecture: 'gemma2' 

I thought I had read that LLamaSharp now supports gemma2?  I'm able to use LLamaSharp with Meta-Llama-3-8B-Instruct-GGUF just fine.  Is it not supported yet, or maybe the model has an issue?

Thanks!

### Reproduction Steps

To reproduce the error, try using  gemma-2-9b-it-GGUF with LLamaSharp.

### Environment & Configuration

- Operating system:  Windows 11
- .NET runtime version:  .NET 8.0
- LLamaSharp version:  0.15.0
- CUDA version (if you are using cuda backend):  N/A CPU
- CPU & GPU device:  CPU

**Comment by aezendc** [comment]
I am having the same issue.

**Comment by martindevans** [comment]
I just tested `gemma-2-9b-it-Q4_K_M` and it works fine for me in one of the examples. Can you provide any more details about the error?

**Comment by nicholusi2021** [comment]
hmmm, well I had downloaded the model manually from HuggingFace, but I think it was a bad model.  When I just downloaded the LM Studio Community version, it worked for me.  So I can confirm it works as long as it's a good model.
