### ISSUE TITLE
[BUG]: Error when starting LLama Cuda11/12

### ISSUE THREAD

**Issue by aropb** [SciSharp/LLamaSharp#903]
### Description

The program does not start, it gives such an error for Cuda 11 and 12. What could be the problem and where to look? Thank you.

NativeLibraryConfig Description:
- LibraryName: LLama
- Path: ''
- PreferCuda: True
- PreferredAvxLevel: NoAVX
- AllowFallback: True
- SkipCheck: False
- SearchDirectories and Priorities: { ./ }

Got relative library path 'runtimes/win-x64/native/cuda11/llama.dll' from local with (NativeLibraryName: LLama, UseCuda: True, AvxLevel: None), trying to load it...
Found full path file './runtimes/win-x64/native/cuda11/llama.dll' for relative path 'runtimes/win-x64/native/cuda11/llama.dll'
**Failed Loading './runtimes/win-x64/native/cuda11/llama.dll'**
Got relative library path 'runtimes/win-x64/native/llama.dll' from local with (NativeLibraryName: LLama, UseCuda: False, AvxLevel: None), trying to load it...
Found full path file './runtimes/win-x64/native/llama.dll' for relative path 'runtimes/win-x64/native/llama.dll'

nvcc -V

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

nvidia-smi

Wed Aug 21 00:22:57 2024
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 522.06       Driver Version: 522.06       CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A5000   WDDM  | 00000000:00:06.0 Off |                    0 |
| 30%   29C    P8    14W / 230W |    429MiB / 23028MiB |     29%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      6400    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A      6632    C+G   ...me\Application\chrome.exe    N/A      |
|    0   N/A  N/A      7000    C+G   ...y\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A      7156    C+G   ...w5n1h2txyewy\SearchUI.exe    N/A      |
+-----------------------------------------------------------------------------+

### Reproduction Steps

-

### Environment & Configuration

- Operating system: Windows Server 2019 Std 
- .NET runtime version: 8.0.8
- LLamaSharp version: 0.13.0
- CUDA version (if you are using cuda backend): 11
- CPU & GPU device: GPU NVIDIA A5000

### Known Workarounds

-

**Comment by aropb** [comment]
Do I understand correctly that this is due to the lack of avx2 on the CPU?

**Comment by martindevans** [comment]
Ah yes that would cause an issue - the CUDA binaries are compiled assuming AVX2 support. What CPU are you using?

**Comment by aropb** [comment]
This is a cloud-based virtual server and avx is not supported there at all. I wrote a program to check it. I'm dealing with them now. It would be great for you to add to the readme about avx.

**Comment by martindevans** [comment]
I think your best option will be to compile the binaries yourself. Make sure you use **exactly** the version of llama.cpp listed [here](https://github.com/SciSharp/LLamaSharp?tab=readme-ov-file#map-of-llamasharp-and-llamacpp-versions)!

**Comment by aropb** [comment]
To be honest, I would not like to do this, I have no experience in this at all. I'm afraid I'm wasting a lot of time. I hope that I will resolve the issue with avx2. I'll change the cloud as a last resort.

**Comment by martindevans** [comment]
You could probably just fork this repo, modify the [build script](https://github.com/SciSharp/LLamaSharp/blob/master/.github/workflows/compile.yml) to specify `-DGGML_AVX2=OFF` and run the action on Github :)
