### ISSUE TITLE
[BUG]: DefaultSamplingPipeline - strange behavior at high temperature

### ISSUE THREAD

**Issue by PioneerMNDR** [SciSharp/LLamaSharp#928]
### Description

I decided to try the popular configuration min_p = 0.1 and temp = 1.5 or higher.
I get the following **result**:

![image](https://github.com/user-attachments/assets/faeaae78-c3d7-4c40-b5ae-1a724b6379f4)

I used the example LLama.Examples/Examples/LLama3ChatSession.cs
To show the incorrect behavior.
**The only thing I changed**
`    var chatHistory = new ChatHistory();`
    and
```
   var inferenceParams = new InferenceParams
  {
      SamplingPipeline = new DefaultSamplingPipeline
      {
          Temperature = 1.5f,
          MinP=0.1f,
                            
      },

      MaxTokens = 100, // keep generating tokens until the anti prompt is encountered
      AntiPrompts = [model.Tokens.EndOfTurnToken!] // model specific end of turn string
  };
```

In my project I use BatchedExecutor with the correct formatting "Promt template" and Anti promts, and I get exactly the same result. I also changed the sampling order of ProcessTokenDataArray and it did not change anything. I tested it on CUDA and Vulkan. I noticed a pattern in that the first 20-30 tokens are correct, and then chaos begins.

In LM Studio and Kobold CPP I set the temperature even higher, and Min p even lower, but everything worked fine there

### Reproduction Steps

1. Use DefaultSamplingPipeline 
2. Set temperature higher than 1.2
3. Set min_p = 0.1 or higher

### Environment & Configuration

- Operating system: Win10
- .NET runtime version: 8.0.4
- LLamaSharp version: 0.16.0
- CUDA version (if you are using cuda backend): 12
- CPU & GPU device: RTX 3050 8gb and i5-12400
- Model: L3-8B-Stheno-v3.2-Q6_K.gguf

**Comment by martindevans** [comment]
If possible, could you try adding some breakpoints/logging into the calls [here](https://github.com/SciSharp/LLamaSharp/blob/master/LLama/Sampling/DefaultSamplingPipeline.cs#L123-L129). These are basically the lowest level calls, directly into llama.cpp

In particular looking for two things:
 - Are the values you set actually getting passed through correctly? Just to make sure there's not something overwriting the values you've set.
 - Are the other calls all being made with default values? Maybe try commenting them out just to be extra sure!

On a sidenote, the next version of LLamaSharp will be completely replacing sampling, because there has been a major redesign of the API on the llama.cpp side recently.

**Comment by PioneerMNDR** [comment]
These are the values ​​that are passed if they are not defined:
![image](https://github.com/user-attachments/assets/183a5c1f-ff9e-4271-bf6f-7227940bef05)
For the sake of purity of the experiment, I decided to comment out other samplers:
![image](https://github.com/user-attachments/assets/b44a8983-6575-433b-9b34-a0e06d57f899)

Nothing has changed(1):
![image](https://github.com/user-attachments/assets/e242797f-5624-4549-aad6-36f9c98ad3a0)
Nothing has changed(2):
![image](https://github.com/user-attachments/assets/2dc943cf-ad5e-421e-88c3-63a285e82ee1)
It feels like when he gets a high temperature he forgets EOS and starts hallucinating.
I decided to conduct an experiment. If I turn min_p up to 1, the model will always respond the same, regardless of temperature:
| ex num | pic | 
|----------|----------|
|  Ex1   | ![image](https://github.com/user-attachments/assets/e4b3f98e-7392-45e6-8b6a-711528be1898) |
|  Ex2   | ![image](https://github.com/user-attachments/assets/8a361cec-605d-46a7-860f-68dcbc7ec0dc)  |
|  Ex3    | ![image](https://github.com/user-attachments/assets/64eeeef4-1e83-44ca-a32e-50c8911d4eb8) |

The experiment shows that min_p sampler works. And I really don't understand what the problem is. True, I reduced min_p to 0.01, and he still told the joke about the bicycle

**Comment by PioneerMNDR** [comment]
In version 0.19.0 (and maybe even earlier) the problem is no longer observed. Thanks for updating samplers
