### ISSUE TITLE
Does v0.19.0 use llama.cpp 958367bf submit?

### ISSUE THREAD

**Issue by taotaow** [SciSharp/LLamaSharp#978]
### Description

why the code still use llama.cpp 11b84eb4 submit

**Comment by martindevans** [comment]
Oops, that's an oversight on my part. I forgot to update the submodule as part of the update process. Thanks for pointing it out.

Just to confirm 0.19.0 uses [958367bf](https://github.com/ggerganov/llama.cpp/tree/958367bf530d943a902afa1ce1c342476098576b].

**Comment by taotaow** [comment]
llama.cpp submit 958367bf support minicpm3 architecture,llama-cli.exe build from this submit can run minicpm3
but when I use llamasharpV0.19.0,error occurs:

> llama_model_load: error loading model: error loading model architecture: unknown model architecture: 'minicpm3'
> llama_load_model_from_file: failed to load model

test model path:
https://huggingface.co/mav23/MiniCPM3-4B-GGUF/blob/main/minicpm3-4b.Q4_K_M.gguf

**Comment by martindevans** [comment]
I just tried the linked model locally and it works fine for me.

Which platform are you using? Have you tried cloning the repo and running one of the examples with the model?

**Comment by taotaow** [comment]
I checked again,it's my mistake.V0.19.0 works fine.Thank you.

**Comment by martindevans** [comment]
Glad it turned out to be a simple issue :)
