### ISSUE TITLE
LoadWeightsFailedException: Failed to load model '<PATH>\wizardLM-7B.ggmlv3.q4_1.bin'

### ISSUE THREAD

**Issue by MrYossu** [SciSharp/LLamaSharp#999]
Started a new .NET7 Blazor server app (although being Blazor didn't make any difference, see P.S.) and followed the instructions on the main page. I installed the two packages, downloaded the `wizardLM-7B.ggmlv3.q4_1.bin` model from [https://huggingface.co/TheBloke/wizardLM-7B-GGML/tree/main](https://huggingface.co/TheBloke/wizardLM-7B-GGML/tree/main) and copied the code into my project. I used that model as it was suggested in [this blog post](https://blog.maartenballiauw.be/post/2023/06/15/running-large-language-models-locally-your-own-chatgpt-like-ai-in-csharp.html) (which is how I found this repo).

However, when I run the project, I get the error shown in the title.

I also tried versions 4.0 and 5.0 of the same model, but had the same problem. As I know absolutely nothing about these models, I have no idea how to find out which other model might work, if indeed that is the problem.

Anyone any idea what I'm doing wrong? I'd post code, but it's exactly the code from the main page, so no point. Here's my project file in case it helps...

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LLamaSharp" Version="0.19.0" />
    <PackageReference Include="LLamaSharp.Backend.Cpu" Version="0.19.0" />
  </ItemGroup>

</Project>
```

Thanks

P.S. Just to make sure, I created a console app and got the same exception, so nothing to do with Blazor.

**Comment by martindevans** [comment]
I just tried loading the model myself and had this message in the log: `gguf_init_from_file: invalid magic characters 'tjgg'`. That probably indicates that this is using an old model file format that is no longer compatible with llama.cpp.

WizardLMv2 is available now, and there are much newer model files available [here](https://huggingface.co/bartowski/WizardLM-2-7B-GGUF) which works with the latest version of llama.cpp/LLamaSharp.

Side note: technically .NET7 isn't supported anymore, it's lifetime ended a couple of months ago. You should upgrade to 8 (LTS) or 9.

**Comment by MrYossu** [comment]
@martindevans Thanks for that, loads fine now. Got a different problem now, but will open a new issue if I can't that sorted.

I know .NET7 is old. I whipped up a project to play with this, and used Blazor server, as that's what I'm most comfortable with. By default, that uses .NET7

Thanks again
